traitsui/qt4/table_model.py, traitsui/qt4/tabular_model.py
Fixes #194 
See https://bugreports.qt.io/browse/PYSIDE-20 for a discussion of the issue and workaround.
=> Workaround for PySide table alignment bug.

.travis.yml, CHANGES.txt, MANIFEST.in, dev_requirements.txt, setup.py, traitsui/__init__.py
Update the versioning system in the same way as Traits, Pyface, etc.
=> Add proper development versioning

setup.py
Release version bump (actual release is @7bc6252 and is tagged as such).
=> Release 4.5.0

CHANGES.txt, setup.py
Fixes #206 for maintenance branch.
=> Fix installation issue in maintenance branch

setup.py
=> Release 4.5.1

traitsui/wx/toolkit.py
This is a replacement for #153 which had a spurious commit. See that PR for discussion.
=> Fix for _popEventHandlers deleting handlers not added by traitsui

traitsui/qt4/text_editor.py
Split out from #117 as a separate PR.
=> Fix TextEditor spacing

traitsui/editors/progress_editor.py, traitsui/qt4/progress_editor.py, traitsui/qt4/text_editor.py
=> Qt ProgressEditor

CHANGES.txt, traitsui/qt4/list_str_editor.py, traitsui/tests/editors/test_liststr_editor_selection.py
=> Fix RuntimeError with selected trait in ListStrEditor

.travis.yml, dev_requirements.txt, travis-ci-requirements.txt
This is a minor cleanup removing unnecessary packages from being installed
=> Cleanup requirements for travis-ci

.gitignore
=> Add _version.py to the .gitignore file

examples/demo/Advanced/Apply_Revert_handler_demo.py, examples/demo/Advanced/Auto_editable_readonly_table_cells.py, examples/demo/Advanced/Date_editor_demo.py, examples/demo/Advanced/HDF5_tree_demo.py, examples/demo/Advanced/Property_List_demo.py, examples/demo/Advanced/Table_editor_with_live_search_and_cell_editor.py, examples/demo/Advanced/Time_editor_demo.py, examples/demo/Applications/Python_source_browser.py, examples/demo/Dynamic_Forms/dynamic_selector.py, examples/demo/Standard_Editors/CSVListEditor_demo.py, examples/demo/Standard_Editors/File_Dialog/File_Open_with_Custom_Extension.py, examples/tutorials/tutor.py, traitsui/editor_factory.py, traitsui/editors/api.py, traitsui/helper.py, traitsui/key_bindings.py, traitsui/qt4/check_list_editor.py, traitsui/qt4/enum_editor.py, traitsui/qt4/list_str_model.py, traitsui/qt4/table_model.py, traitsui/qt4/tabular_editor.py, traitsui/table_column.py, traitsui/value_tree.py, traitsui/wx/check_list_editor.py, traitsui/wx/enum_editor.py, traitsui/wx/helper.py, traitsui/wx/table_editor.py, traitsui/wx/table_model.py
Fixes which have come up in actual testing of examples.
=> Various Python 3 Fixes

traitsui/wx/helper.py, traitsui/wx/instance_editor.py, traitsui/wx/toolkit.py, traitsui/wx/ui_panel.py
This is the results of my first look at compatibility testing, there are likely still more changes that need to be made. I just wanted to get this PR created for now in case others would like to contribute to it.
WIP, don't merge yet. More to come as free time allows...
=> Fixes and updates for wxPython 3.0.x compatibility

CHANGES.txt, appveyor-install.cmd, setup.py
Update CHANGES.txt and setup.py for 5.0.0 release.
Not ready for merge yet (needs release flag set)
=> Release 5.0.0

README.rst, traitsui/qt4/code_editor.py, traitsui/qt4/editor.py, traitsui/qt4/tree_editor.py
PR catching up on a bunch of bugfix PRs from Master for maintenance branch.
=> Fixes from 5.0 master

CHANGES.txt, docs/source/traitsui_user_manual/front.rst, docs/source/traitsui_user_manual/intro.rst, traitsui/toolkit.py
=> Change default backend

traitsui/tests/test_toolkit.py, traitsui/toolkit.py
This is a fix for #258.  It's not perfect, but it will do for now.
=> Improve toolkit selection

traitsui/qt4/instance_editor.py, traitsui/qt4/table_editor.py, traitsui/qt4/ui_base.py, traitsui/qt4/ui_panel.py
From https://github.com/enthought/traitsui/pull/276, plus the cleanup suggested by @corranwebster  in comments there
@kitchoi @dpinte
=> Fix qt tableeditor segfault on editing close

CHANGES.txt, README.rst, setup.py, tox-requirements.txt, tox.ini, travis-ci-requirements.txt
Preparing for the next release.
=> Release 5.1.0

doc-requirements.txt, docs/make.bat
This PR fixes adds a doc-requirements.txt and fixes the readthedocs build (see http://traitsui.readthedocs.org/en/fix-readthedocs-build/) 
note: I also added a make.bat for those of us that use a windows machine
=> Fix readthedocs build

traitsui/ui_editors/data_frame_editor.py
Probably crept in when debugging.
=> Remove spurious print statements

traitsui/qt4/enum_editor.py
=> Fix integer division for enum editor on Python 3

traitsui/qt4/check_list_editor.py
=> Fix string comparision in CheckListEditor

.travis.yml, install_edm.sh, travis_ci_install.sh
Turn on OS X builds on top of EDM-based CI infrastructure.
=> Run CI tests on OS X

tasks.py
As written some of the suggested commands wouldn't work.
=> Quick fix for tasks.py documentation

codecov.yml
=> Fix syntax issues

traitsui/tests/ui_editors/test_data_frame_editor.py
=> Improve tests for dataframe editor

traitsui/qt4/boolean_editor.py, traitsui/qt4/button_editor.py, traitsui/qt4/check_list_editor.py, traitsui/qt4/code_editor.py, traitsui/qt4/date_editor.py, traitsui/qt4/editor_factory.py, traitsui/qt4/enum_editor.py, traitsui/qt4/extra/bounds_editor.py, traitsui/qt4/extra/range_slider.py, traitsui/qt4/file_editor.py, traitsui/qt4/font_editor.py, traitsui/qt4/history_editor.py, traitsui/qt4/html_editor.py, traitsui/qt4/instance_editor.py, traitsui/qt4/list_editor.py, traitsui/qt4/list_str_editor.py, traitsui/qt4/list_str_model.py, traitsui/qt4/range_editor.py, traitsui/qt4/set_editor.py, traitsui/qt4/table_editor.py, traitsui/qt4/tabular_editor.py, traitsui/qt4/tabular_model.py, traitsui/qt4/text_editor.py, traitsui/qt4/time_editor.py
Companion to https://github.com/enthought/pyface/pull/256  This may help with #325.
=> Remove old-style signals and slots

traitsui/qt4/list_editor.py
@corranwebster This fixes a bug left from #330.
=> BUG: Fix connection to Signal.

.travis.yml, tasks.py
Hopefully this should be no more than getting CI set up and using the new `pyface.qt` from Pyface.
=> Qt5 Support

.travis.yml, traitsui/qt4/list_str_editor.py, traitsui/qt4/table_editor.py, traitsui/qt4/tabular_editor.py
Move PyQt5 out of allowed failures on travis-ci and fix a few issues
=> Fix PyQt5 compatibility

traitsui/tests/_tools.py
This is causing CI failures for Enable currently: https://travis-ci.org/enthought/enable/jobs/247587609
=> Call unittest.skip correctly

traitsui/qt4/tree_editor.py, traitsui/wx/tree_editor.py
This fixes #385.  Includes some drive-by clean-up.
=> Fix value editor icons

traitsui/qt4/range_editor.py, traitsui/tests/editors/test_range_editor_text.py
=> Prevent loopback from slider when updating text field of range editor

traitsui/qt4/list_editor.py
Fixes #374.
Not sure of root cause of this (possibly a PyQt bug), but effectively reverting 2921e7d4619 so that we use indices rather than objects for the `QSignalMapper` signals seems to work.
Would be nice to have a test for this, but not sure how to do it.
=> Fixes issue where list item menus did not appear in PyQt

traitsui/color_column.py, traitsui/tests/test_color_column.py
This fixes #302.  Includes a simple smoke test for color column.
=> Fix for color column

traitsui/qt4/editor.py, traitsui/tests/test_labels.py, traitsui/wx/editor.py
=> Item label enable when support

appveyor.yml, etstool.py
=> fix appveyor test builds

.travis.yml, appveyor.yml, etstool.py, traitsui/tests/_tools.py, traitsui/tests/test_actions.py, traitsui/toolkit.py
Still have a couple of intermittent failures.  Turn on testing for Python 3.6.
=> Update CI matrixes

traitsui/editors/shell_editor.py
Uses new API from enthought/pyface#314
Fixes #446
=> Fix ShellEditor save_prefs

examples/tutorials/tutor.py, traitsui/basic_editor_factory.py, traitsui/dockable_view_element.py, traitsui/editors/tuple_editor.py, traitsui/file_dialog.py, traitsui/group.py, traitsui/handler.py, traitsui/key_bindings.py, traitsui/list_str_adapter.py, traitsui/qt4/list_editor.py, traitsui/qt4/ui_panel.py, traitsui/table_filter.py, traitsui/tabular_adapter.py, traitsui/ui.py, traitsui/ui_editor.py, traitsui/view.py, traitsui/wx/helper.py, traitsui/wx/history_editor.py, traitsui/wx/list_editor.py, traitsui/wx/scrubber_editor.py, traitsui/wx/table_editor.py, traitsui/wx/ui_panel.py
Fixes #333 
I don't see any uses of `HasTraits.get()`, I don't think.
=> BUG: Remove deprecated uses of HasTraits.set()

README.rst
Example didn't work as expected.
=> fix range editor in readme

traitsui/__init__.py, traitsui/qt4/tree_editor.py, traitsui/tree_node.py
Adds `six` to the list of dependencies.
=> BUG: Fix a Python 2-ism in the TreeEditor code.

traitsui/tree_node.py
=> Change getattr to xgetattr in tree get children

.travis.yml, etstool.py
The basic approach is to pin the pyside2 version for now.
=> Get Pyside2 tests working again

traitsui/wx/progress_editor.py
Fixes a typo for the `wx` backend for the progress editor.
=> NullColor -> NullColour

traitsui/qt4/tree_editor.py
Hopefully fixes #323 for real.
=> Fix unhashable node type

README.rst
=> Minor correction to test suite command

traitsui/editors/tabular_editor.py, traitsui/qt4/tabular_editor.py, traitsui/qt4/tabular_model.py
Fix #351 
~WIP for I would like to investigate:~
~(1) Adding tests~
~(2) Possibly same issue with TableEditor and ListStrEditor~
=> Fix TabularEditor.drag_move to properly allow drag-copy 

examples/demo/Advanced/Date_editor_demo.py, examples/demo/Advanced/Date_range_editor_demo.py, traitsui/api.py, traitsui/editors/api.py, traitsui/editors/date_editor.py, traitsui/editors/date_range_editor.py, traitsui/editors/styled_date_editor.py, traitsui/qt4/date_editor.py, traitsui/qt4/date_range_editor.py, traitsui/qt4/styled_date_editor.py, traitsui/tests/editors/test_date_editor.py, traitsui/tests/editors/test_date_range_editor.py
This pull request introduces a `DateRangeEditor` and this has a side-effect of implementing the `multi_select=True` functionality for the custom `DateEditor` in Qt.
=> Introduce DateRangeEditor (for Qt only)

examples/demo/Extras/Tree_editor_with_TreeNodeRenderer.py
=> Fix the tree sparkline demo

traitsui/qt4/toolkit.py, traitsui/qt4/ui_panel.py
=> Fix some stray divisions

traitsui/wx/helper.py
Thanks to @vladu for fix.
Fixes #9
=> Fix find closest display for Wx backend

traitsui/qt4/range_editor.py
=> Check that control exists before trying to get palette

docs/source/api/traitsui.qt4.tree_node_renderers.rst, docs/source/api/traitsui.rst, docs/source/api/traitsui.tree_node_renderer.rst, docs/source/traitsui_user_manual/adapters.rst, traitsui/qt4/tree_editor.py
Plus a minor fix to `QIcon` usage in TreeEditor.
=> Tree node renderer docs

traitsui/ui.py
=> Add a shadowed trait for the UI's key_bindings

traitsui/qt4/table_editor.py, traitsui/table_filter.py, traitsui/tests/editors/test_table_editor.py, traitsui/wx/table_editor.py
Fixes enabled state of Wx TableEditor search button (looks like error from bad merge).  Also fixes #475 and some other minor errors in the TableEditors.
=> Table editor filter and search UI fixes

README.rst
=> Fix etstool command in README

setup.py
=> Release 6.1.0

traitsui/qt4/file_editor.py, traitsui/qt4/helper.py, traitsui/qt4/image_enum_editor.py, traitsui/qt4/list_str_editor.py, traitsui/qt4/table_editor.py
This requires changes to pyface.qt, so will not work with anything before https://github.com/enthought/pyface/pull/371/commits/fb50a744fcc258b9351debb2535d370a4f7512cf
=> Better handling of qt4 and qt5 detection.

traitsui/base_panel.py
=> Fix dialog button handler signatures on Qt backend

traitsui/tests/editors/test_tree_editor.py, traitsui/tree_node.py
Fix for #556 and some other fixes to copy-pasted code.
=> Fix TreeNodeObject listener cache

traitsui/tree_node.py
Maintenance version of #560 (not waiting for tests).
=> Maint: Fix tree node insert

CHANGES.txt, setup.py
PR for a 6.1.1 release of TraitsUI.
=> Release 6.1.1

traitsui/tests/test_tree_node.py, traitsui/tree_node.py
=> BUG: Fix broken insert_child on TreeNode

traitsui/tests/test_toolkit.py
Import it from the standard library instead of importing it from `traits`.
=> Update unittest import

.travis.yml, appveyor.yml
We aren't getting CI builds on maintenance branches.
=> Build CI on maintenance branches

.travis.yml, appveyor.yml, etstool.py, traitsui/qt4/enum_editor.py, traitsui/qt4/helper.py, traitsui/qt4/tabular_editor.py, traitsui/qt4/tree_editor.py, traitsui/qt4/view_application.py, traitsui/tests/editors/test_tree_editor.py, traitsui/tests/test_toolkit.py, traitsui/tests/test_tree_node.py, traitsui/tests/test_view_application.py, traitsui/tree_node.py, traitsui/wx/custom_editor.py, traitsui/wx/helper.py, traitsui/wx/tree_editor.py, traitsui/wx/view_application.py
This is an omnibus PR pulling back bugfixes and CI improvements since 6.1.1 release.
This includes some important bugfixes needed for Mayavi.
=> Backport bugfixes to maint 6.1 branch

traitsui/ui.py, traitsui/view.py
Does the same for the `UI` class.  Also does some clean-up of old, commented out code.
Fixes #600
=> Make View icon trait an Image trait

traitsui/qt4/table_editor.py
Drive-by spelling fix, motivated by #609.
=> Fix typos in table_editor.py comments

etstool.py
=> Fix default Python version to be consistent in etstool.

traitsui/api.py
=> Add TabularAdapter to api

etstool.py, traitsui/wx/file_editor.py
Fixes #626.
Fixed the incorrect call, now file editor and directory editor demos are working.
=> Fix call to bind

traitsui/wx/range_editor.py
#632 
Handle exception in range editor when using compound_editor.
=> Fix compound_editor

traitsui/qt4/tests/test_helper.py
=> Allow '...' instead of ellipsis for elision test

traitsui/table_column.py
Fixes #655 
This makes it easier to make check box columns in Qt
=> Add bool type to allowed table column types

CHANGES.txt
Also add enhancements since the 6.1.0 release.
=> Update master CHANGES.txt to reflect 6.1.3 release

CHANGES.txt, setup.py
=> Release 6.1.3

traitsui/extras/progress_column.py
=> Fix typo in progress column exception

.travis.yml, appveyor.yml, install-edm-linux.sh, install-edm-osx.sh, install-edm-windows.cmd
This PR updates the CI systems to use the most recently released EDM (version 2.0.0).
=> Build: update Travis CI and Appveyor to use EDM 2.0.0.

traitsui/editor.py
The first in a series of PRs to replace #684 
This removes the use of eval in the `Editor` class and generally makes the synchronization code much clearer.
The code being changed has fairly comprehensive tests in `traitsui/tests/test_editor.py`.
=> Remove eval from base Editor

traitsui/editor.py
Last PR that replaces #684.
This is only a code reshuffle.  No functionality changes.
=> Reorganize Editor class layout to be more coherent

traitsui/qt4/tabular_editor.py
=> Fix column_clicked bug

docs/source/api/traitsui.extras.has_dynamic_views.rst, docs/source/api/traitsui.extras.rst, examples/demo/Advanced/Dynamic_views_demo.py, traitsui/extras/api.py, traitsui/extras/has_dynamic_views.py
It didn't really belong in Traits, moved into `traitsui.extras` and updated demo.
=> Move HasDynamicViews from traits

etstool.py, traitsui/__init__.py
=> Add docutils as an optional dependency of traitsui

traitsui/qt4/tabular_editor.py
=> Add check to use PyQt5-compliant API

.travis.yml, appveyor.yml, ci-src-requirements.txt, etstool.py
Also turn off CI for 2.7 and 3.5.
=> Test against Traits master

traitsui/api.py, traitsui/editors/__init__.py, traitsui/editors/api.py, traitsui/editors/datetime_editor.py, traitsui/qt4/datetime_editor.py
Required for  https://github.com/enthought/traits/issues/668
=> Add a DateTimeEditor

traitsui/api.py, traitsui/editors/__init__.py, traitsui/editors/api.py, traitsui/editors/datetime_editor.py
Fixes #730 
Related: https://github.com/enthought/traits/issues/811
=> Rename DateTimeEditor to DatetimeEditor

traitsui/wx/file_editor.py
- fix syntax error
- change some Binds to Unbinds
=> Fixes for wxPython FileEditor

examples/demo/Extras/Tree_editor_with_TreeNodeRenderer.py, traitsui/context_value.py, traitsui/editors/button_editor.py, traitsui/editors/csv_list_editor.py, traitsui/editors/file_editor.py, traitsui/editors/image_enum_editor.py, traitsui/editors/instance_editor.py, traitsui/editors/range_editor.py, traitsui/editors/table_editor.py, traitsui/editors/tuple_editor.py, traitsui/extras/demo.py, traitsui/qt4/button_editor.py, traitsui/qt4/check_list_editor.py, traitsui/qt4/code_editor.py, traitsui/qt4/color_trait.py, traitsui/qt4/editor.py, traitsui/qt4/extra/bounds_editor.py, traitsui/qt4/file_editor.py, traitsui/table_column.py, traitsui/tabular_adapter.py, traitsui/tests/editors/test_button_editor.py, traitsui/tests/editors/test_tabular_editor.py, traitsui/tests/test_context_value.py, traitsui/tree_node.py, traitsui/ui_editors/data_frame_editor.py, traitsui/undo.py, traitsui/wx/color_trait.py, traitsui/wx/extra/bounds_editor.py, traitsui/wx/ui_wizard.py
Make use of improvements from Traits 6.0.
Fixes #769
=> Traits 6.0 updates

CHANGES.txt, ci-src-requirements.txt, docs/source/conf.py, etstool.py, setup.py, traitsui/context_value.py, traitsui/editors/button_editor.py, traitsui/editors/csv_list_editor.py, traitsui/editors/table_editor.py, traitsui/qt4/extra/bounds_editor.py, traitsui/table_column.py, traitsui/tabular_adapter.py, traitsui/tree_node.py, traitsui/ui_editors/data_frame_editor.py, traitsui/wx/extra/bounds_editor.py, traitsui/wx/ui_wizard.py
=> TraitsUI 7.0 Release

ci-src-requirements.txt
As with Pyface, continue to test against released Traits versions.
=> Test against Pyface master branch

traitsui/extras/demo.py
=> Fix the back button in the demo

examples/demo/Standard_Editors/DatetimeEditor_demo.py, traitsui/editors/datetime_editor.py, traitsui/qt4/datetime_editor.py, traitsui/tests/editors/test_datetime_editor.py
Fixes #802 
Adds a demo for the editor.
=> Fixes for Qt DatetimeEditor

etstool.py, traitsui/__init__.py, traitsui/tests/_tools.py
Addresses #613
The PR follows https://github.com/enthought/pyface/pull/515.
This only modifies the test runner, the tests themselves are modified in #809, which is the PR that should be merged first.
=> Switch to unittest test runner

traitsui/wx/ui_panel.py
Fixes #828.
It is possible we may need to do some further tweaking of Wx layout with this being removed, but this fixes the immediately reported problem.
=> Remove align centre which was causing problems

traitsui/tests/editors/test_image_enum_editor.py, traitsui/wx/ui_panel.py
Adds tests for image enum editor.
=> Add image enum editor tests

traitsui/tests/test_theme.py, traitsui/theme.py
Closes #825 
PR adds toolkit checks before wx imports
=> Fix Theme pickling

traitsui/qt4/tabular_editor.py
Fixes #988 . Feedback requested.
=> Avoid Qt5 crash from out-of-sync user_widths.

CHANGES.txt, traitsui/qt4/extra/bounds_editor.py, traitsui/qt4/range_editor.py
This PR backports bug fixes from #999 and #1000 for 7.0.1 release.
This PR also updates the changelog (which needs review)
=> Backport fix for integer division in Qt RangeEditor and BoundsEditor

setup.py
First commit is the release commit where IS_RELEASED is True.
Then we bump the version for 7.0.2 and set IS_RELEASED to False.
Ref: #933
=> Bug fix release 7.0.1

CHANGES.txt
This PR backports changelog released with 7.0.1 back to master.
Ref: #933
=> Backport changelog from 7.0.1 to master

CHANGES.txt, docs/source/traitsui_user_manual/factories_advanced_extra.rst, docs/source/traitsui_user_manual/factories_basic.rst, docs/source/traitsui_user_manual/glossary.rst, traitsui/dockable_view_element.py, traitsui/menu.py, traitsui/qt4/code_editor.py, traitsui/qt4/ui_panel.py, traitsui/wx/code_editor.py, traitsui/wx/table_editor.py, traitsui/wx/table_model.py, traitsui/wx/ui_panel.py
As mentioned in the comments on issue #584 this is the first PR for fixing the comments, docstrings, documentation, etc.  
Another PR will handle the deprecation associated with PyFaceAction.
=> PyFace to Pyface change (non-code)

setup.py
=> Added long_description_content_type

setup.cfg
=> removed top-level setup.cfg file

checksums
=> removed checksums file

TODO.txt
fixes #1012 - All items in TODO.txt file have been added as Github issues (see issue #1021 )
=> removed TODO.txt file

docs/source/tutorials/traits_ui_scientific_app.rst
=> fixed minor typos in tutorial

ets-demo/LICENSE.txt, ets-demo/image_LICENSE_Nuvola.txt
fixes #1045 
@kitchoi can you confirm I copied these files to the right directory.  I wasn't sure if they should go to `ets-demo` or `ets-demo/estdemo`
=> copied license files from traitsui root directory to ets-demo

etstool.py
adding description of use of --editable flag.
=> updated traitsui etstool docstring to match that of pyface 

setup.py
This implements a suggestion made on PR #1047
=> Convert extracting of long_description from readme to a context manager

.travis.yml, appveyor.yml, ets-demo/etstool.py, etstool.py
=> updated edm version in travis and appveyor config files

traitsui/examples/demo/Advanced/Adapted_tree_editor_demo.py, traitsui/examples/demo/Advanced/Auto_update_TabularEditor_demo.py, traitsui/examples/demo/Advanced/History_demo.py, traitsui/examples/demo/Advanced/Property_List_demo.py, traitsui/examples/demo/Applications/Python_source_browser.py, traitsui/examples/demo/Standard_Editors/File_Dialog/File_Open.py, traitsui/examples/demo/Standard_Editors/File_Dialog/File_Open_with_Custom_Extension.py, traitsui/examples/demo/Standard_Editors/File_Dialog/File_Open_with_FileInfo_Extension.py, traitsui/examples/demo/Standard_Editors/File_Dialog/File_Open_with_ImageInfo_Extension.py, traitsui/examples/demo/Standard_Editors/File_Dialog/File_Open_with_Multiple_Extensions.py, traitsui/examples/demo/Standard_Editors/File_Dialog/File_Open_with_TextInfo_Extension.py
=> Fix demo descriptions

docs/source/conf.py
=> fixing broken link

traitsui/examples/demo/Standard_Editors/ButtonEditor_simple_demo.py
=> Adding a comment for ButtonEditor_simple_demo

ets-demo/etsdemo/main.py, ets-demo/etsdemo/tests/test_main.py
Closes #1026
This PR adds a basic context manager for configuring logger in the main function such that the configuration is cleaned up upon exiting the context. Currently we only log to console.
Command line options are added for setting the log level.
=> Configure logging for etsdemo main function

etstool.py, traitsui/api.py, traitsui/base_panel.py, traitsui/basic_editor_factory.py, traitsui/color_column.py, traitsui/delegating_handler.py, traitsui/dock_window_theme.py, traitsui/editor_factory.py, traitsui/handler.py, traitsui/help_template.py, traitsui/helper.py, traitsui/instance_choice.py, traitsui/key_bindings.py, traitsui/list_str_adapter.py, traitsui/menu.py, traitsui/message.py, traitsui/qt4/extra/progress_renderer.py, traitsui/table_column.py, traitsui/toolkit.py, traitsui/tree_node.py, traitsui/ui.py, traitsui/ui_editor.py, traitsui/ui_info.py, traitsui/ui_traits.py, traitsui/undo.py, traitsui/value_tree.py, traitsui/view_element.py, traitsui/view_elements.py
I was stuck on most of my other issues, and wanted to try to make some form of a tangible contribution.  Rahul had mentioned flake8 isn't currently being used on traitsui and pyface, but that ideally it would be.  I decided to try and do a style clean up and fix a bunch of flake8 errors.  I quickly realized my efforts were futile, at least for now, and stopped here.  Regardless I thought I would open a PR as even some style fixes can't hurt (although I apologize for the tedious PR review).
=> fixing some simple flake8 errors

ets-demo/MANIFEST.in
I neglected to add the new file `CHANGES.txt` to `MANIFEST.in` in #1109. This PR adds the file so that the changelog is included in the source distribution.
For #1031
=> Include CHANGES.txt in MANIFEST.in

ets-demo/setup.py
This PR bumps the `etsdemo` version on master for the development of the next release.
=> Bump version for development of the next release for etsdemo

ets-demo/setup.py
This PR sets the release flag to true for the etsdemo release branch.
For #1031
=> Release etsdemo 0.1.0

traitsui/qt4/list_str_editor.py, traitsui/qt4/tree_editor.py
Fixes two other occurrences of https://github.com/enthought/traitsui/issues/1098
=> Fix deprecation warnings regarding collections.abc in ListStrEditor and TreeEditor

docs/source/traitsui_user_manual/factories_basic.rst
=> Line of code in examples was missing

ets-demo/etsdemo/app.py, ets-demo/etsdemo/tests/test_app.py, setup.py, traitsui/context_value.py, traitsui/editor.py, traitsui/extras/_demo_legacy.py, traitsui/qt4/color_editor.py, traitsui/table_filter.py, traitsui/tests/test_context_value.py, traitsui/wx/list_editor.py
=> Cleanup some Python 2 compat code

traitsui/testing/tester/locator.py, traitsui/testing/tester/qt4/default_registry.py, traitsui/testing/tester/qt4/helpers.py, traitsui/testing/tester/qt4/implementation/check_list_editor.py, traitsui/testing/tester/wx/default_registry.py, traitsui/testing/tester/wx/helpers.py, traitsui/testing/tester/wx/implementation/check_list_editor.py, traitsui/tests/editors/test_check_list_editor.py
Implements the final bullet on issue #1149
=> UI Tester Update - adding check list editor implementation

integrationtests/test_all_examples.py, traitsui/testing/tester/locator.py, traitsui/testing/tester/registry_helper.py, traitsui/testing/tester/tests/test_ui_tester.py, traitsui/testing/tester/ui_tester.py, traitsui/testing/tester/ui_wrapper.py
fixes #1195 by implementing find_by_id.
=> UI Tester updates - find by id

traitsui/testing/tester/qt4/helpers.py, traitsui/testing/tester/qt4/implementation/list_editor.py, traitsui/testing/tester/wx/helpers.py, traitsui/testing/tester/wx/implementation/list_editor.py, traitsui/tests/editors/test_list_editor.py
=> UI Tester updates - implement notebook list editor

traitsui/qt4/check_list_editor.py, traitsui/qt4/enum_editor.py, traitsui/wx/check_list_editor.py, traitsui/wx/enum_editor.py
The code was a bit difficult to understand (see PR #1191 for reference) so I added a few quick comments to. hopefully make it a little clearer for someone looking in the future.  Eventually we may want to refactor this code all together so that it is simpler to follow.
=> Adding inline comments to EnumRadioEditor and CheckList editor code for populating grid

integrationtests/test_all_examples.py
This is the first "example" (which is actually a test of a traitsui example/demo) to be added for UI Tester. 
Addresses part of #1220
=> adding UI Tester test/example for ButtonEditor_simple_demo.py

integrationtests/test_all_examples.py
part of #1220 
Adds a simple test to see that we can navigate to a tab and change traits of a person, and also that the index trait for the demo is updated.
=> adding UI Tester test/example for List_editor_notebook_selection_demo.py

traitsui/testing/tester/ui_wrapper.py
This PR makes changes to the docstring of UIWrapper so that they provide more information.
=> Fix and expand docstring for UIWrapper

docs/source/traitsui_user_manual/testing.rst
This PR fixes a few small language / visual issues in the user manual for UITester.
=> Doc: Minor improvements to UITester user manual

examples/tutorials/doc_examples/examples/array_editor.py, examples/tutorials/doc_examples/examples/configure_traits_view.py, examples/tutorials/doc_examples/examples/configure_traits_view_buttons.py, examples/tutorials/doc_examples/examples/configure_traits_view_group.py, examples/tutorials/doc_examples/examples/default_trait_editors.py, examples/tutorials/doc_examples/examples/default_traits_view.py, examples/tutorials/doc_examples/examples/enum_editor.py, examples/tutorials/doc_examples/examples/handler_override.py, examples/tutorials/doc_examples/examples/instance_editor_selection.py, examples/tutorials/doc_examples/examples/key_bindings.py, examples/tutorials/doc_examples/examples/mixed_styles.py, examples/tutorials/doc_examples/examples/multi_object_view.py, examples/tutorials/doc_examples/examples/multiple_views.py, examples/tutorials/doc_examples/examples/override_editor.py, examples/tutorials/doc_examples/examples/tree_editor.py, examples/tutorials/doc_examples/examples/view_attributes.py, examples/tutorials/doc_examples/examples/view_multi_object.py, examples/tutorials/doc_examples/examples/view_standalone.py, setup.cfg, traitsui/default_dock_window_theme.py, traitsui/dockable_view_element.py, traitsui/editor.py, traitsui/editor_factory.py
In this PR I simple started going through the list of flake8 excluded files in setup.cfg and cleaned them up/removed them from setup.cfg.
=> Flake8 clean files and remove from setup.cfg

appveyor.yml
[Targeting maint/7.1 branch]
This makes sure any new changes brought to the maintanence branch are run on Appveyor.
=> Add maint/7.1 to the branches being tested on Appveyor

traitsui/image/image.py
Related to #1024
This PR updates the deprecation warning message with more up-to-date information.
=> Update deprecation warnings for removing traitsui.image

setup.py
For #1419
I will open a separate PR to flip IS_RELEASED to false and bump the version after this one is merged.
=> TraitsUI Release 7.1.1

CHANGES.txt
=> Update changelog after release of 7.1.1

traitsui/api.py, traitsui/editors/api.py
This PR adds a module docstring to the `traitsui.api` and `traitsui.editors.api` modules.
=> Add a module docstring to the api modules

ets-demo/etstool.py
=> Add pygments to etsdemo's etstool.py

traitsui/wx/date_editor.py, traitsui/wx/time_editor.py
This PR removes a few meaningless comments that exist in the codebase, probably the result of a now-outdated coding style.
=> Remove meaningless comments from an outdated coding style.

.github/workflows/test-etsdemo.yml, .github/workflows/test-with-edm.yml
This PR updates EDM from 3.2.1 to 3.2.3 (the latest).
=> Use EDM 3.2.3 instead of EDM 3.2.1

traitsui/handler.py
Together with #1583, #1587 , #1588 and #1589 , this PR fixes #1167
Looks like I missed this one in the earlier PRs.
=> Call super without any arguments

setup.py
This PR is for TraitsUI 7.2.0 release. 
**Checklist**
=> Release TraitsUI 7.2.0

CHANGES.txt
This PR simply updates the changelog to match the changes which were made to `maint/7.2` 
**Checklist**
=> Update changelog to match maint/7.2

traitsui/editors/table_editor.py
=> Remove "Does not work on Qt." comments for traits which now do work with Qt

traitsui/examples/demo/Extras/Image_editor_demo.py
Illustrates the new capabilities from Pyface 7.4.0.  Modified UI looks like this:
The gradient comes from an RGB array built dynamically in the example.
**Checklist**
=> Add a dynamically created ArrayImage to the ImageEditor example.

traitsui/qt4/progress_editor.py, traitsui/wx/progress_editor.py
Fixes #1787
This just pushes any sanity checking of values down to the underlying code in Pyface.
**Checklist**
=> Fix issue with resetting the `ProgressEditor`

setup.py
Set the release flag.  This branch has been:
- tested from sdist
- the documentation builds
=> Release 7.3.0

setup.py
Increment minor version number, and reset release flag.
=> Post-release version bump

traitsui/qt4/image_enum_editor.py
=> Enforce use of int for Qt code.  Final fix for #1681

CHANGES.txt, traitsui/qt4/file_editor.py, traitsui/qt4/image_enum_editor.py, traitsui/qt4/key_binding_editor.py, traitsui/tests/editors/test_file_editor.py, traitsui/wx/file_editor.py
Cherry-pick #1860, #1862 and #1864 back to maint/7.3
Includes update to change log.
=> Cherry pick fixes to 7.3 maintenance branch

setup.py
=> Release 7.3.1

setup.py
=> Post release version bump

CHANGES.txt
This adds the 7.3.1 change log to the main branch.
=> Update change log for release 7.3.1

.github/workflows/publish-on-pypi.yml
This is the same as the pyface and traits-futures versions.
=> Add publish on PyPI workflow.

traitsui/qt4/check_list_editor.py, traitsui/qt4/color_editor.py, traitsui/qt4/enum_editor.py, traitsui/qt4/list_editor.py
=> Fix for mappedInt/mappedString API change in PySide2 for < 5.15.0

setup.py
Release PR for TraitsUI 7.4.0
**Checklist**
=> Release 7.4.0

setup.py
Post-release version bump for main branch.
**Checklist**
=> Post release version bump.

setup.py
=> Release 7.4.1

CHANGES.txt, traitsui/qt4/file_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_interaction_helpers.py, traitsui/testing/tester/_ui_tester_registry/wx/_interaction_helpers.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/button_editor.py, traitsui/wx/file_editor.py
It looks like we missed a couple of bugfixes in the previous PR. This adds them.
=> More 7.4.1 backports

setup.py
Set things up in case we need a 7.4.3 release.
=> Post 7.4.2 version bump

CHANGES.txt, docs/releases/upcoming/1960.bugfix.rst, docs/releases/upcoming/1964.bugfix.rst, docs/releases/upcoming/1966.bugfix.rst, docs/releases/upcoming/1967.bugfix.rst, docs/releases/upcoming/1972.test.rst, docs/releases/upcoming/1973.bugfix.rst, setup.py
Changelog update and release PR.
=> Release 7.4.3

.github/workflows/test-build-documentation.yml, CHANGES.txt, README.rst, docs/source/conf.py, docs/source/traitsui_user_manual/intro.rst, pyproject.toml
This PR:
- Updates the changelog for 8.0
- describe changes to toolkit behaviour
- adds tests for documentation on each PR
=> Update documentation in preparation for 8.0 release

pyproject.toml
=> Release 8.0.0
