enthought/traitsui

docs/source/conf.py
Can't exec `__init__.py` any more because it uses absolute imports; instead exec `_version.py`.
=> Import version correctly for development versioning

traitsui/qt4/list_editor.py, traitsui/wx/list_editor.py
ListEditor in notebook style crashes with the following error whenever the model object is given in extended name notation:
traits.trait_errors.TraitError: Trait notification dispatch type 'ui' is not compatible with handler signature and extended trait name notification style
A search through old emails reveals that this bug was found in 2009, but the fix was never propagated to the notebook editor.
=> bugfix: notebook list editor works with extended name notation

appveyor-install.cmd, appveyor-test.cmd, appveyor.yml
This PR adds appveyor to the ci setup. There are two builds run on python 2.7 windows 64bit and python 3.4 windows 64bit.
=> Add appveyor setup files

traitsui/qt4/code_editor.py, traitsui/qt4/editor.py
The first fix is for split layouts when using visible_when to hide groups, which caused an error.
The second fix is for auto_set=False in Qt CodeEditor which was completely ignored (works in WX). Note that this requires also my pyface pull request
=> Fix: allow hiding of groups in split layouts. Fix auto_set=False behavior of CodeEditor

docs/source/conf.py
Use @rkern's `enthought_sphinx_theme` if installed when building the docs.  If not available, it will default to the old style.
I haven't added any formal dependency, since we haven't published the theme to PyPI.
=> Enthought Sphinx Theme Support

traitsui/qt4/tree_editor.py
Fixes #250.
When going from having no children to having children, nodes were not being updated to indicate that they could be expanded.  The tree editor handles this by adding a dummy child to the unexpanded node so that Qt will flag it as expandable.  This was not happening in the handlers for replacing all children or updating children for a node in the case where they were not expanded and started with no children.
A better fix for this would be to replace the nodes in the Qt model with `QModelViewItem` subclasses instead of `QTreeWidgetItem`s, but that's a substantial amount of work.
=> Fix empty tree nodes not changing when adding children.

traitsui/wx/themed_window.py
This PR changes ThemedWindow to use the wx HasCapture method instead of trying to track the state itself.
wxPython 3 is more strict about capturing the mouse, and no longer allows a widget to capture it if it already holds the capture, and it's also possible for the capture to be stolen by another widget.  So trying to track the state of the capture in a local attribute can sometimes have holes, resulting in assertion errors from wx.
=> Fix wx capture mouse issue.

traitsui/qt4/list_editor.py
Two traits were present twice. I removed the duplicated entries.
=> Removes duplicated traits in NotebookEditor

traitsui/list_str_adapter.py, traitsui/tests/editors/test_liststr_editor.py
Solves issue #269. The root cause was that the adapter was not able to deal with
None objects. This is already performed in the TabularAdapter, and was missing in
the ListStrAdapter. The result was that ListStrModel.rowCount was raising exception
because at deinitialization, the editor trait object can be None. It is sensible in
this case that the adapter simply returns zero.
=> Fixes exception occurring during disposal of ListStrEditor

traitsui/qt4/tests/test_ui_panel.py, traitsui/qt4/ui_base.py, traitsui/qt4/ui_panel.py
The Mayavi2 application do not show the toolbar for the pipeline (one of the workbench panels) when the backend is Qt4.
This will allow the panel to add the toolbar to the window.  However, the toolbar would be added to the main window instead of the panel.  The full fix for mayavi would require https://github.com/enthought/pyface/pull/192 for the toolbar to appear in the panel it's associated with.
Before:
After:
=> Add toolbar in Qt UI panel (fix for Mayavi)

traitsui/wx/themed_window.py
This is related to enthought/traitsui#265. The behavior of themed_windows was still a little buggy with some missed click events. I think this may solve the issue.
=> Fix wx _left_up() event for themed windows

docs/source/traitsui_user_manual/factories_advanced_extra.rst, examples/demo/Advanced/Table_editor_with_progress_column.py, traitsui/extras/progress_column.py, traitsui/qt4/extra/progress_renderer.py, traitsui/tests/editors/test_table_editor.py
Probably want a little more customization, but this is the basics of `TableEditor` column which displays progress bars.
=> TableEditor column with progress bar

traitsui/wx/color_editor.py, traitsui/wx/editor_factory.py, traitsui/wx/extra/bounds_editor.py, traitsui/wx/file_editor.py, traitsui/wx/range_editor.py, traitsui/wx/scrubber_editor.py, traitsui/wx/text_editor.py, traitsui/wx/themed_slider_editor.py, traitsui/wx/themed_text_editor.py
`Skip()` should always be called for kill-focus events of native widgets, especially `wx.TextCtrl`s.
Not calling Skip for these events is one of those things that may accidentally work in some cases, but was never the correct thing to do unless it is a generic widget or you are overriding all the native behavior.
See https://enthought.zendesk.com/agent/tickets/63321 for an example of breakage with wxPython 3.0.
Fixes #282
=> Fix skip kill-focus events

traitsui/qt4/tree_editor.py
This prevents the dragged item from being disconnected from the mouse
pointer if the drag takes a long time to start.
Fixes #292
=> Fix offset when dragging items in a Qt TreeEditor

appveyor.yml
Update to Appveyor default pip version broke the Appveyor CI tests.  This should fix.
=> Fix appveyor pip install command

traitsui/qt4/table_model.py
Dragging and dropping fails for Qt tables, this clearly looks like a typo.
=> Fix Qt table model drop mime typo

traitsui/qt4/enum_editor.py
Fixes "TypeError: list indices must be integers or slices, not float"
``incr`` is a list of floats due to its computation. In python3 floats cannot be used for indexing.
=> Fix TypeError in Python3

docs/source/traitsui_user_manual/intro.rst
See https://github.com/enthought/traits/pull/326. Should wait for that to be merged.
=> Remove references to '-toolkit' option

traitsui/file_dialog.py, traitsui/image/image.py, traitsui/wx/dnd_editor.py
Fixes #297.
The `2to3` infrastructure apparently doesn't auto-replace uses of `file` with `open` (probably because they aren't equivalent in some versions of Python 2).  This PR does a manual removal of all uses of `file`.
=> Replace file with open in a few places

examples/demo/Useful/using_springs.py
The `using_springs` demo mentioned that using a Spring didn't move
widgets down, but it actually does. This updates the statement to say
that it works.
"Proof" that it works:
=> Fix comment saying vertical springs don't work

traitsui/qt4/instance_editor.py, traitsui/tests/editors/test_instance_editor.py
Fixes #331.  The change keeps the sub-dialog UI around so that clean-up can be done for the non-modal version.  This distinctly simplifies the handling of the case where the editor is destroyed before the user closes the child UI.
=> Properly handle dialog lifecycle for simple InstanceEditor

traitsui/qt4/tree_editor.py
Fixes #323 where under PyQt and Python 3 `QTreeWidgetItems` are not hashable.
Also improves safety of blocking signals.
=> Fix TreeEditor label updates for PyQt and Python 3

traitsui/qt4/enum_editor.py
Enum editor was using the wrong typed version of the `QComboBox` `currentIndexChanged` signal.  This is a regression introduced by #330.
=> Fix regression from removing old-style signals & slots

.travis.yml, tasks.py, travis_ci_bootstrap_edm.sh
This PR goups the builds in travis based on the used runtime to reduce the cache size
In more details
- There are 6 ( < 9) builds now
- The retrieve files functionality now support glob patterns
- Coverage is combined at the end of the build so that we still get the right combined coverage in codecov
=> Group builds in travis

traitsui/qt4/helper.py
Hi,
this PR fixes failure with Qt5, e.g. for examples/demo/Standard_Editors/ListEditor_demo.py
With PyQt5 (tested with 5.6.0 from conda) QPixmapCache has a slightly different API.
=> fix for use with qt5, QPixmapCache

traitsui/qt4/button_editor.py, traitsui/tests/editors/test_button_editor.py, traitsui/wx/button_editor.py
Fix #355.
- Get label from editor factory or the UI label
- Synchronize button label
=> Fix setting button label from another traits in CustomEditor

traitsui/wx/toolkit.py
Drive-by cleanup: removes the unused `drop_target` argument to `GUIToolkit.hook_events` for the wx backend. This also makes the API consistent between the wx backend and the Qt backend.
=> Remove an unused argument to wx.hook_events.

traitsui/qt4/toolkit.py
A TraitsUI-using application was producing a FatalError in its test run of the following form:
```
test_h5_tool (test_package.TestH5Tool) ... Exception AttributeError: "'KeyEventHook' object has no attribute 'eventFilter'" in 'garbage collection' ignored
Fatal Python error: unexpected exception during garbage collection
Abort trap: 6
```
This PR fixes that error, by making `KeyEventHook` a module-level class, so that its `eventFilter` method isn't collected as part of regular cyclic garbage collection.
I'm not having much luck producing a minimal TraitsUI-only example at the moment, but will keep trying for a bit: it would be good to have a regression test for this.
=> Fix potential FatalError during garbage collection.

traitsui/qt4/tabular_editor.py, traitsui/table_column.py
The `raise_to_debug` method:
- is in `traitsui.api` not `traits.api`
- does the check for the `TRAITS_DEBUG` environment variable for you.
Fixes #361 and another similar issue.
=> Fix a couple of calls to raise_to_debug

README.rst
Was pointing at @itziakos old account, switch it to point at the EnthoughtOSS version.
=> Fix target of Appveyor badge

traitsui/tests/test_tuple_editor.py
A drive-by cleanup: in the original code, if `model.edit_traits()` fails, a `NameError` for `ui` will be raised in the `finally` clause, obscuring (or replacing, in Python 2) the original traceback.
Also removes the unnecessary `ui is not None` check: `ui` will either be a `UI` object, or undefined.
=> Cleanup: Fix a broken try/finally pattern in a test.

traitsui/editor.py, traitsui/qt4/tabular_editor.py, traitsui/tests/editors/test_tabular_editor.py
[Includes commits from #372; that should be reviewed first.]
`Editor.sync_value` currently does two things:
- Sets up trait change handlers in the appropriate directions to synchronize a user object trait with the corresponding editor trait.
- Sets the initial values of those traits to be equal.
The second action is inappropriate for `Event` traits, and fails with an exception under `TRAITS_DEBUG=1`.
This PR adds an `is_event` optional argument to the `sync_value`, and uses it in the `TabularEditor`. There are likely other places that it should be used.
I feel dirty for making a complicated and horrible method even more complicated and horrible, but it seems easier to add this quick fix and then refactor in a separate PR (coming soon, honest!) rather than try to do both at once.
Fixes …
=> Make it possible to avoid reading Event trait values in Editor.sync_value

traitsui/qt4/check_list_editor.py
#378 fixed the exception thrown when choosing the values from the dropdown
We found that the text variable is ok to use instead of calling the index of the value.
=> fix bug in update_object function

docs/source/traitsui_user_manual/custom_view.rst, docs/source/traitsui_user_manual/view.rst
- Replace the tables describing the arguments to Item, Group and View, with something more definition-like. The documentation for each argument comes from our teaching documentation, as well as from the trait comments from the code. 
- Add more Item subclass definitions and reformat them as a table, like the Group subclasses.
=> DOC: Document Item, Group, and View in the user manual

docs/source/traitsui_user_manual/handler.rst, traitsui/handler.py, traitsui/qt4/ui_base.py, traitsui/tests/test_handler.py, traitsui/wx/ui_base.py
This adds a `perform` method to the base `Handler` class and shifts the common `Action` perform dispatch logic out of the toolkit `BaseDialog` classes.
This should be largely backwards compatible: obviously any existing user `Handler` subclass with a `perform` will have a problem, and there are some subtle differences in what methods will be checked (eg. `_<action.name>_clicked` can be called for menu toolbar items and in addition to buttons, if `action.action` is not defined).
Fixes #383 and a TODO left open in #56.
Also cleans up a couple of other issues (eg. `ui_base.ButtonEditor` was not correctly initialised)
=> Improve TraitsUI Action handling

traitsui/tests/null_backend/test_null_toolkit.py, traitsui/toolkit.py
Fixes #390 
Typical error message will now look like this:
```
File "examples/demo/Standard_Editors/BooleanEditor_demo.py", line 68, in <module>
demo.configure_traits()
File "/Users/cwebster/.edm/envs/edm/lib/python2.7/site-packages/traits/has_traits.py", line 2172, in configure_traits
kind, handler, id, scrollable, args )
File "/Users/cwebster/src/ets/traitsui/traitsui/toolkit.py", line 309, in view_application
not_implemented_message.format(ETSConfig.toolkit))
NotImplementedError: the 'null' toolkit does not implement this method
```
=> Better error messages when toolkit doesn't implement methods

traitsui/qt4/ui_base.py
#384 broke action dialog buttons on Qt.
This fixes signature of the `perform` method of `traitsui.qt4.ui_base.ButtonEditor` to match what the Qt button's `clicked` signal expects.
=> Fix action buttons in Qt

traitsui/tests/test_actions.py
=> Add tests for actions bound to buttons

etstool.py
Current build of pyqt appears to be bad on windows.  Temporary downgrade for CI system.
=> Avoid PyQt 4.12-1 build

traitsui/qt4/check_list_editor.py
When the signal connections were upgraded to the new style in #330,
some of them actually required the argument type specification to select
the correct C++ overload of the signal.
Ping @corranwebster
=> BUG: Fix the signal connection.

traitsui/wx/image_control.py, traitsui/wx/list_editor.py
Two fixes:
- be paranoid about making any callback that could delete the menu button happen in a `CallAfter` or with `dispatch='ui'`.
- manually delete children of scrolled panel because `DestroyChildren` seems to have issues.
Fixes  #337.
=> Fix list editor menu segfaults on Wx

traitsui/tests/ui_editors/test_data_frame_editor.py, traitsui/ui_editors/data_frame_editor.py
Corrects 2 copy-pasta typos, in the `DataFrameEditor` and its test suite.
=> Fix: df editor typos

traitsui/qt4/table_editor.py, traitsui/qt4/tree_editor.py, traitsui/qt4/ui_panel.py, traitsui/tests/editors/test_tree_editor.py
The conversion of `QBytes` to something that the TraitsUI preferences (really, widget-state) saving machinery can deal with was not made Python-3-safe. I stuck a quick smoke test in for the `TreeEditor` (which caused the report enthought/mayavi#576 bug), but there were a few other problematic editors that I fixed (untested).
Fixes enthought/mayavi#576
=> Fix Qt widget state saving for Python 3

setup.py, traitsui/null/__init__.py, traitsui/qt4/__init__.py, traitsui/qt4/toolkit.py, traitsui/tests/test_toolkit.py, traitsui/toolkit.py, traitsui/wx/__init__.py, traitsui/wx/toolkit.py
This PR does a few things:
- allows adding new toolkits via `pkg_resources` entrypoints.
- leans on the pyface toolkit mechanisms where practical, reducing duplicated code
- allows `qt` as a synonym for `qt4`.
=> Better toolkit handling

traitsui/wx/file_editor.py
Set the default directory and filename for the dialog explicitly, rather than via the path. Fixes #409.
=> Fix Wx Simple File Editor

traitsui/editor_factory.py, traitsui/qt4/button_editor.py, traitsui/qt4/editor_factory.py, traitsui/tests/editors/test_button_editor.py, traitsui/toolkit.py
The previous changes to toolkit lookup broke lookup of editor backends in the case where the editor of a particular style is not implemented in the same module as the editor factory.
=> Fix toolkit editor lookup

examples/demo/Advanced/Table_editor_with_checkbox_column.py, traitsui/qt4/extra/checkbox_renderer.py
Fixes #439 
Additionally handles the case where the table is disabled (so that checkboxes are disabled as well)
=> Fixes issue of poorly visible checkbox in table editor

traitsui/editors/color_editor.py, traitsui/editors/font_editor.py, traitsui/editors/rgb_color_editor.py
The following warnings came up in the test suite for another project:
```
/Users/travis/.edm/envs/traits-futures-py36-pyqt/lib/python3.6/site-packages/traitsui/editors/color_editor.py:80: DeprecationWarning: invalid escape sequence \*
"""
/Users/travis/.edm/envs/traits-futures-py36-pyqt/lib/python3.6/site-packages/traitsui/editors/font_editor.py:57: DeprecationWarning: invalid escape sequence \*
"""
/Users/travis/.edm/envs/traits-futures-py36-pyqt/lib/python3.6/site-packages/traitsui/editors/rgb_color_editor.py:60: DeprecationWarning: invalid escape sequence \*
"""
```
This PR fixes those invalid escape sequences.
=> Fix a few invalid escape sequences in docstrings.

examples/demo/Advanced/Tabular_editor_with_context_menu_demo.py
Since I spent some time figuring this out, I thought I'd add a demo. This adapts the demo for the `TableEditor` with context menu to work with a `TabularEditor`
A lot of the code is duplicated between the two demos because I assume the intent is that each demo is standalone. If that is not the case, I can certainly import some of the classes from the table editor demo.
=> Add demo for tabular editor with context menu

traitsui/qt4/editor.py, traitsui/qt4/ui_panel.py, traitsui/wx/editor.py, traitsui/wx/ui_panel.py
This implements the suggestion in #472.  If a `tooltip` metadata
attribute exists for a trait, it is used as is for the tooltip,
otherwise the original behavior of using the `'Specifies' + item.desc`
is used.
=> Use tooltip metadata optionally instead of desc.

traitsui/wx/color_editor.py
Removing duplicate 'wx.' in reference to CB_READONLY
=> Removing duplicate 'wx.' in reference to CB_READONLY

.travis.yml
and create separate jobs for pyside2 on 2.7, 3.5 and 3.6, which can
be allowed to fail.
this is hopefully a temporary measure, reverted when a fix for the
pyside2 issues causing CI failure is discovered.
=> For now, allow CI failures on pyside2 jobs

traitsui/group.py, traitsui/item.py, traitsui/util.py, traitsui/view_element.py
because all version of python we support have str.find, we don't need to use the private module.
note that str_find and str_rfind are being removed from the private module in traits. see https://github.com/enthought/traits/pull/449
=> Remove use of traits._py2to3 module

etstool.py, tox-requirements.txt, traitsui/__init__.py, traitsui/extras/demo.py, traitsui/tests/test_extras.py
This fixes the docstring and source code parsing when loading demos in examples/demo/demo.py. It's never worked in Python because of an issue of bytes vs unicode what was silenced by a base `except`.
PR #484 introduced two new issues. It used `tokenize.open` on Python 3 and the regular `open` in Python 2, but they have different signatures; `tokenize.open` only takes a filename. This failed silently. And second it used `BytesIO`, where `tokenize.open` returns Unicode, which also failed silently.
This PR uses `io.open` and `StringIO` on both version.
All exceptions are still silently caught.
=> FIX: Parse description and source code in Demos

traitsui/qt4/ui_modal.py
`CloseAction` invokes `Handler._on_close()` which eventually invokes the `close()` method (without arguments) on one of these toolkit objects that provides the flavor of dialog that was requested. [Most have a default value](https://github.com/enthought/traitsui/blob/master/traitsui/qt4/ui_live.py#L205) for the return code, but the Qt implementation of the modal dialog did not. The [wx version of the modal dialog](https://github.com/enthought/traitsui/blob/master/traitsui/wx/ui_modal.py#L240) also provides the default value.
I would add a test except that it appears to be frightfully difficult to test modal dialogs in a test suite. Manual testing confirms that it does what one expects it to do, however.
=> BUG: allow argumentless call to _ModalDialog.close()

traitsui/editor.py, traitsui/undo.py
Improve undo/redo exception handling.  Don't try to undo readonly items.  Short-circuit some expensive string comparisons.
=> Fixes for Undo/Redo

examples/demo/Extras/Tree_editor_with_TreeNodeRenderer.py, traitsui/qt4/tree_editor.py
No corresponding work done for wx backend, however.
Values can be tuples or a value held in a `Color` or `RGBColor` trait.
=> Allow colors to be used as icons for qt TreeEditor nodes

traitsui/qt4/table_model.py
Drag-n-drop on table rows leads to a crash with Python 3 and PyQt5.
Fixed based on same changes applied in https://github.com/enthought/traitsui/commit/3aedd8ce69a04c81ce82d3acd06158f693003906
=> Fixed crash with Python3 (unicode vs bytes)

traitsui/item.py, traitsui/tests/test_ui.py
Fixes #514
Regardless of any underlying issues that we might want to also fix in Traits itself, this is likely a good idea.
=> BUG: Use an existing omnipresent trait for the spring dummy.

traitsui/qt4/tabular_editor.py, traitsui/tabular_adapter.py
This PR aims to fix #520 by returning None any time a `View` tries to get the properties of a non-existent column in `TabularAdapter`.
I can't spot any unintended consequences of this, but as it seems that `get_font` is the main culprit here, this change could be applied at that level instead if that makes more sense.
=> Fix crash when creating view of TabularEditor with no columns

traitsui/handler.py
=> Fix use of deprecated getargspec function on Python 3

traitsui/editors/range_editor.py
Make `RangeEditor` handle the case of code object for a `Range` trait's low or high bound, which occurs when one bound of a Range trait is a fixed value and the other is a trait name.
Fixes #6
=> Fix range trait with mixed low/high constant name

traitsui/qt4/text_editor.py
This matches the behaviour of the Wx backend and fixes a bug where passwords would not be obscured when using `style='text`' in the Qt backend.
Fixes #10.
=> Make Qt TextEditor the same as SimpleEditor for TextEditor factory.

traitsui/tests/editors/test_tree_editor.py, traitsui/tree_node.py
This fixes #494 and fixes #529 including similar issues affected updating of children and header labels.
=> Ensure the tree model gets the expected node object on updates

traitsui/editor.py, traitsui/editor_factory.py
Also refactors so that string formatting is largely handled by the factory instead of the editor unless overidden.
Fixes #267.
=> Use formatting for values in EditorWithListFactory

traitsui/editors/tabular_editor.py, traitsui/qt4/tabular_editor.py
This change allows scrolling to the column index (nearly identical to scroll_to_row). Corran, I couldnt find any tests for tabular_editor, but if I did miss it please let me know and I will add one asap for scroll_to_column. 
In the near future, I'll send you another PR to populate a selected_column property similar to selected_row, but this one would be useful for our project now.
=> Scroll to column implementation.

traitsui/tests/editors/test_tree_editor.py, traitsui/tree_node.py
Fixes #556 on 6.1 maintenance branch.
This is just #557 rebased.
=> Maintenance branch TreeNodeObject fix

traitsui/ui_editors/data_frame_editor.py
Realized that this feature was missing from the DataFrameEditor, despite mirroring (most of) the other functionality provided by the TabularEditor. Turned out to be easy, as least for the environment I'm running in. I wasn't sure if this was left out originally for backend-specific reasons, but figured I'd open a PR to start the conversation.
=> Add `scroll_to_row` functionality to DataFrameEditor

traitsui/qt4/tree_editor.py
The default implementation of `QStyledItemDelegate::sizeHint()` is exactly what Qt calls when no item delegate is set on a `QTreeView`.
=> Fix the sizeHint() default for TreeItemDelegate

traitsui/qt4/enum_editor.py
Remove use of `unicode`; also drive-by removal of bare excepts.
Fixes #571.
=> Remove unicode usage

etstool.py, traitsui/qt4/view_application.py, traitsui/tests/test_view_application.py
The event loop was being run twice under Qt when using `configure_traits` in conjunction with a modal `kind`.
Also adds fairly comprehensive tests for `view_application` which covers most use cases under Qt.
Fixes #573.
=> Fix modal view application

traitsui/qt4/helper.py, traitsui/qt4/view_application.py, traitsui/wx/custom_editor.py, traitsui/wx/helper.py, traitsui/wx/tree_editor.py, traitsui/wx/view_application.py
This PR removes the `open_fbi` function and its uses, and so also removes the (optional) dependence of the code on `etsdevtools`, which is unmaintained.
=> Remove uses of etsdevtools.

traitsui/tests/editors/test_tree_editor.py, traitsui/tree_node.py
This fixes #576.  `TreeNodeObject` instances expect to be the object that the label change is applied to.
=> Call correct object on label change for TreeNodeObject

traitsui/qt4/tree_editor.py
Make the copy action actually copy the underlying data. Fixes #578.
=> Fix tree node copy failure to copy

CHANGES.txt, setup.py
This is the release PR for the 6.1 maintenance branch.  This is a bugfix release which corrects a number of issues, including some which impacted Mayavi's UX.
=> Release 6.1.2

traitsui/qt4/ui_base.py, traitsui/qt4/ui_panel.py, traitsui/ui.py
Previously the control was having the focus set too soon, so it did not correctly register.  This changes the algorithm to remember a reference to the control which needs focus, and sets the focus when the UI is set up and ready to go.
Fixes #599
=> Set initial item focus correctly on Qt

examples/tutorials/tutor.py
Ensure docutils produces a unicode HTML string when compiling .rst.  On Python 3 it was returning a bytestring which meant most pages didn't appear.
=> Fix tutor.py in examples

.travis.yml, appveyor.yml, etstool.py, traitsui/qt4/range_editor.py
Testing on Python 3.5 is not giving us a lot more information, but is adding to CI completion time.  We expect that most users now will be on Python 3.6+ going forward.
Fixes #618.
=> Remove Python 3.5 from test matrix

traitsui/editor.py, traitsui/tests/test_editor.py
TraitsUI needs more tests of core functionality.  This is a reasonably comprehensive set of tests for the base `Editor` object.
Incidentally fixes #608.
=> Add tests for base Editor object

README.rst, docs/source/tutorials/traits_ui_scientific_app.rst
Fixed typos in links and also update the obsolete code.enthought.com to docs.enthought.com (#617)
However, after make, the webpage style looks different from the usual ones.
=> GHI 617 : Update doc links

etstool.py
This adds a "docs" subcommand to etstool.py so that you should now be able to correctly build documentation from an existing environment with the command:
```
python etstool.py docs ...
```
with the usual `--runtime`, `--version` and `--environment` options available.  So for example:
```
python etstool.py install
python etstool.py docs
```
will build documentation for the default runtime and toolkit (currently 3.6 and PyQt).
HTML documentation will be in `docs/build/html` as usual.
=> Add 'docs' command to etstool that builds HTML documentation

traitsui/qt4/tabular_editor.py
Fixes #605 
The problem was a `clicked` handler which was assuming single select.
=> Fix multi-select in a TabularEditor

traitsui/editors/table_editor.py, traitsui/qt4/table_editor.py, traitsui/qt4/table_model.py, traitsui/table_column.py, traitsui/wx/constants.py, traitsui/wx/table_editor.py
Improves situation for #594 although it is not a complete fix.  This:
- fixes most color traits on the Qt TableEditor so that they work as advertised and match behaviour of WxPython backend as closely as feasible.
- fixes the font traits on the Qt TableEditor so that they actually do something.
- fixes the row_height on the Qt TableEditor so that if gives the right default size.
It also includes some drive-by documentation fixes.
=> Fix table editor styling

traitsui/context_value.py, traitsui/tests/test_context_value.py
The `__init__` method of `ContextValue` didn't call super.  This fixes that, along with many other code improvements and tests.
For the reviewer: `ContextValue` isn't currently used by any editors, but there are hooks in the base `Editor` class to look for and use them if the editor factory has any.  It allows factories to have an API where values can come dynamically from the context without having to use a separate trait to hold the name of the source value.  It would be good to start using these.
=> Fix ContextValue __init__

traitsui/tests/ui_editors/test_data_frame_editor.py, traitsui/ui_editors/data_frame_editor.py
This PR:
- handles user errors during the setting of values in the DataFrameEditor better by logging rather than printing a traceback
- changes the logic for setting values to avoid a warning
- adds tests for setting values
Fixes #649.
=> Fix error handling for setting data in DataFrameEditor

traitsui/dock_window_theme.py, traitsui/theme.py, traitsui/wx/toolkit.py
The `Category` mechanism is deprecated in Traits.  This PR removes all remaining usages of `Category` classes from TraitsUI.  This was achieved by:
- adding the contributed traits properties from `WXTheme` to `Theme` coupled with careful delayed importing of wx-specific modules
- converting the contributed traits properties from `WxDockTheme` to use the `IImageResource` interface and hence become backend-agnostic and therefore safe to move to `DockTheme`.
Plus additional drive-by clean-up of the modules affected.
See https://github.com/enthought/traits/issues/506 for more on deprecation and removal of `Category` from Traits.
=> Remove Use of Category Classes from TraitsUI

traitsui/helper.py, traitsui/qt4/tabular_editor.py, traitsui/tests/test_helper.py
This PR does the following:
- adds a (tested!) algorithm for computing column widths for Table and Tabular editors similar to the way it specified in the documentation
- uses the algorithm in the Qt TabularEditor implementation
- automatically updates on resize of table or user modification of columns, preserving user choices.
The end result is _much_ nicer behaviour when re-sizing the columns.
Fixes #638.
=> Fix tabular editor column widths on Qt

traitsui/editor.py
The second in a series of PRs to replace #684. Requires #685 to be merged before this is merged.
A couple of small code improvements:
- add a `clean_up` trait metadata for traits that should be set to `None` during disposal.
- add a contextmanager for when the underlying trait is being modified from a change in the editor.
Plus add docstrings, remove redundant comments and other drive-by clean-up.
=> Base Editor Cleanup

traitsui/editors/array_editor.py, traitsui/editors/compound_editor.py, traitsui/editors/html_editor.py, traitsui/editors/value_editor.py, traitsui/extras/demo.py, traitsui/qt4/extra/led_editor.py, traitsui/wx/key_binding_editor.py
This PR replaces uses of the `false` and `true` convenience trait types with `Bool(False)` or `Bool(True)` as appropriate.
(Note that `Bool(False)` is technically redundant: `Bool()` or even `Bool` would be enough, but I think the explicitly-spelled out default has value for readability.)
=> Replace uses of trait types 'false' and 'true'

traitsui/extras/api.py, traitsui/extras/edit_column.py, traitsui/extras/progress_column.py
As it says.  This defers the toolkit imports until they are actually needed.
=> Better toolkit imports for ProgressColumn and EditColumn

traitsui/ui.py
Replace a small handful of uses of `DictStrAny` with `Dict(Str, Any)`.
These appear to be the only uses of the "convenience" compound trait types in Traits UI.
=> Replace uses of DictStrAny

traitsui/extras/demo.py, traitsui/extras/tutor.py
contributes to #698. 
This PR unifies the document text generation between **demo.py** and **tutor.py** by using utility functions which are thin wrappers around `docutils` to generate html from reStructuredText.. A future PR would unify the text parsing between **demo.py** and **tutor.py**.
=> Use a common utility to generate HTML from RST in demo.py and tutor.py

traitsui/extras/tutor.py
Closes #698 
- Use the parser from `demo.py` to get the docstring and code in `tutor.py`. This means we no longer support different types of sections (*description*, *hidden*, *normal*) in a py file.
This is follow on to PR #702.
=> Unify py file parsing between demo.py and tutor.py

traitsui/null/rgb_color_trait.py, traitsui/wx/rgb_color_trait.py
These were missing before the black reformat and caused SyntaxWarnings then.
=> Fix missing commas in convert_to_color functions

docs/source/traitsui_user_manual/factories_basic.rst, traitsui/editors/list_editor.py, traitsui/qt4/list_editor.py
The `scrollable` trait of the `ListEditor` allows us to hide the vertical scrollbar, and display all the items contained in the list.
Drive-by fixes -- Removes some duplicate code.
=> Add scrollable trait to the ListEditor

traitsui/extras/demo.py
Drive by cleanup for `demo.py`.
This is in preparation for adding `tutor.py` functionality to `demo.py`.
xref #710
=> Cleanup demo.py

traitsui/tree_node.py
Replace the deprecated `AdaptedTo` with the exact equivalent `Supports`.
Related: enthought/traits#723.
Also related: #674
=> Replace AdaptedTo with Supports

traitsui/qt4/table_editor.py
Fixes #717 
I don't know if we should expect PyQt to handle this redraw, so I'm not sure if this is a fix or just a workaround, but forcing the redraw appears to fix the issue.
=> TableEditor: add explicit redraw on select event

docs/source/traitsui_user_manual/factories_basic.rst
`ThisClass` is due to be either deprecated or removed in Traits 6.0, and isn't something that we want to advertise.
Ref: enthought/traits#697
=> Remove mentions of ThisClass from docs

docs/source/traitsui_user_manual/factories_basic.rst
DOC: Add dialog_style notes for FileEditor
From file_editor.py:
```
#: The style of file dialog to use when the 'Browse...' button is clicked
#: Should be one of 'open' or 'save'
dialog_style = Str("open")
```
=> DOC: Add dialog_style notes for FileEditor

examples/demo/Advanced/NumPy_array_tabular_editor_demo.py, examples/demo/Advanced/Tabular_editor_demo.py, examples/demo/Applications/Python_source_browser.py, examples/demo/Extras/Tree_editor_with_TreeNodeRenderer.py, examples/demo/Standard_Editors/ColorEditor_demo.py, examples/demo/Standard_Editors/FontEditor_demo.py, examples/demo/Standard_Editors/Popup_versions/ColorEditor_demo.py, examples/demo/Standard_Editors/Popup_versions/FontEditor_demo.py, examples/demo/Standard_Editors/Popup_versions/TupleEditor_demo.py, examples/demo/Standard_Editors/RGBColorEditor_demo.py, examples/demo/Standard_Editors/TupleEditor_demo.py, examples/tutorials/doc_examples/examples/override_editor.py, examples/tutorials/traitsui_4.0/editors/tabular_editor/sm_person_example.py, integrationtests/ui/test_ui.py, integrationtests/ui/test_ui3.py, integrationtests/ui/test_ui4.py, integrationtests/ui/test_ui5.py, traitsui/api.py, traitsui/editors/code_editor.py, traitsui/editors/scrubber_editor.py, traitsui/editors/table_editor.py, traitsui/list_str_adapter.py, traitsui/table_column.py, traitsui/tabular_adapter.py, traitsui/tests/null_backend/test_font_trait.py, traitsui/tests/test_color_column.py, traitsui/toolkit_traits.py, traitsui/ui_editors/array_view_editor.py, traitsui/ui_editors/data_frame_editor.py
This creates versions of the `Color`, `Font` and `RGBColor` trait factories inside TraitsUI.  This will allow deprecation of the UI traits from `traits.traits` as users can be instructed to use `traitsui.api` to get them rather than `traits.api` (see https://github.com/enthought/traits/issues/728).
=> Define Color, Font and RGBColor TraitFactories in TraitsUI

traitsui/editor.py, traitsui/tests/test_editor.py, traitsui/tests/test_undo.py
Fixes #672 
The method that logs changes made to an editor: `traitsui.editor.Editor.log_change` was being called when the user performs some new action on the editor and also when an undo/redo action is performed. 
This was resulting in a corrupted `history` in `traitsui/ui.py:103`
This PR checks adds a check by looking at the `updating` flag which indicates the source of the change whether on the editor itself or externally and only calls `log_change` if the change was made on the editor.  
I feel that only changes made by the user need to be logged and not external changes, can't think of a case where the user should be allowed to undo an external change.
Looking for suggestions how to test this thoroughly.
=> Fix incorrect editor Undo action

traitsui/editors/tuple_editor.py
Fixes #746 
Earlier, explicitly using `editor=TupleEditor()`, for instances of `traits.api.ValidatedTuple`, without re-specifying the `types` attribute in the editor factory, raised errors. This PR fixes this issue, by allowing the use of `editor=TupleEditor()` for all traits items that are instances of `traits.api.BaseTuple`.
=> FIX: Allow using TupleEditor for all classes derived from BaseTuple.

traitsui/qt4/table_model.py
A quick PR to log error messages prior to a crash due to bad sorting in the Qt TableModel.
This is related to #749.
=> Log exceptions during sorting

etstool.py, examples/demo/Standard_Editors/VideoEditor_demo.py, traitsui/editors/video_editor.py, traitsui/qt4/video_editor.py
This is currently not working, but the same implementation using pyqt5 instead of pyside2 does work.
It may be related to [this bug report](https://bugreports.qt.io/browse/PYSIDE-794?attachmentOrder=desc)
This is the basic idea for inserting a QAbstractVideoSurface between the input from the data source and the output QVideoWidget. This allows a user defined image transformation function to be inserted in before painting to the QVideoWidget.
I'm sure the actual implementation of this would need to be discussed and changed.
=> FEAT: QT VideoEditor pulling frames

traitsui/editors/tabular_editor.py
=> MAINT: Fix typo in tabular editor doc comment

traitsui/tests/_tools.py, traitsui/tests/editors/test_csv_editor.py, traitsui/tests/editors/test_liststr_editor_selection.py, traitsui/tests/editors/test_range_editor_spinner.py, traitsui/tests/test_color_column.py, traitsui/tests/test_toolkit.py, traitsui/tests/test_ui.py, traitsui/wx/ui_wizard.py
Fixed incorrect calls and testfailures for wxpython 4+ by replacing: 
* "control.Unbind(wx.EVT_XXX, handler)" with "control.Unbind(wx.EVT_XXX, handler=handler)" in wx.ui_wizard.py
* deprecated "wz.PyWizardPage" with "wz.WizardPage" in wx.ui_wizard.py
* missing method spin.SetValueString("4") with spin.SetValue("4") in test_range_editor_spinner.py
* missing attribute "wx._controls.TextCtrl" with "wx.TextCtrl" in test_ui.py
* "control.FindWindowByName(name)" with "control.FindWindowByName(name, control)" in:
* test/_tools.py
* test/test_csv_editor.py
* test/test_liststr_editor_selection.py
* test/test_range_editor_spinner.py
* test/test_ui.py
Other improvements include:
* Readded TestColorColumn.test_color_column to the test-suite when ETS_TOOLS="wx"
* Removed unused import of warnings in …
=> Fixed incorrect calls and testfailures for wxpython 4+

traitsui/table_filter.py, traitsui/tests/editors/test_default_override.py, traitsui/wx/helper.py
* wx.BitmapFromImage with wx.Bitmap in in traitsui.wx.helper.py
* object.get with object.trait_get in traitsui.table_filter.py
* assert_equals from nose.tools with assert_equal in tests/editors/test_default_override.py
Fixes #774
=> Replaced call to deprecated functions and classes

traitsui/wx/text_editor.py, traitsui/wx/ui_base.py, traitsui/wx/ui_live.py, traitsui/wx/ui_modal.py
Moved duplicated code in ui_live.py and ui_modal.py to BaseDialog.display_ui method in ui_base.py for the wx backend.
This is similar to what is done for the qt4 backend.
Added check to ensure the wx.TextCtrl is single line before calling "SetHint" method in
traitsui/wx/text_editor.py to avoid "wx._core.wxAssertionError", because hints can only
be set for single line text controls.
=> Refactored duplicated code

traitsui/qt4/ui_panel.py, traitsui/wx/ui_panel.py
Python 3.8 API change: https://docs.python.org/3/whatsnew/3.8.html#api-and-feature-removals
Since the documentation says the old location is deprecated in Python 3.2 I did hard replace rather than try/except.
=> Python 3.8 API change: cgi.escape -> html.escape

traitsui/context_value.py, traitsui/editors/button_editor.py, traitsui/editors/csv_list_editor.py, traitsui/editors/table_editor.py, traitsui/qt4/extra/bounds_editor.py, traitsui/table_column.py, traitsui/tabular_adapter.py, traitsui/tree_node.py, traitsui/ui_editors/data_frame_editor.py, traitsui/wx/extra/bounds_editor.py, traitsui/wx/ui_wizard.py
**Targeting release branch for 7.0**
This PR reverts the `Union` back to `Either` as `Union` was not released with Traits 6.
Not sure if we wanted this on master too. We can cherry pick in either direction.
=> Convert Union back to Either as Union which is not released in traits 6.0

.travis.yml, appveyor.yml, etstool.py, traitsui/__init__.py
Following https://github.com/enthought/pyface/pull/512, traitsui can no longer test again PySide < 2 and PyQt4. New builds on CI currently fail.
This PR removes PySide <2 and PyQt4 from the CI configuration in order to be consistent with Pyface. They are also removed from extra_requires as `pyface.qt` no longer supports these backends.
=> TST: Remove PySide < 2 and PyQt4 from CI

examples/tutorials/tutor.py
Closes #793 - removes the unnecessary `NameError` from `tutor.py`.
This PR also chooses the current directory as default if `root_dir` is omitted. The usage docstring was advertising this behaviour but it was not implemented before.
=> Remove NameError and add default root_dir to tutor.py

.travis.yml
Follows a comment on another PR: https://github.com/enthought/traitsui/pull/809#issuecomment-627398753
Sets up a separate test run for pyqt5 tests on linux that are allowed to fail.
=> Allow Travis failures with pyqt5 on linux

traitsui/tests/_tools.py, traitsui/tests/editors/test_code_editor.py, traitsui/tests/editors/test_csv_editor.py, traitsui/tests/editors/test_default_override.py, traitsui/tests/editors/test_instance_editor.py, traitsui/tests/editors/test_liststr_editor.py, traitsui/tests/editors/test_liststr_editor_selection.py, traitsui/tests/editors/test_range_editor_spinner.py, traitsui/tests/editors/test_range_editor_text.py, traitsui/tests/editors/test_table_editor.py, traitsui/tests/editors/test_tuple_editor.py, traitsui/tests/null_backend/test_font_trait.py, traitsui/tests/null_backend/test_null_toolkit.py, traitsui/tests/test_actions.py, traitsui/tests/test_controller.py, traitsui/tests/test_labels.py, traitsui/tests/test_layout.py, traitsui/tests/test_splitter_prefs_restored.py, traitsui/tests/test_ui.py, traitsui/tests/test_visible_when_layout.py, traitsui/tests/ui_editors/test_data_frame_editor.py
Addresses #613 
All unit test functions have been added to `unittest.TestCase`s. Nose and bare asserts have been replace with unittest assertion methods. All tests are now compatible to be run with unittest test runner.
=> Rewrite nose tests to use unittest

etstool.py
This PR adds an option to the `install` command in etstool.py for installing traitsui with editable mode switched on.  This allows developers to test the effect of their local clone of the repository immediately, especially when switching between branches.
This option is consistent with the one in traits.
The lack of --editable flag has bitten me quite a few times: I switched a branch and the new code was not actually run. That said, this would well have been my own working pattern being problematic. Given the flag is by default absent, I hope this is not going to interfere with other people's workflow, nor CI's.
=> Add --editable flag to etstool install command

appveyor.yml
Creates a separate appveyor job for wx tests and switches to Visual Studio 2019 image as a workaround needed with new Qt-5.12.6 egg.
=> Separate wx tests in appveyor in use VS 2019 image

traitsui/tests/_tools.py
`store_exceptions_on_all_threads` raises errors too early: The original exception hooks are not restored if a test should fail. This could result in unrelated exceptions being captured by a no-longer valid exception hook.
This PR moves the raise to happen after resetting the hooks,
Credit to @ievacerny having spotted this.
=> Raise exception after resetting exception hooks

traitsui/extras/demo.py
- fixed .css handling
- fixed loading of images and other files into HTML
- improved UI layout (fewer unused panels)
- made initial size more compatible with small screens
- better config file handling
There is still a lot to be done, but this makes the experience better.
New directory page layout:
New example page layout:
=> A variety of fixes to the Demo app

traitsui/tests/_tools.py, traitsui/tests/editors/test_enum_editor.py, traitsui/wx/ui_panel.py
Adds more tests for EnumEditor.
=> Add more tests for Enum Editor

traitsui/tests/_tools.py, traitsui/tests/editors/test_set_editor.py, traitsui/tests/test_labels.py, traitsui/wx/ui_panel.py
=> Add set editor tests

traitsui/tests/_tools.py, traitsui/tests/test_labels.py, traitsui/tests/test_layout.py
This PR adds a few simple tests to ensure that a UI can be created with various layout settings. In particular, this aims at increasing test coverage on `traitsui.wx.ui_panel` (changed from 46% to 50%...)
- Add `create_ui` context manager to `traitsui.tests._tools`.  We have seen this pattern again and again in the test suites. It is probably time to refactor this. Note that this context manager has deliberately left out the `EventLoopHelper.delete_widget` context manager. Otherwise we ~could~ would have to rely on toolkit-specific implementations of `EventLoopHelper`, which has not been implemented yet for wx.
- Drive-by changes to ensure existing tests call `ui.dispose` at the end of the test.
This was motivated by #829, e.g. the `TestOrientation.test_horizontal_layout` would fail …
=> TST: Add tests for layout and labels using any non-null toolkits

traitsui/editor_factory.py, traitsui/qt4/enum_editor.py, traitsui/qt4/image_enum_editor.py, traitsui/qt4/set_editor.py, traitsui/tests/editors/test_enum_editor.py, traitsui/tests/editors/test_image_enum_editor.py, traitsui/tests/editors/test_set_editor.py, traitsui/wx/enum_editor.py, traitsui/wx/helper.py, traitsui/wx/image_enum_editor.py, traitsui/wx/set_editor.py
Closes #782 
Closes #835 
Moves value mapping from factory to individual editors. Also fixes wx Enum and Set editor format_func issue by switching to general `enum_values_changed` version.
=> Move value mapping from factory to individual editors

examples/demo/Advanced/index.rst, examples/demo/Dynamic_Forms/__init__.py, examples/demo/Dynamic_Forms/index.rst, examples/demo/index.rst, traitsui/extras/demo.py, traitsui/extras/tests/test_demo.py
Closes #849 
Closes #804 too (that was what I initially set out to solve).
This PR:
- Changes the source file for loading a folder description to a single source `index.rst`. Updated the `examples` directory accordingly.
- Removes the hard-coded `traits_ui_demo.jpg`: The `index.rst` is responsible for providing a correct reference to whatever image it wants to show.
- Removes `DemoPath.source` which represents the source in `__init__.py`: This is not used.
- Adds tests (coverage on `demo.py` changed from 0% to 47%).
With this PR, these are the desirable fixes:
- If `__init__.py` is not found, we no longer see "Sorry, something went wrong...[traceback]" in the description. We just see an empty page.
- The directory containing tutorials no longer have to be Python package in order to …
=> Fix Demo application description if __init__.py or traits_ui_demo.jpg are not found

traitsui/qt4/list_str_model.py
There were a couple of bugs in `ListStrModel` that prevented the auto-add functionality of `ListStrEditor` from working in the Qt backend.
=> BUG: Correctly implement auto-add functionality in ListStrModel.

traitsui/qt4/tabular_model.py
may fix -- I think -- #870 
`QModelIndex.row()` returns -1 when trying to append a row below existing rows (I didn't find any indication in the Qt docs why that should be the case, but I observed it in practice using the example from #870). This causes `TabularModel.beginInsertRows()` to try and insert a row at index -1, which causes a segfault. The fix is to adjust the row location to be non-negative, i.e. to make it equal to the number of rows already in the table, [as per the documentation](https://doc.qt.io/qt-5/qabstractitemmodel.html#beginInsertRows).
I've based my investigation entirely on the example from #870, I'm not sure if there are other places in the codebase that are susceptible to this.
@rahulporuri Could you give this a spin?
=> FIX: Make sure new_row is positive

traitsui/qt4/tabular_model.py, traitsui/qt4/tests/test_tabular_model.py
This PR addresses my own comment in https://github.com/enthought/traitsui/pull/871#issuecomment-639392315
The row index should always be valid, that means nonnegative and less than the row count in the model.
See https://doc.qt.io/qt-5/qabstractitemmodel.html#checkIndex
See https://doc.qt.io/qt-5/qabstractitemmodel.html#dropMimeData for the scenario where row index will be -1.
This PR normalizes the row index for TraitsUI implementation of `QAbstractItemModel.dropMimeData`.
(It seems that the model never cares about the column index.)
=> Maint: Normalize row index in TabularModel

traitsui/tests/editors/test_tabular_editor.py, traitsui/wx/tabular_editor.py
Adds a few more tests for TabularEditor.
I wasn't trying to cover as much of the editor as in #869 so I was able to write these tests by just using model state. 
Just like #869 this also includes a minor bug fix in wx version of `TabularEditor` because it was easier to fix it than to open an issue.
The bug: in `_multi_selected_items_changed` instead of `self.value` the method was trying to use `self.values` which doesn't exist.
=> Add more TabularEditor tests

traitsui/tests/editors/test_liststr_editor.py, traitsui/tests/editors/test_liststr_editor_selection.py, traitsui/wx/list_str_editor.py
Adds more tests for ListStrEditor.
Also includes a minor bug fix in wx version of `ListStrEditor` because it was easier to fix it than to open an issue.
The bug: in `_multi_selected_items_changed` instead of `self.value` the method was trying to use `self.values` which doesn't exist.
I would also like to rename the test files `test_liststr_editor.py -> test_liststr_adapter.py` and `test_liststr_editor_selection.py -> test_liststr_editor.py` so that it's easier to find relevant tests. If nobody has any objections, I will do it just before merging to keep a nicer diff in the meantime.
=> Add more ListStrEditor tests

traitsui/qt4/boolean_editor.py, traitsui/tests/editors/test_boolean_editor.py
Part of #431 
This PR implements the missing `disconnect` for Qt BooleanEditor.
=> Implement dispose for Qt BooleanEditor

traitsui/qt4/list_str_editor.py, traitsui/qt4/tabular_editor.py, traitsui/tests/editors/test_liststr_editor_selection.py, traitsui/tests/editors/test_tabular_editor.py, traitsui/wx/list_str_editor.py, traitsui/wx/tabular_editor.py
Closes #791 
`TraitListEvent` in `ListStrEditor` and `TabularEditor` now gets its arguments by keyword.
The tests for this PR are in #869 and #874
=> Fix bad TraitListEvent in ListStr and Tabular Editors

traitsui/qt4/drop_editor.py, traitsui/tests/editors/test_drop_editor.py
Part of #431 
The PR adds open-and-close tests for DropEditor which are already passing without the new dispose method.
A `dispose` method is still added to ensure correctness: DropEditor uses the simple `TextEditor`'s `init` only if `readonly` is false. The new `dispose` to ensure it does not call the TextEditor dispose when the TextEditor `init` is not actually used. See #884.
(Orthogonal note 1: I tried but I still could not figure out how DropEditor is meant to be used.)
(Orthogonal note 2: The `_DropEventFilter` in this module is used by the Qt InstanceEditor.)
=> Implement dispose for DropEditor (Qt)

traitsui/tests/editors/test_datetime_editor.py
The `store_exceptions_on_all_threads` does a few things, one of those is to capture exceptions 
from trait change and then re-raise. 
This is needed if an error occurs in the change handlers for `minimum_datetime` and `maximum_datetime` on the DatetimeEditor.
For example if the `if self.control is None` was removed from the change handler, we get errors logged on the console but the tests still pass. Wrapping the test with the context manager make them fail in that scenario.
Motivated by #431 which also concerns the hooking and unhooking of trait change handlers. 
Solves part of #876
=> Wrap DatetimeEditor tests with store_exceptions_on_all_threads

traitsui/tests/editors/test_directory_editor.py
This PR adds tests for Qt's `DirectoryEditor` to ensure that changes in `FileEditor` from #889 do not adversely affect the directory editor. The tests only cover init and dispose as this is motivated by #431.
Again, skipping wx for now to avoid creating more test interactions in the mean time until #752 is fixed.
=> Add tests for DirectoryEditor (Qt)

traitsui/qt4/datetime_editor.py
Part of #431
This PR adds a dispose method to disconnect signals in DatetimeEditor. DatetimeEditor is only implemented by Qt and its init-dispose is already covered by tests.
Note that there are two `on_trait_change` handlers attached for the editor's traits and they are never removed. It is not necessary to remove those change handlers in `dispose` because the change handler checks `if self.control is None` to avoid accessing GUI components that have been disposed. I will add these tests separately as they pass independently of this PR.
=> Add dispose method in DatetimeEditor (Qt)

traitsui/qt4/date_editor.py, traitsui/qt4/styled_date_editor.py, traitsui/tests/editors/test_date_editor.py, traitsui/tests/editors/test_styled_date_editor.py
Part of #431 
This PR implements the `dispose` method for Qt DateEditor.
The custom DateEditor is also subclassed by `DateRangeEditor` and `StyledDateEditor`. I checked `DateRangeEditor` does not need changes because it basically just calls `super().init(parent)` and so it makes sense to carry on using the inherited `dispose`.
`StyledDateEditor.init` has much in common with the base but it did not call the base class `init`. The option is (1) keep the `init` as is but add a `dispose` and then call `traitsui.editor.Editor.dispose` there, or (2) reuse the base class `init` so that it makes sense to inherit the base class `dispose` too. I opt-ed for the second option.
Tests for `DateRangeEditor` already cover init and dispose. New tests are added for `StyledDateEditor` to confirm the …
=> Implement dispose for DateEditor (Qt)

traitsui/qt4/range_editor.py, traitsui/tests/editors/test_range_editor.py, traitsui/wx/range_editor.py
Closes #898
`SimpleEnumEditor` and `CustomEnumEditor` in `range_editor.py` (both qt and wx) are not subclasses of `Editor` themselves. Instead they are functions that return an `EnumEditor` via `traitsui.editors.enum_editor.ToolkitEditorFactory`.
The PR modifies the signatures of these functions to match what `EditorFactory` expects (adding `format_func`, `format_str` and `invalid_trait_name`). These additional arguments aren't passed to the actual editor to match the behaviour as it was before the bug.
=> Fix unexpected format_func in RangeEditor bug

traitsui/qt4/html_editor.py, traitsui/tests/editors/test_html_editor.py
Part of #431 
This PR implements the `dispose` method of `HTMLEditor` (Qt).
Confirmed that no other editors in traitsui subclass `HTMLEditor` (Qt)
=> Implement dispose for HTMLEditor (Qt)

traitsui/qt4/check_list_editor.py, traitsui/qt4/editor.py, traitsui/tests/editors/test_check_list_editor.py
This PR presents an alternative approach to https://github.com/enthought/traitsui/pull/881
~One of these two can merge, but not both :)~.  I have unilaterally closed #881 in favour of this.
~Like in #881, this is also done here:~
- ~`CustomEditor` no longer subclasses `SimpleEditor` in order to reuse the `list_updated` method. This relationship makes it difficult to implement `dispose` as the two editors need to perform different cleanup. The `list_updated` logic is now refactored out to a base class.  Then it is easier to see what needs to be disconnected and cleaned up in each of these concrete subclasses.~ (Edited: This is removed)
Instead of adding `dispose_child` to the editor base class's `clear_layout`, the approach in this PR keeps lists of connected signals.
In particular, …
=> Alternative approach to implement dispose for Qt CheckListEditor

traitsui/qt4/tabular_editor.py, traitsui/tests/editors/test_tabular_editor.py
Many thanks to @FedeMiorelli tracking down the cause to issue #894.  The issue is indeed resolved by resetting the user widths.
This PR proposes resetting the user-defined widths in a slightly different place.
This PR actually does two things:
(1) Invalidating the view's `_user_widths` cache when the adapter columns is changed.
(2) Workaround an error that occurs when the UI is disposed. I believe the error is caused by header resize signal still being connected after the factory is removed from the editor. (See #431). The second test fails with this error if the `if self._editor.factory is not None` check is removed:
```
File "/Users/kchoi/Work/ETS/traitsui/traitsui/tests/editors/test_tabular_editor.py", line 402, in …
```
=> Alternative fix to TabularAdapter crashes when column number reduces

traitsui/qt4/button_editor.py, traitsui/tests/editors/test_button_editor.py
Part of #431
This PR adds missing dispose logic for Qt's ButtonEditor.
=> Reverse on_trait_change hook in Qt ButtonEditor's dispose

traitsui/qt4/text_editor.py, traitsui/tests/editors/test_text_editor.py
Part of #431 
This PR implements the missing `dispose` method in Qt TextEditor.
In the process of testing the dispose method, I discovered a bug:
```
class Foo(HasTraits):
value = Float()
view = View(
Item('value', editor=TextEditor(auto_set=False), style="custom"),
)
Foo().configure_traits(view=view)
```
Launching the GUI fails with:
```
...
File "/Users/kchoi/Work/ETS/traitsui/traitsui/qt4/ui_panel.py", line 874, in _add_items
editor.prepare(inner)
File "/Users/kchoi/Work/ETS/traitsui/traitsui/editor.py", line 264, in prepare
self.init(parent)
File "/Users/kchoi/Work/ETS/traitsui/traitsui/qt4/text_editor.py", line 84, in init
control.editingFinished.connect(self.update_object)
AttributeError: 'QTextEdit' object has no attribute 'editingFinished'
```
In order to test the new dispose for …
=> Implement dispose for Qt TextEditor 

.travis.yml, etstool.py, integrationtests/test_all_examples.py
This PR adds a test case to ensure demo examples can be run to the extent that a GUI can be opened and then closed. Unfortunately some of them have to be skipped, see inlined reasons.
Since `examples` is not a package (though included in source distribution), the tests are added to `integrationtests` folder, which isn't distributed.
A few dependencies are added for testing some of the examples. If that's too much, then we can only skip those examples in the tests (or evaluate if those examples should be removed?).
One downside is that these tests are rather noisy on wx due to DeprecationWarnings. These warnings should be fixed, see https://github.com/enthought/traitsui/issues/579
See #623 for behavioural issues on the demo examples.
=> TST: Test demo examples can be run

docs/source/traitsui_user_manual/adapters.rst, docs/source/traitsui_user_manual/factories_advanced_extra.rst
Closes #830 
Adds links from TabularEditor and TreeEditor documentation to more detailed TabularAdapter and TreeNode documentation.
=> Add links from TabularEditor and TreeEditor to adapter docs

etstool.py
Closes #920
> #853 added test dependencies which install the release version of pyface from PyPI. While that would have been our goal in the future, we do need pyface master for CI. When CI script gets to pip install -r ci-src-requirements.txt --no-dependencies for installing pyface master, pyface is already there and master is not installed. Then when the test tries to import traitsui.wx.table_editor, it runs into an error
This PR fixes this by making sure pyface master is always installed
=> Reinstate pyface master for CI

traitsui/tests/_tools.py
While Linux/OSX typically have decent timing precision (in the order of microseconds), Windows has a worse [temporal resolution](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/high-resolution-timers).
This PR increases the precision tolerance in `process_cascade_events` to account for the larger precision error on Windows. Again false positive is okay as long as the next redundant run returns fast enough to exit the loop, so it is fine for Linux/OSX to receive the same treatment.
=> Increase precision offset for process_cascade_events and Windows

traitsui/qt4/tests/test_ui_panel.py, traitsui/tests/editors/test_button_editor.py, traitsui/tests/editors/test_check_list_editor.py, traitsui/tests/editors/test_csv_editor.py, traitsui/tests/editors/test_date_editor.py, traitsui/tests/editors/test_date_range_editor.py, traitsui/tests/editors/test_datetime_editor.py, traitsui/tests/editors/test_enum_editor.py, traitsui/tests/editors/test_image_enum_editor.py, traitsui/tests/editors/test_instance_editor.py, traitsui/tests/editors/test_liststr_editor_selection.py, traitsui/tests/editors/test_range_editor_spinner.py, traitsui/tests/editors/test_range_editor_text.py, traitsui/tests/editors/test_set_editor.py, traitsui/tests/editors/test_table_editor.py, traitsui/tests/editors/test_tabular_editor.py, traitsui/tests/editors/test_text_editor.py, traitsui/tests/editors/test_tree_editor.py, traitsui/tests/editors/test_tuple_editor.py, traitsui/tests/test_color_column.py, traitsui/tests/test_labels.py, traitsui/tests/ui_editors/test_data_frame_editor.py
This is an ongoing efforts to clean up UI and GUI event queue in order to resolve test interactions.
This PR does the following:
(1) Search for `edit_traits` in tests and convert them to use `create_ui` so that the tests receive the same dispose logic. One exception is `test_editor`, which is the logic `create_ui` depends on. Using `create_ui` will be a bit circular.
(2) Use `process_cascade_events` to ensure cascade events are processed in Qt. In many places where there are no cascade events, `GUI.process_events()` would be enough, but really the tests often mean to process everything before doing the next things, not just the current snapshots of events.
(3) Drive-by: Avoid holding references to `Editor.control` in tests
Closes #851
=> TST: Update tests to use the same dispose and event queue process logic

examples/demo/Standard_Editors/BooleanEditor_demo.py, examples/demo/Standard_Editors/ButtonEditor_demo.py, examples/demo/Standard_Editors/CSVListEditor_demo.py, examples/demo/Standard_Editors/CheckListEditor_demo.py, examples/demo/Standard_Editors/CheckListEditor_simple_demo.py, examples/demo/Standard_Editors/CodeEditor_demo.py, examples/demo/Standard_Editors/ColorEditor_demo.py, examples/demo/Standard_Editors/CompoundEditor_demo.py, examples/demo/Standard_Editors/DataFrameEditor_demo.py, examples/demo/Standard_Editors/DatetimeEditor_demo.py, examples/demo/Standard_Editors/DirectoryEditor_demo.py, examples/demo/Standard_Editors/FileEditor_demo.py, examples/demo/Standard_Editors/FontEditor_demo.py, examples/demo/Standard_Editors/HTMLEditor_demo.py, examples/demo/Standard_Editors/ImageEnumEditor_demo.py, examples/demo/Standard_Editors/InstanceEditor_demo.py, examples/demo/Standard_Editors/ListEditor_demo.py, examples/demo/Standard_Editors/Popup_versions/BooleanEditor_demo.py, examples/demo/Standard_Editors/Popup_versions/ButtonEditor_demo.py, examples/demo/Standard_Editors/RGBColorEditor_demo.py, examples/demo/Standard_Editors/SetEditor_demo.py, examples/demo/Standard_Editors/TableEditor_demo.py, examples/demo/Standard_Editors/TitleEditor_demo.py, examples/demo/Standard_Editors/TreeEditor_demo.py, examples/demo/Standard_Editors/TupleEditor_demo.py
Addresses #866 
These are mostly flake8, formatting and other minor stylistic fixes for demos in `Standard_Editors`. 
Some of the demos are broken. ~Warnings will be added soon, after relevant issues are opened.~ Warning are added to demos that are broken in some way. Issue references also added as comments.
More important changes are pointed out with in-code review comments.
=> Minor stylistic changes to demos in Standard_Editors

traitsui/tests/test__tools.py
This PR updates a test (the one that fails occasionally in #951) by making sure the QObject checks the event type it is processing.
When looking into #951, this is the only one thing that jumps out at me. I am not sure what caused the issue as I wasn't able to reproduce locally. I also don't think the change in this PR will be a fix for the issue. Still it is good to make sure the object isn't treating any spurious events as the custom one used in the test.
=> TST: Make DummyObject.event process only the event it posts

etstool.py
The master cron job is failing (with error) on CI because of a missing variable in the install script, and `python etstool.py install --source` fails.
This variable was added in #914 but a merge (conflict?) with master resulted in it being erroneously removed.
This PR adds the variable back so that `python etstool.py install --source` does not fail.
=> Fix install script for CI cron job

traitsui/tests/_tools.py
`UI.dispose` is not atomic, this PR ensures even if it fails, tests still process whatever events left over.
I don't think there are test-related issues caused by this yet, but I think it is correct to always process the events after `dispose` (even if it fails), otherwise errors from dispose could cause test interactions.
=> Maint: Ensure events are processed even if dispose fails half-way

examples/demo/Standard_Editors/File_Dialog/File_Open.py, examples/demo/Standard_Editors/File_Dialog/File_Open_with_Custom_Extension.py, examples/demo/Standard_Editors/File_Dialog/File_Open_with_FileInfo_Extension.py, examples/demo/Standard_Editors/File_Dialog/File_Open_with_ImageInfo_Extension.py, examples/demo/Standard_Editors/File_Dialog/File_Open_with_Multiple_Extensions.py, examples/demo/Standard_Editors/File_Dialog/File_Open_with_TextInfo_Extension.py
Addresses #866
This PR mainly does stylistic and flake8 fixes to demos in `Standard_Editors/File_Dialog`. It also adds warning about all these demos being broken (see issue #953)
A few more significant changes:
- replace "Traits" references to "TraitsUI"
- replace `io.open` with Python built-in `open` and use it as a context manager
- remove the use of `commatize` function in demo code because it raises errors. Use integer string formatting instead
=> Maintenance of Standard_Editors/File_Dialog demos

examples/demo/Advanced/Date_editor_demo.py, examples/demo/Advanced/Date_range_editor_demo.py, examples/demo/Advanced/Time_editor_demo.py
Addresses #866
These are mostly flake8, formatting and other minor stylistic fixes for time and date editor demos in `demos/Advanced`.
Some of the demos are broken. Warning are added to demos that are broken in some way. Issue references also added as comments.
More important changes:
- Updated docstrings
- Added explanation about options ignored by qt
- Add protection against launching `DateRangeEditor` demo with wx backend because the editor isn't implemented
=> Maintenance of date and time editor demos in demos/Advanced

examples/demo/Advanced/Auto_update_TabularEditor_demo.py, examples/demo/Advanced/Multi_select_string_list.py, examples/demo/Advanced/NumPy_array_tabular_editor_demo.py, examples/demo/Advanced/String_list_ui_editor.py, examples/demo/Advanced/Tabular_editor_demo.py, examples/demo/Advanced/Tabular_editor_with_context_menu_demo.py
Addresses #866
These are mostly flake8, formatting and other minor stylistic fixes for TabularEditor demos in `demos/Advanced`.
Some of the demos are broken. Warning are added to demos that are broken in some way. Issue references also added as comments.
More important changes:
- Numpy demo had a TabularEditor `readonly` style, but it doesn't disable the editing. Added necessary editor options to disable editing.
- Removed mention of an old closed issue and restored code that was commented out because of it.
- Some minor fixes (e.g. `auto_resize=True`) to improve the appearance of the demos
- Remove the use of `lambda` in `Tabular_editor_demo.py`
=> Maintenance of TabularEditor demos in demos/Advanced

examples/demo/Advanced/List_editors_demo.py, examples/demo/Advanced/Property_List_demo.py, examples/demo/Advanced/Table_editor_with_checkbox_column.py, examples/demo/Advanced/Table_editor_with_context_menu_demo.py, examples/demo/Advanced/Table_editor_with_progress_column.py
Addresses #866
These are mostly flake8, formatting and other minor stylistic fixes for `TableEditor` demos in `demos/Advanced`. There are two more `TableEditor` demos that are not dealt with in this PR: `Table_editor_with_live_search_and_cell_editor.py` and `Auto_editable_readonly_table_cells.py` .
`List_editors_demo.py` is broken because of differences between `TableEditor` implementations.
More important changes:
- Added `sortable=False` in demos where this feature isn't important to avoid `TableEditor` implementation differences
- Added `show_toolbar=True` to `List_editors_demo.py` because a lot of the functionality added there wasn't accessible. Now it is accessible but the differences between implementation are more obvious.
- Simplified an expression in demo with checkboxes so that …
=> Maintenance of TableEditor demos in demos/Advanced

traitsui/wx/tabular_editor.py
On the CI build for wx (currently allow failures), there are several test errors like this (they started occurring as we make more tests to dispose the UI at the end of the tests):
```
======================================================================
ERROR: test_data_frame_editor_columns (traitsui.tests.ui_editors.test_data_frame_editor.TestDataFrameEditor)
File "/Users/travis/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/traitsui/tests/ui_editors/test_data_frame_editor.py", line 368, in test_data_frame_editor_columns
pass
File "/Users/travis/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/contextlib.py", line 88, in __exit__
next(self.gen)
File …
```
=> Fix Wx test errors due to comparing None with int

traitsui/tests/_tools.py
This PR expands the docstring of `process_cascade_events` to refer to #951
I am unable to expand more on that because at this stage I am still not sure what exactly caused the test failure, and what the implications are for when this function is used in other context.
(Note the function is currently just a test utility function private to traitsui)
=> Maint: Expand docstring of process_cascade_events

traitsui/qt4/image_enum_editor.py, traitsui/tests/editors/test_image_enum_editor.py, traitsui/tests/editors/test_liststr_editor_selection.py, traitsui/tests/editors/test_tabular_editor.py
With Qt4 and Mac OSX, I can reliably reproduce the error seen in https://github.com/enthought/traitsui/issues/854#issuecomment-636715072
Closes #854
This PR fixes the issue by unsetting the item model held by the QComboBox in the ImageEnumEditor.
The issue observed here is that after the test run and the editor is disposed, the `QComboBox` is still kept alive (ideally it should have garbage collected, but that's a separate issue). Consequently its model (an instance of `QAbstractItemModel`) is still responding to events, e.g. its `rowCount` could be called. Calling these methods after the editor is disposed results in attribute error, because the editor factory is no longer available.
As for the larger issue with cleaning widgets, see #431
=> Fix image enum test due to combo box's model reacting to events post dispose

appveyor.yml
Targeting `maint/7.0` so that we can run the test suites on Appveyor.
In preparation for 7.0.1 release.
=> Update appveyor setting to include maint/7.0 branch

traitsui/tests/_tools.py, traitsui/tests/test__tools.py
After some digging, the issue in #951 was due to:
- `QtCore.QEventLoop.processEvents` may misreport whether it has processed some pending events on certain platforms, build conditions and Qt version.
- The ability to process cascade events relies on looping over the result of `QEventLoop.processEvents`: If it returns true, run it again. However, when it erroneously returns false, the loop can break too early, leaving cascaded events unprocessed.
This has been observed on Qt5 + Appveyor, and Qt4 + OSX.
This PR:
- Expand docstring of `process_cascade_events` to note the situation. At worst, it is as good as `processEvents` which process only the current snapshots of events. At best, it can achieve what we often wanted in tests.
- Skip the tests for the problematic Qt version and platform …
=> Expand caution notes and skip test for process_cascade_events on certain conditions

.travis.yml, appveyor.yml, etstool.py, traitsui/__init__.py
Closes #821 
This PR reverts #815 and #818 but not literally, because `pyside` does not support Python 3 so that does not need to be brought back.
With that `traitsui-test-3.6-pyqt` development environment refers to the PyQt4 environment again! (It is PyQt5 on master currently).
=> Bring Qt4 back to CI

traitsui/__init__.py, traitsui/editor.py, traitsui/editor_factory.py, traitsui/editors/array_editor.py, traitsui/editors/csv_list_editor.py, traitsui/qt4/ui_panel.py, traitsui/tests/editors/test_text_editor.py, traitsui/tests/test_editor.py, traitsui/tests/test_ui.py, traitsui/wx/ui_panel.py
Closes #983 
Revert #859
The issue in #790 is fixed by upgrading to traits 6.1 (see [PR in traits](https://github.com/enthought/traits/pull/1032)).  Attempt to fix the issue independently causes breakages as shown in #983. So this PR reverts those changes.  Users who would like #790 being fixed will have to upgrade traits to >= 6.1 instead.
It might be easier to review this commit-by-commit. This PR:
(1) Add a regression test for #790, because this PR will revert the PR that aims at fixing the issue independently of traits. This test passes on master even with traits 6.0
(2) Add failing tests for #983
(3) Revert #859. This allows the tests added for #983 to pass. The test added for #790 still passes if traits version is 6.1, but fails if traits version is less than 6.1
(4) Skip the test …
=> Fix invalid value in Item not being used

examples/demo/Advanced/Table_editor_with_live_search_and_cell_editor.py
Part of #866.
The `examples/demo/Advanced/Table_editor_with_live_search_and_cell_editor.py` example takes a long time to start up if one happens to run it from a directory that contains lots of files (e.g. a directory that contains many python virtual environment).
This PR changes the default folder to the directory where the example is, which is a much smaller folder. Now starting up the example is reasonably fast wherever you run it from.
=> Demo: Use a smaller directory as the default root for an example script

CHANGES.txt, traitsui/__init__.py, traitsui/editor.py, traitsui/editor_factory.py, traitsui/editors/array_editor.py, traitsui/editors/csv_list_editor.py, traitsui/qt4/ui_panel.py, traitsui/tests/editors/test_text_editor.py, traitsui/tests/test_editor.py, traitsui/tests/test_ui.py, traitsui/wx/ui_panel.py
This PR:
- backports bug fix from #985
- updates the changelog accordingly for 7.0.1
Note that this is targeting the `maint/7.0` branch.
=> Backport bug fix to 7.0.1

traitsui/qt4/tabular_editor.py
Reverts enthought/traitsui#989 since a better fix was made in #897 . My apologies again.
cc @kitchoi @corranwebster
=> Revert "Avoid Qt5 crash from out-of-sync user_widths."

traitsui/tests/test__tools.py
For #951, it was not clear whether it was the test itself being problematic, or whether the test is doing the right thing but the test objective fails.
This PR expands the failure message for the tests on `process_cascade_events`, in order to provide more information for diagnosing the problem, when it does fail.
=> TST: Expand test to provide more information for diagnosing

traitsui/qt4/list_str_editor.py
Related to #431 and resolves part of #986.
The error seen in #986 is revealed by unskipping the test in https://github.com/enthought/traitsui/pull/974.
As it turns out, events are still received by the `ListStrModel` used in the view of `ListStrEditor` after the UI is disposed.
The issue occurs most frequently in Qt4.
This PR attempts to resolve this by doing the same thing in #974: Unset the item model from the view in the editor dispose.
Since the error is sporadic, I might need to rebuild this a few time to verify the issue is fixed. 
This does not completely _fix_ #986 because there are other instances of `QAbstractItemModel` which we are not unsetting.
=> Unset ListStrModel from the ListStrEditor view upon dispose

etstool.py
Applying a quick fix for [Command names with underscores must be invoked with dashes instead when upgrading from 6.7 to 7.0](https://github.com/pallets/click/issues/1123)
This will make the documentation command consistent: ```python etstools.py test_all```
=> FIX: Enforce underscore for click command

traitsui/qt4/range_editor.py
Fixes this error I get on PyQt 5.15:
```
File "/home/larsoner/python/traitsui/traitsui/qt4/range_editor.py", line 144, in init
sh.setWidth(sh.width() / 2)
TypeError: setWidth(self, int): argument 1 has unexpected type 'float'
```
=> FIX: Fix for PyQt 5.15 int

traitsui/qt4/extra/bounds_editor.py
`setWidth` expects an integer rather than a float.
See also #999.
=> Fix a true division to be integer division

traitsui/tests/test__tools.py
We have now seen more information for the test failure on Appveyor (see #951). For it is either not possible or very costly to try to fix/workaround this specific Qt issue, to avoid slowing down development, this PR skips the relevant test for Qt <= 5.12.6 and Appveyor.
The condition for the skip is set to be very specific so that we can detect whether the issue exists with newer versions of Qt and/or future images of Appveyor and/or other Windows machines. If we need to expand the range and include Windows more generally, we can do that with the relevant incident being tracked.
=> Skip test for process_cascade_events with Qt <= 5.12.6 and Appveyor

ets-demo/etsdemo/app.py, ets-demo/etsdemo/tests/test_app.py
This PR fixes errors from the demo application if one tries to press the previous or the next button when the selected node is not defined.
Before the fix, these two buttons are erroneously enabled (there is a try-except around the evaluation of `enabled_when`):
If one tries to press any of the previous and next buttons, the app would crash because `selected_node` is None.
After the fix, the buttons are correctly disabled:
The "Parent" action already has this `if self.selected_node is None` guard, but the previous and next buttons don't. This PR adds the same guards and add the tests that fail before the fix.
A similar test is added for the "Parent" action.
I decided not to assert in the tests if the buttons are by default disabled, because they can be enabled in general, e.g. if the …
=> Fix demo application's previous and next buttons if no items are selected

examples/demo
The symbolic link to the new location of the demo files should be relative to where the symbolic link file is.
This PR fixes this. Now GitHub can recognize the symbolic link being a directory (though it still won't bring you directly to the actual folder).
=> Fix symlink path for examples/demo

ets-demo/setup.py
This is not a fix but a workaround for #1032
Crashing on Windows is bad enough we should avoid that. The one downside is that if one tries to run this application from a desktop shortcut on Windows, it will result in a command line shell being open as well (which is a bit ugly), but that is better than crashing.
=> Switch to console_scripts to workaround crash on Windows

docs/source/tutorials/traits_ui_scientific_app.rst
The date in this section is created with the release: https://docs.enthought.com/traitsui/tutorials/traits_ui_scientific_app.html
This sends a misleading message that the article was written as recently as the last release was made, which isn't true. Since it is at best misleading, this PR removes the date. We can add the original date back later or a last update date later if there is value in doing so.
=> Doc: Remove dynamic date tied to the release date

ets-demo/etsdemo/info.py
This PR removes the desktop shortcut defined in the EAM metadata.
Currently installing an application bundle via the EDM GUI or the command line does not have the option for skipping the shortcuts. For now, we will remove the desktop shortcut until the installer provides an option to skip it.
Closes #1043
=> Remove desktop shortcut for etsdemo EAM application

ets-demo/etsdemo/app.py
Closes #1028
This PR sets the application main window icon.
I decided not to use Python logo to avoid trademark issue, see https://github.com/enthought/traitsui/issues/1028#issuecomment-661980408
=> Set an icon for the demo app main window

traitsui/qt4/file_editor.py, traitsui/qt4/list_str_editor.py, traitsui/qt4/table_editor.py, traitsui/qt4/tabular_editor.py
With Qt5, running the tests for the editors result in a lot of warnings like this:
```
$ python -m unittest traitsui.tests.editors
.....QItemSelectionModel: Selecting when no model has been set will result in a no-op.
QItemSelectionModel: Selecting when no model has been set will result in a no-op.
QItemSelectionModel: Selecting when no model has been set will result in a no-op.
...
```
This PR resolves these warnings by reseting the QAbstractItemModel used in various editors's `dispose`.
Related to #431 
I have not fully understood the warnings. But it looks like the right to do: If we are disposing the widget, we should be invalidating any data or structure changes have been posted to the model. 
This also resolves some sporadic errors from the test suite I get when I add some new tests …
=> TST: Resolve warnings from QItemSelectionModel with Qt5

README.rst, setup.py
Added an explicit separator before the Running the Test Suite section.
So now, what is rendered on Pypi will simply be the first part of the readme.  Anything found after the seperator will appear on GitHub but not Pypi (content relevant to contributors and less so users such as how to run the test suite)
fixes #1017
=> Separating Pypi long description and readme 

traitsui/key_bindings.py
This fixes a deprecation warning visible from running the tests on the examples.
=> Fix deprecation warning about trait_get

traitsui/tests/test_ui_traits.py
This PR adds unit tests for the `ui_traits` module. 
Trait types and objects defined in this module are probably indirectly tested in places with more dependencies (e.g. integration tests). This PR adds unit tests that have very minimal dependency, making it easier to maintain.
=> TST: Add tests for ui_traits module

ets-demo/etsdemo/app.py
When a demo is selected, it is convenient to have the demo tab be the default tab shown so that a user can immediately see what the demo does, instead of simply seeing the output.
=> in etsdemo, make demo tab default tab shown as opposed to output

traitsui/tests/test_ui_panel.py
[Targeting #1067]
This PR adds a test that fails on wx and master, in an effort to reproduce #1066
The test failure was the following:
```
File "/Users/kchoi/Work/ETS/traitsui/traitsui/tests/test_ui_panel.py", line 45, in test_grouped_layout_with_springy
with create_ui(obj1, dict(view=view)):
File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/contextlib.py", line 81, in __enter__
return next(self.gen)
File "/Users/kchoi/Work/ETS/traitsui/traitsui/tests/_tools.py", line 177, in create_ui
ui = object.edit_traits(**ui_kwargs)
File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/traits/has_traits.py", line 1678, in edit_traits
args,
File "/Users/kchoi/Work/ETS/traitsui/traitsui/view.py", line 462, in ui
ui.ui(parent, …
```
=> Add test for nested group and spring in UI 

traitsui/wx/scrubber_editor.py, traitsui/wx/ui_panel.py
This gets rid of the 
```
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL))" failed at /Users/robind/projects/bb2/dist-osx-py36/build/ext/wxWidgets/src/common/sizer.cpp(2114) in DoInsert(): Vertical alignment flags are ignored with wxEXPAND
```
error mentioned in issue #1066  (another example of #828).  However, after this fix is completed, the issue of a segfault on mouseover as mentioned in #434 still occurs.
=> remove the ALIGN_CENTRE_VERTICAL FLAG to avoid error

ets-demo/etsdemo/app.py, ets-demo/etsdemo/tests/test_app.py
Closes #1029
(This kind of mitigate #1030 if TraitsUI demo happens to be first one: The demo has a big welcome image for setting the size hint such that the split ratio looks better, but that should not be relied on.)
=> Set default node in etsdemo if there is data available

traitsui/wx/table_editor.py
=> removing Horizontal alignment flag that is ignored with wxEXPAND

traitsui/examples/demo/Extras/animated_GIF.py, traitsui/tests/editors/test_animatedGIF_editor.py, traitsui/tests/test_animatedGIF_editor.py, traitsui/wx/animated_gif_editor.py
fixes #1071 
wx.adv.GenericAnimationCtrl is a subclass of wx.adv.AnimationCtrl but it has the SetUseWindowBackgroundColour() method.  I believe this was the intended class from the beginning - after the change the demo seems to run fine.
=> replace AnimationCtrl object with GenericAnimationCtrl in animated_gif_editor.py

traitsui/tests/editors/test_animatedGIF_editor.py
This PR switches `skip_if_not_wx` to `requires_toolkit` with wx.
The test was added in a PR when the PR introducing `requires_toolkit` was pending.
I believe this is the last occurrence of `skip_if_not_`. After confirming no other PRs are using it, we can remove the placeholder.
=> Maint: Specify wx being required by a test

traitsui/tests/_tools.py
This PR removes the test utility functions / decorators that are now replaced by `is_qt`, `is_wx`, `is_null` and `requires_toolkit`.
No more pending PRs (as far as I can see) are introducing new dependencies on them.
=> Maint: Remove internal test utility functions

traitsui/tests/_tools.py, traitsui/tests/test__tools.py
This PR improves the context manager we used for capturing exceptions that occur in the GUI event loop as a test is run.
- Change `print` to logging
- Instead of re-raising the first exception as is, serialize all the exceptions and re-raise RuntimeError instead. 
- It is problematic to re-raise the first one regardless of its type, e.g. it could be a `SystemExit` or it could be a `StopIteration` (see [PEP 479](https://www.python.org/dev/peps/pep-0479/)). When we re-raise, we meant to make the test error, rather than propagating the intended side effect of the captured exception.
- If more than one exception occurs, we get to see all of them.
=> Maint: Improve how we capture and re-raise errors in GUI tests

traitsui/undo.py
fixes #1098 
Since we no longer support python 2 I believe this shouldn't be a problem
=> using collections.abc instead of collections

.travis.yml, etstool.py
Closes #1054
This PR adds a job for the Travis build to test against Traits 6.0.
I did not multiply the entire matrix with Traits 6.0 because I did not find this necessary. Given most of the GUI tests are skipped on Null or Wx backend, choosing one of the Qt backend exercise most logic that would depend on traits 6.1. Then the choice of PyQt5 over PySide2 is a bit arbitrary.
=> Add a CI job for testing against traits 6.0

ets-demo/CHANGES.txt
Preparation for #1031 
This PR adds the changelog file for the release of `etsdemo`.
Since this is the first release, there are technically no "changes". A laundry list of PRs for the migration out of traitsui and preparation for entry points are not particularly useful. I added some description and notes on the intended migration from `traitsui.extras.demo`.  I feel this is the right place as it is close to an announcement.
=> Add change log for etsdemo release 0.1.0

ets-demo/etsdemo/tests/test_info.py
The current latest version of eam on PyPI is 1.1.0, which does not have this `--debug` option.
This means the test would fail if one installs `etsdemo` and its dependencies all via PyPI.
This PR fixes this by removing the option. The option is not required for the test objective: It only serves to make debugging test failure a bit easier.
This issue has not appeared on CI because `eam` is installed via EDM. And the latest version available has this `--debug` option.
=> TST: Remove --debug from the eam commmand which isn't available on eam 1.1.0

ets-demo/etsdemo/tests/test_main.py
The test for running `main` in the normal condition is too strict: It could fail if there were warnings ~printed to the console through code outside of our control~ (Edited:  but the test is about testing logging settings.)
For purpose of the test, we can just assert the log message (asserted in the next test) is not emitted for the normal run condition.
=> Relax test assertion for etsdemo main function

ets-demo/setup.py, traitsui/__init__.py
It was mentioned before that `pip install pyface[pyqt5]` did not work (see https://github.com/enthought/pyface/issues/446#issuecomment-531195281) and I can confirm this for traitsui and etsdemo.
e.g. Calling `pip install traitsui/ets-demo[pyqt5]` would fail:
```
ERROR: Could not find a version that satisfies the requirement pyqt>=5
```
This fixes the problem. The distribution name _is_ `pyqt5`
=> Fix setup extras_require for PyQt5

ets-demo/README.rst
`etsdemo` is now live on PyPI, and can be `pip install`-ed.
This PR adds installation instruction on the README so it is shown on the PyPI page for the project.
It will be available on PyPI the next time we release.
=> Add install instruction for etsdemo

traitsui/wx/list_str_editor.py
Closes #1116
The corresponding test is added in #1115 (`test_list_str_editor_right_click_out_of_bound`). The test is skipped due to another crippling error: https://github.com/enthought/traitsui/issues/752
Before this fix, the test would have failed due to the IndexError. After this fix, the test would error due to #752.
`GetIndex()` could return `-1` when what it actually meant is an invalid index. If not checked, the -1 could have been used incorrectly in places to take the last item of a sequence. I have not confirmed/checked if this scenario has been handled correctly in other places of this editor.
=> Fix index error when clicking space in wx ListStrEditor

traitsui/examples/demo/Advanced/Auto_update_TabularEditor_demo.py, traitsui/examples/demo/Advanced/List_editors_demo.py, traitsui/examples/demo/Advanced/MVC_demo.py, traitsui/examples/demo/Advanced/NumPy_array_view_editor_demo.py, traitsui/examples/demo/Advanced/Popup_Dialog_demo.py, traitsui/examples/demo/Advanced/Scrubber_editor_demo.py, traitsui/examples/demo/Advanced/Statusbar_demo.py, traitsui/examples/demo/Advanced/Table_editor_with_live_search_and_cell_editor.py, traitsui/examples/demo/Advanced/Tabular_editor_demo.py, traitsui/examples/demo/Applications/Python_source_browser.py, traitsui/examples/demo/Dynamic_Forms/dynamic_range_editor.py, traitsui/examples/demo/Standard_Editors/CheckListEditor_simple_demo.py, traitsui/examples/demo/Standard_Editors/EnumEditor_demo.py, traitsui/examples/demo/Standard_Editors/File_Dialog/File_Open.py, traitsui/examples/demo/Standard_Editors/File_Dialog/File_Open_with_FileInfo_Extension.py, traitsui/examples/demo/Standard_Editors/TextEditor_demo.py, traitsui/examples/demo/Standard_Editors/TitleEditor_demo.py, traitsui/examples/demo/Standard_Editors/TreeEditor_demo.py
Some of the lists had indentation which made the description look awkward. This commit simply dedents the lists.
=> Dedent lists in demo description

ets-demo/etsdemo/app.py, ets-demo/etsdemo/tests/test_app.py
Closes #1122
There are two ways to fix the issue: 
(1) Sanitize the file path to a conforming file URI with an absolute path
(2) Use the file name directly and rely on the `base_url_name` set on the HTMLEditor.
This PR uses option (2) to fix this issue: it is the least effort one and is also consistent with the handling in other nodes (e.g. the file handler for the index.rst).
=> Fix display of image file in etsdemo

etstool.py, traitsui/__init__.py
This provides for point 2 of #1125
This PR updates the `extras_requires` to include dependencies for the demo examples.
We should mention this in the README, but then we should also mention installation options for PyQt5 etc... they aren't there at the moment, and I decided not to mix them in this PR.
=> Update extras_require to include requirements for examples

.travis.yml, etstool.py
Looks like PySide2 version was pinned to workaround #509
This was a while ago. Now we have PySide2 5.15.0 from PyPI, let's see if it is good now.
=> Relax constrain on PySide2 version

traitsui/examples/demo/Advanced/Adapted_tree_editor_demo.py, traitsui/examples/demo/Advanced/HDF5_tree_demo.py, traitsui/examples/demo/Advanced/HDF5_tree_demo2.py, traitsui/examples/demo/Extras/Tree_editor_with_TreeNodeRenderer.py, traitsui/examples/demo/Standard_Editors/DataFrameEditor_demo.py
Closes #1125
This PR highlights some additional dependencies in the examples.
Note that for examples that are primarily for editing NumPy array (e.g. `NumPy_array_view_editor_demo.py`), I did not add the mention of "this example requires NumPy" because this feels dumb :)
=> Mention additional dependencies in examples

traitsui/examples/demo/Advanced/Popup_Dialog_demo.py
Fixes #1068 
There is no ui_popup function in https://github.com/enthought/traitsui/blob/master/traitsui/qt4/toolkit.py, but there is in https://github.com/enthought/traitsui/blob/master/traitsui/wx/toolkit.py.
If I am mistaken and this is actually supposed to work on Qt, then the issue can be directly addressed.
=> adding to docstring to specify Popup_Dialog_demo not implemented on qt

.travis.yml, appveyor.yml, etstool.py, install-edm-osx.sh
fixes #1156 
Travis-CI osx VMs use a 2013 CPU which does not support AVX2. This PR updates the ci builds to run the osx build on appveyor whose MacOS VMs use more recent CPUs
=> Update appveyor config to also build on macos

ets-demo/README.rst
This PR clarifies the API documentation for contributing entry points to etsdemo: The entry point group is required to match, but the entry point name isn't.
=> Clarify entry point definition requirement for etsdemo

traitsui/qt4/check_list_editor.py, traitsui/wx/check_list_editor.py
Ref https://docs.python.org/3.6/library/logging.html#logging.Logger.warning
=> logger.warn is deprecated, use logger.warning instead

traitsui/qt4/ui_panel.py
It is possible that a `UI` instance has its `View` set to `None` during the lifetime of a widget or layout that is using the `_size_hint_wrapper` (which is itself a hack).  In some circumstances this causes a segfault at UI dispose time.  This PR puts a guard in place to prevent exceptions in this code.
No tests at the moment, because this is an implementation detail of a hack in a private implementation detail, and I'm not sure I want to be formalizing this piece of code that much, but if review thinks it's needed, I will add.
=> Check that the UI has a valid View before modifying size in _size_hint_wrapper

ets-demo/etsdemo/app.py
This PR updates `super` usage in the `etsdemo` package but not in `traitsui` because `etsdemo` is small and new. This was done using manual search and replace.
=> Clean super usage in etsdemo

traitsui/testing/tester/wx/tests/test_helpers.py
`traitsui.testing.tester.qt4.tests` and `traitsui.testing.tester.wx.tests` are missing `__init__.py`.  Consequently running unittest with discover results in the tests in these packages not being run.
=> Add missing __init__.py for test discovery

traitsui/testing/api.py
As mentioned in the discussion https://github.com/enthought/traitsui/issues/1149#issuecomment-677477757 this adds an empty `traitsui.testing.api` module.  
This file will need to be appropriately populated to complete the second bullet on issue #1173
=> adding a blank api for UITester

traitsui/testing/tester/wx/helpers.py, traitsui/testing/tester/wx/implementation/range_editor.py, traitsui/tests/editors/test_range_editor.py
fixes #1183 
fixes #1182 
fixes #1177 
This PR explicitly handles the case when a KeyClick command is issued with "Backspace" as the key.  It also makes the same change that was added in PR #1181 for `key_sequence_text_ctrl` to `key_click_text_ctrl`
Finally, it makes the default behavior for entering a textbox to have the insertion point be the rightmost rather than the leftmost point of text.  (this keeps consistent behavior with qt)
=> fix UITester wx - explicitly handle a KeyClick('Backspace') and update key_click_text_ctrl

traitsui/testing/tester/wx/helpers.py, traitsui/testing/tester/wx/tests/test_helpers.py, traitsui/tests/editors/test_text_editor.py
This PR fixes the implementation of `KeyClick("Backspace")` on wx.TextCtrl when there is already some selected text.
For reference, we could not get [`wx.TextCtrl.EmulateKeyPress`](https://wxpython.org/Phoenix/docs/html/wx.TextCtrl.html#wx.TextCtrl.EmulateKeyPress) to emulate backspace on Windows, hence we had to emulate it ourselves. See https://github.com/enthought/traitsui/pull/1184 and this [discussion on wxPython forum](https://discuss.wxpython.org/t/wx-textctrl-and-emulatekeypress/28300).
=> Fix backspacing wx textbox when there is selected text

.travis.yml, etstool.py
Travis CI + wx has not been able to build. This PR brings it recently changes on pyface.
~If that does not work I will need to do more debugging. Marking as a draft for now.~ Edited: That works.
For reference, the error looks like this:
```
======================================================================
ERROR: traitsui (unittest.loader._FailedTest)
File "/home/travis/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/traitsui/__init__.py", line 69, in load_tests
from traitsui.tests._tools import filter_tests
File "/home/travis/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/traitsui/tests/_tools.py", line 24, in <module>
from pyface.api import GUI
File …
```
=> Update travis CI + wx setup

traitsui/testing/tester/qt4/common_ui_targets.py, traitsui/testing/tester/qt4/implementation/text_editor.py, traitsui/testing/tester/qt4/registry_helper.py, traitsui/testing/tester/wx/common_ui_targets.py, traitsui/testing/tester/wx/implementation/text_editor.py, traitsui/testing/tester/wx/registry_helper.py, traitsui/tests/editors/test_range_editor.py, traitsui/tests/editors/test_text_editor.py
This PR refactors how we add interaction handlers for editable textboxes.
There are small changes to the tests to exercise more interactions in order to ensure the refactoring has not broken things.
With this refactoring, I can add interactions for things like the text-style FontEditor relatively easily (see #1161).
=> Refactor registering interaction handlers for editable textboxes

traitsui/testing/tester/qt4/implementation/instance_editor.py, traitsui/testing/tester/wx/implementation/instance_editor.py, traitsui/tests/editors/test_instance_editor.py, traitsui/wx/instance_editor.py
Targeting #1208
This PR is intended to accompany my review comments... it does not need to be merged but if @aaronayres35 is happy with this to be merged to #1208, please feel free to review and I will address review comments accordingly.
=> Move MouseClick to a separate interaction for simple instance editor

traitsui/qt4/editor.py, traitsui/tests/editors/test_table_editor.py
This should fix #741, though I'm not entirely sure where to add tests to confirm it! Having it work in one canopy data app where this came up probably isn't sufficient..
The problem seemed to be that `Action`s with an `on_perform` attribute hit :
https://github.com/enthought/traitsui/blob/884414547b634ce30421df29e817bb6beaa1036c/traitsui/qt4/editor.py#L260-L261
and called the function set as `on_perform`, but then afterwards hit:
https://github.com/enthought/traitsui/blob/884414547b634ce30421df29e817bb6beaa1036c/traitsui/qt4/editor.py#L263
which basically does the same thing again, only in the `Action` class this time.
https://github.com/enthought/pyface/blob/4b91627c8a8ab2680f62e85af261d1da54675558/pyface/action/action.py#L123-L132
Just returning after the first one would mean …
=> Fix for menu actions with on_perform being performed twice

traitsui/tests/editors/test_tree_editor.py
This PR adds a test for #1166, persumably fixed by the guard added in #1168
=> Add test for TreeEditor with a nested UI

traitsui/testing/tester/qt4/default_registry.py, traitsui/testing/tester/qt4/implementation/instance_editor.py, traitsui/testing/tester/wx/default_registry.py, traitsui/testing/tester/wx/implementation/instance_editor.py, traitsui/tests/editors/test_instance_editor.py, traitsui/wx/instance_editor.py
fixes #1206 
Adds a simple implementation for Instance editor, and modifies tests to now use UI Tester.  Also adds an additional test to see that the displayed editor updates if a trait changes externally to the editor.  
Note: the code for the wx instance editor had to be changed very slightly in order to gain access to the ui of interest.  This idea was take from kit's draft branch #1150
=> UI Tester updates - Instance editor implementation

traitsui/testing/tester/qt4/implementation/check_list_editor.py, traitsui/testing/tester/wx/implementation/check_list_editor.py, traitsui/tests/editors/test_check_list_editor.py
fixes #1214 
Effectively this does exactly what was done for the enum editor in pr #1191 
It handles the strange behavior of the checklist grid being populated in row major with order with the elements arranged in column major order.
=> UI Tester checklist editor indexing fix

traitsui/tests/editors/test_enum_editor.py
One of the existing tests (`test_radio_enum_editor_button_update`) for the radio enum editor checks the UI states are updated when the trait state is updated.
The test was added prior to the introduction of UITester.
The implementation of the test does this by getting all the states of the radio buttons, but since radio buttons are "auto-exclusive" for one-of-many selections, the implementation for querying for the selected item achieves the same goal.
This PR:
- Update the test to use UITester features. This demonstrates one of the two patterns of UI testing: Updating the trait results in UI state change.
- Remove `test_radio_enum_displayed_selected_text` because its purpose is for exercising the logic of `SelectedText`. The test updated here now uses `SelectedText` so …
=> TST: Update a test on Radio enum editor to use UITester

etstool.py, traitsui/__init__.py
When I was trying to add flake8 to CI, I notice that the existing organization of dependencies in `etstool.py` will force me to add flake8 to the `dependencies` set. This led me to realize that the dependencies set has mixed runtime dependencies and CI dependencies.
This PR:
- Reorganize the dependencies in `etstool.py` to clarify what dependencies are used for what, with a goal of matching those used by `setup.py`
- Add an optional set of dependencies called `"editors"` to be used by `setup.py` to specify the dependencies on optional features:
- `pandas` is required by DataFrameEditor. (Note that `DataFrameEditor` is not exposed in `api`)
- `numpy` is required by ArrayEditor and DataFrameEditor. `traitsui.api` explicitly allows `numpy` to be absent. If numpy absent, `traitsui.api` won't …
=> Maint: Reorganize optional dependencies in etstool.py and setup.py

traitsui/tests/ui_editors/test_data_frame_editor.py
Currently the test module for DataFrameEditor will fail with ImportError if one runs `python -m unittest discover -t . traitsui` with an environment installed from PyPI, Qt5 and without NumPy.
NumPy is an optional dependency, e.g. the `ArrayEditor` is skipped in `traitsui.api` if importing it should fail due to absence of numpy.
This PR skips the test module if NumPy cannot be imported, in the same way that the module is skipped if pandas is not available.
=> Skip test module for DataFrameEditor if numpy is absent

traitsui/testing/tester/ui_tester.py, traitsui/testing/tester/ui_wrapper.py
This PR moves the docstrings for parameters in the `UITester` and `UIWrapper`'s  `__init__` to the class docstring.
This follows NumPy docstring guide. The clarifies parameters for initialization and attributes accessible post-instantiation.
=> Update docstrings for UITester and UIWrapper

traitsui/testing/tester/qt4/helpers.py, traitsui/testing/tester/qt4/implementation/check_list_editor.py, traitsui/testing/tester/qt4/implementation/list_editor.py, traitsui/testing/tester/wx/implementation/check_list_editor.py, traitsui/testing/tester/wx/implementation/list_editor.py, traitsui/tests/editors/test_check_list_editor.py
fixes #1197 
I believe that `register_editable_textbox_handlers` is actually already currently used where it should be.  Thus, this PR simply changes the checklist and List editor implementations to utilize the new `_BaseSourceWithLocation` base class added in #1191 
Note this was originally sitting on top of PR #1215 (hence the couple extra commits in the commit history).  That is now merged though, so the files changed are correct.
=> UI Tester - use _BaseSourceWithLocation for Checklist and List editor implementations

traitsui/testing/tester/qt4/implementation/list_editor.py, traitsui/testing/tester/qt4/implementation/range_editor.py, traitsui/testing/tester/wx/implementation/list_editor.py, traitsui/tests/editors/test_range_editor_text.py
This solves the problem mentioned here: https://github.com/enthought/traitsui/pull/1209#issuecomment-694313188
We did not make a necessary change to a test on #1209 after changing the RangeEditor implementation
=> Fixing test that was broken by #1209

traitsui/testing/tester/wx/helpers.py, traitsui/testing/tester/wx/implementation/button_editor.py, traitsui/testing/tester/wx/implementation/instance_editor.py, traitsui/testing/tester/wx/implementation/ui_base.py, traitsui/testing/tester/wx/registry_helper.py, traitsui/testing/tester/wx/tests/test_helpers.py
Fixes #1194 
Introduces new `_create_event` helper function, and `mouse_click` decorator.  
Also, note that the decorator enforces arguments to mouse click functions to be key word and not positional arguments.  When calling these mouse click functions we typically already passed arguments with a keyword, but in a few cases we had passed them by position.  Those have been replaced in this PR.
=> UI Tester wx mouseclick refactor

traitsui/testing/tester/qt4/default_registry.py, traitsui/testing/tester/qt4/implementation/font_editor.py, traitsui/testing/tester/wx/default_registry.py, traitsui/testing/tester/wx/implementation/font_editor.py, traitsui/tests/editors/test_font_editor.py, traitsui/wx/editor_factory.py
Closes #942 
Also resolve the second item in https://github.com/enthought/traitsui/issues/1073
Also part of #752 
The cause of the issue is as explained in #942.  This base class is used by both the text style FontEditor and the text style CompoundEditor.
I came across this while I was trying to _resolve_ #1145.
(The solution I am going to propose for #1145 also "resolves the error" in the context when the UI wrapping this editor has its `dispose` method called. But I believe removing the handler hooks with Unbind is still the right thing to do.)
As a drive-by improvement to the test coverage, implementations are added for testing the Qt implementation of the same editor.
=> Implement dispose for wx simple TextEditor (base class)

traitsui/testing/tester/wx/helpers.py, traitsui/testing/tester/wx/tests/test_helpers.py
fixes #1228 
simply moves the text entry's insertion point to the end if a key click is called with "End".
Also a simple test for this is added to this PR.
=> Adding 'End' as a possible value for Key click text entry on wx

traitsui/testing/tester/tests/test_ui_tester.py, traitsui/tests/_tools.py
The observation in https://github.com/enthought/traitsui/pull/1161#discussion_r476589718 led me to this: `create_ui` context manager should capture and reraise exceptions occurred from the GUI event loop while disposing a UI.
However this does not resolve the strangeness observed in https://github.com/enthought/traitsui/pull/1161#discussion_r476589718
The event that causes the error (which was fixed by #1161) was processed much much later.
=> Reraise exception captured when the UI is disposed from create_ui

traitsui/testing/tester/qt4/implementation/instance_editor.py, traitsui/testing/tester/qt4/implementation/list_editor.py, traitsui/testing/tester/registry_helper.py, traitsui/testing/tester/ui_tester.py, traitsui/testing/tester/wx/implementation/instance_editor.py, traitsui/testing/tester/wx/implementation/list_editor.py
Follow this https://github.com/enthought/traitsui/pull/1227#discussion_r490837104
This PR renames `register_nested_ui_solvers` to `register_traitsui_ui_solvers`
The function does not care if the `traitsui.ui.UI` instance is nested or not. The name is slightly long, but verbosity for understanding trumps ~conciseness~.
Note: Could not use the name `register_ui_solvers` here because the function is only about `traitsui.ui.UI`. The word "UI" is too broad and is used in many other context.
=> Rename register_nested_ui_solvers to register_traitsui_ui_solvers

traitsui/testing/exception_handling.py, traitsui/testing/gui.py, traitsui/testing/tester/ui_tester.py, traitsui/testing/tester/ui_wrapper.py, traitsui/testing/tests/test_exception_handling.py, traitsui/testing/tests/test_gui.py, traitsui/tests/_tools.py
Closes #1238
- The implementation of `traitsui.tests._tools.create_ui` is now moved to `UITester.create_ui`. The `traitsui.tests._tools.create_ui` is kept to limit the scope of this PR (otherwise I need to change a lot of test)
- `traitsui.tests._tools.process_cascade_events` is moved to `traitsui.testing.gui`. Its test is also moved. Likewise, the alias in `_tools` is kept, for now to limit scope.
- `traitsui.tests._tools.reraise_exceptions` is moved to `traitsui.testing.exception_handling`. Its test is also moved. Likewise, the alias in `_tools` is kept, for now to limit scope.
=> Reverse dependency so that traitsui.tests._tools depend on traitsui.testing

traitsui/tests/editors/test_range_editor.py
This PR fixes the following test failure on Windows + wx (CI allowed to fail, hence hard to spot)
```
ERROR: test_range_text_editor_set_with_text_valid (traitsui.tests.editors.test_range_editor.TestRangeEditor)
File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\tests\editors\test_range_editor.py", line 129, in test_range_text_editor_set_with_text_valid
number_field_text.target.textbox.SetInsertionPointEnd()
AttributeError: 'RangeTextEditor' object has no attribute 'textbox'
```
This was caused by changes to implementation details (note the original code is wx specific). With #1229 support, we can change insertion point in test code without relying on …
=> Fix test for text-style RangeEditor on wx and Windows

traitsui/testing/tester/locator.py, traitsui/testing/tester/qt4/implementation/range_editor.py, traitsui/testing/tester/wx/implementation/range_editor.py, traitsui/tests/editors/test_list_editor.py, traitsui/tests/editors/test_range_editor.py
fixes #1233 
Removes the `locator.WidgetType` enum class, and replaces it  with more flexible standalone classes for each widget type.
=> replacing WidgetType enum members with standalone types

traitsui/testing/tester/registry.py, traitsui/testing/tester/tests/test_registry.py, traitsui/testing/tester/tests/test_ui_wrapper.py, traitsui/testing/tester/ui_wrapper.py
Closes #1211
Instead of implementing properties on `UIWrapper`, this PR implements a `help` method to print help messages when it is invoked.
Its current use case is only for developers to discover supported features while they are writing tests.
e.g. if I add the following in this [test](https://github.com/enthought/traitsui/blob/1b2a3933c5313f1d4d2084f197bdb6fc8e4c1ecf/traitsui/tests/editors/test_list_editor.py#L122-L128):
```
print("Help on the list editor")
list_.help()
print("Help on an item in the list editor")
list_.locate(locator.Index(1)).help()
```
Then I see this being printed:
<details>
<summary> printed content </summary>
```
Help on the list editor
Interactions
------------
No interactions are supported.
Locations
---------
<class 'traitsui.testing.tester.locator.Index'>
A …
```
=> Add help method to UIWrapper for self-discovery

integrationtests/test_all_examples.py, traitsui/examples/demo/Standard_Editors/CheckListEditor_simple_demo.py, traitsui/testing/tester/qt4/helpers.py
addresses part of #1220 
This PR, in addition to adding the UI Tester test/example for CheckListEditor_simple_demo.py, modifies the `mouse_click_qwidget` function to address a test failure observed here and in other places.  (see comments).  It fixed the problem by handling clicking of objects that subclass `QAbstractButton` separately.
=> adding UI Tester test/example for CheckListEditor_simple_demo.py

traitsui/testing/tester/common_ui_targets.py, traitsui/testing/tester/qt4/common_ui_targets.py, traitsui/testing/tester/qt4/implementation/button_editor.py, traitsui/testing/tester/qt4/implementation/check_list_editor.py, traitsui/testing/tester/qt4/implementation/enum_editor.py, traitsui/testing/tester/qt4/implementation/font_editor.py, traitsui/testing/tester/qt4/implementation/instance_editor.py, traitsui/testing/tester/qt4/implementation/list_editor.py, traitsui/testing/tester/qt4/implementation/range_editor.py, traitsui/testing/tester/qt4/implementation/text_editor.py, traitsui/testing/tester/qt4/implementation/ui_base.py, traitsui/testing/tester/registry.py, traitsui/testing/tester/registry_helper.py, traitsui/testing/tester/tests/test_ui_tester.py, traitsui/testing/tester/tests/test_ui_wrapper.py, traitsui/testing/tester/ui_tester.py, traitsui/testing/tester/ui_wrapper.py, traitsui/testing/tester/wx/common_ui_targets.py, traitsui/testing/tester/wx/implementation/button_editor.py, traitsui/testing/tester/wx/implementation/check_list_editor.py, traitsui/testing/tester/wx/implementation/enum_editor.py, traitsui/testing/tester/wx/implementation/font_editor.py, traitsui/testing/tester/wx/implementation/instance_editor.py, traitsui/testing/tester/wx/implementation/list_editor.py, traitsui/testing/tester/wx/implementation/range_editor.py, traitsui/testing/tester/wx/implementation/text_editor.py, traitsui/testing/tester/wx/implementation/ui_base.py, traitsui/tests/editors/test_enum_editor.py, traitsui/tests/editors/test_range_editor.py
fixes #1249 
This pr replaces UIWrapper.target with UIWrapper._target. I also tried to make the change where appropriate in the documentation (in docstrings). 
Note this may cause some currently open PRs to have test failures (e.g. #1243).  They will simply need to update and uses of .target to ._target, which should be an easy fix.
=> Rename UIWrapper.target to UIWrapper._target

integrationtests/test_all_examples.py, traitsui/examples/demo/Standard_Editors/InstanceEditor_demo.py
part of #1220 
This PR adds a very simply test for the instance editor demo.  
One thing to note, I originally intended to test by using the simple style first and then custom.  However, once the tester clicks on the button for the simple style and the new ui for the instance pops up, I don't believe we currently have a way to close that ui.  Might be something we eventually want to add
=> adding UI Tester test/example for InstanceEditor_demo.py

integrationtests/test_all_examples.py, traitsui/examples/demo/Standard_Editors/TextEditor_demo.py, traitsui/examples/demo/Standard_Editors/tests/test_TextEditor_demo.py
This PR implements the `load_tests` protocol so that we can add tests to the nonpackage folders, e.g. inside `traitsui/examples/demo`, e.g. `traitsui/examples/demo/Standard_Editors/tests/test_TextEditor_demo.py`
- Implements `load_tests` in `test_all_examples` to load addition tests from the nonpackage folder containing demos
- Add a test in the examples/demo folder to demonstrate this works.  I can remove it. It is only added to test the load_tests and because otherwise the load_tests logic would be unused.
The test added can be run on etsdemo too. The GUI will appear for a short while as a script is always run as soon as the user clicks on it (not sure if it is desirable, but that's orthogonal).
=> Implement load_tests to load and run tests from the demo folder(s)

ets-demo/etstool.py, etstool.py
This PR adds a new `shell` click command - which when run activates the development environment for traits. The usual command line options are available to choose the environment name and the runtime version/toolkit of the development environment. Underneath the hood, the click command just uses the `edm shell` command with the appropriate environment name, which is why the docstring for the click command is _almost_ the same as that of `edm shell`.
=> Add a new shell command

traitsui/testing/tester/_ui_tester_registry/default_registry.py
This is a very short PR to address the issue that was brought up here: https://github.com/enthought/traitsui/pull/1264#discussion_r493637964
=> Use current package in default_registry.py instead of hard coded path when locating toolkit specific default_registry module

traitsui/testing/api.py
Part of #1173 
Note to keep this PR small and easier to review, this PR simply adds the import statements to `traitsui.testing.api.py`.  It does not change any other code to actually use the api (see the fifth bullet on 1173). These changes will be made in a separate PR after this is merged.  
I don't believe anything else belongs in the api atm?  One thing I wasn't sure about was if `UIWrapper` should be included, but I could not think of a case where a user would need a wrapper separate from having a UITester.  In all the test code we have written so far we never needed to import `UIWrapper`.  However, I very well may be wrong and it can easily be added here.
=> Populating the traitsui.testing.api module

traitsui/examples/demo/Standard_Editors/ListEditor_demo.py, traitsui/examples/demo/Standard_Editors/tests/test_ListEditor_demo.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/list_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/list_editor.py, traitsui/tests/editors/test_list_editor.py
fixes #1253 
This PR modifies the UI Tester implementation of Custom List Editor so that it works with Lists of objects that don't have nested UIs (e.g. just a list of Strings).  It does so by the means described on issue 1253 and here: https://github.com/enthought/traitsui/pull/1252#issuecomment-696385370
=> UI Tester update List Editor implementation to not only work with nested uis

.travis.yml, README.rst, appveyor.yml
The current test coverage for the code base is 60% (after combining coverage from Qt and Wx, running from an OSX machine with Python 3.6).  However the codecov badge is showing 30+%, that is misleading.
The codecov report is unlikely to useful either. See similar issue on Traits: https://github.com/enthought/traits/issues/919
This PR:
- Remove the misleading coverage badge from README
- Remove scripts to submit coverage from CI
~Unverified:~(edited) I believe the discrepancy is caused by the fact that the wx CI job is still failing (which should be fixed), the test coverage from wx build is therefore not submitted for the combined statistics.
=> Remove codecov badge and submission of coverage from CI

traitsui/tests/editors/test_button_editor.py
This PR adds a test for ButtonEditor to verify that a button is disabled when the `enabled_when` flag results in a falsey value.
(This is motivated by wanting to get more test coverage for `traitsui.testing`, e.g. this [line](https://github.com/enthought/traitsui/blob/815cfb074cbf6063178e8607c37cb0638a30fbee/traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/button_editor.py#L34)).
=> TST: Expand test for ButtonEditor to handle enabled/disabled button

traitsui/examples/demo/Advanced/tests/test_List_editor_notebook_selection_demo.py, traitsui/examples/demo/Applications/tests/test_converter.py, traitsui/examples/demo/Standard_Editors/tests/test_ButtonEditor_demo.py, traitsui/examples/demo/Standard_Editors/tests/test_ButtonEditor_simple_demo.py, traitsui/examples/demo/Standard_Editors/tests/test_CheckListEditor_simple_demo.py, traitsui/examples/demo/Standard_Editors/tests/test_EnumEditor_demo.py, traitsui/examples/demo/Standard_Editors/tests/test_InstanceEditor_demo.py, traitsui/examples/demo/Standard_Editors/tests/test_TextEditor_demo.py
This fixes the fifth bullet of #1173 
It simply changes the import statements in the current tests of examples in `examples/demo` to import from the now populated `traitsui.testing.api`
=> Update UI Tester demo examples to import from traitsui.testing.api

traitsui/qt4/tests/test_tabular_model.py, traitsui/testing/_exception_handling.py, traitsui/testing/tests/test_exception_handling.py
Closes #1232
(Part of #1173)
This PR
- Removes setting trait change exception handler in `reraise_exceptions`.
- Apply `BaseTestMixin` to one more test case that would have lost the setting if this wasn't done before/when `reraise_exceptions` lost this behaviour. Most of the other test cases that need this should have received the treatment from #1266.
(I missed this one test case there. 😞   I searched for these test cases by finding all references to `reraise_exceptions`, but I overlooked `traitsui.qt4.tests` package back then.)
=> Remove trait change exception handler in reraise_exceptions

docs/source/traitsui_user_manual/testing.rst, traitsui/testing/tester/_ui_tester_registry/_common_ui_targets.py, traitsui/testing/tester/_ui_tester_registry/_traitsui_ui.py, traitsui/testing/tester/_ui_tester_registry/qt4/_registry_helper.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/button_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/editor_factory.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/enum_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/instance_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/list_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/range_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/text_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/ui_base.py, traitsui/testing/tester/_ui_tester_registry/wx/_registry_helper.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/button_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/editor_factory.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/enum_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/instance_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/list_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/range_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/text_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/ui_base.py, traitsui/testing/tester/registry.py, traitsui/testing/tester/tests/test_registry.py, traitsui/testing/tester/tests/test_ui_wrapper.py
This PR merely does the name change:
- `TargetRegistry.register_solver` -> `TargetRegistry.register_location`
- `TargetRegistry.register_handler` -> `TargetRegistry.register_interaction`
User manual is updated as well.
Closes #1273
=> Rename TargetRegister.register_handler and register_solver

traitsui/examples/demo/Standard_Editors/BooleanEditor_demo.py, traitsui/examples/demo/Standard_Editors/BooleanEditor_simple_demo.py, traitsui/examples/demo/Standard_Editors/tests/test_BooleanEditor_demo.py, traitsui/examples/demo/Standard_Editors/tests/test_BooleanEditor_simple_demo.py, traitsui/testing/api.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/boolean_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/default_registry.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/boolean_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/default_registry.py, traitsui/testing/tester/query.py, traitsui/tests/editors/test_boolean_editor.py
This PR adds an implementation for BooleanEditor to UI Tester.  It also modifies the current `test_boolean_editor.py` file by modifying it to use UI Tester, and adding another simple test.  Lastly, it adds tests for the examples `BooleanEditor_demo` and `BooleanEditor_simple_demo`. The previously list changes are made in roughly 1 change per commit.
=> UI Tester - add boolean editor

traitsui/testing/tester/tests/test_ui_tester.py, traitsui/testing/tester/ui_tester.py, traitsui/testing/tester/ui_wrapper.py, traitsui/tests/editors/test_range_editor.py
This PR makes a few of the arguments on `UITester` and `UIWrapper` keyword only. When callers are required to set arguments by names, this allows more room for future changes that is backward compatible. This should incur little inconvenience as these arguments are not often set by user code.
=> Maint: Make registries and delay arguments keyword only

traitsui/testing/tester/tests/test_ui_wrapper.py, traitsui/testing/tester/ui_wrapper.py
This PR causes `UIWrapper.locate` (testing tool) to process the GUI events prior to resolving locations on the GUI.
Use case:
- When a trait is changed to cause GUI elements to change (e.g. the available values in the enum is dynamically computed), those updates may have been deferred for the GUI event loop to process (using dispatch="ui" in on_trait_change or observe). In that case, we should locate a GUI element only after those events are processed such that the GUI state is consistent.
Locating a GUI element is similar in concept compared to `UIWrapper.inspect`. `inspect` also needs to process GUI events in order to ensure the GUI is in a consistent state prior to getting the GUI state for testing.
We should only need to process events prior to locating the GUI element. Locate should …
=> Process GUI events before resolving location

traitsui/testing/tester/_ui_tester_registry/_layout.py, traitsui/testing/tester/_ui_tester_registry/qt4/_interaction_helpers.py, traitsui/testing/tester/_ui_tester_registry/wx/_interaction_helpers.py, traitsui/testing/tester/ui_tester.py
This PR makes some very simply changes to comments and doc strings in the `traitsui.testing` module.  It fixes some typos, updates comments to be more clear/accurate, and adds a 'Raises' section to various doc strings.
=> Misc. clean up of UI Tester (typos, comments, docstring updates)

docs/source/api/traitsui.testing.api.rst, docs/source/api/traitsui.testing.rst, docs/source/traitsui_user_manual/testing.rst, traitsui/testing/api.py
This PR
- Expand docstring for `traitsui.testing.api` so that the API reference provides links to the objects of interest directly.
- Add `traitsui.testing.api` to the TOC
- Minor grammar fix (the cross reference causes the "traitsui.testing.api" to be rendered as "api" with a hyperlink)
=> Doc: Add traitsui.testing.api to the API reference

traitsui/testing/tester/command.py
Generating the API documentation results in a number of warnings. This PR solves the ones from `traitsui.testing`:
```
/Users/kchoi/Work/ETS/traitsui/traitsui/testing/tester/command.py:docstring of traitsui.testing.tester.command.KeyClick:6: WARNING: Unexpected section title.
Attribute
---------
/Users/kchoi/Work/ETS/traitsui/traitsui/testing/tester/command.py:docstring of traitsui.testing.tester.command.KeySequence:6: WARNING: Unexpected section title.
Attribute
---------
```
=> Fix section name to solve Sphinx warning

traitsui/testing/tester/_ui_tester_registry/_common_ui_targets.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/check_list_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/enum_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/list_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/check_list_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/enum_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/list_editor.py
This PR renames a class in a private module to have a public name, as the class is imported by other modules in the same package. Since the module itself is privately named (so is its container package), the class is still considered private from the end user.
=> Rename _BaseSourceWithLocation to BaseSourceWithLocation

docs/source/traitsui_user_manual/testing.rst, traitsui/testing/tester/tests/test_ui_tester.py, traitsui/testing/tester/tests/test_ui_wrapper.py, traitsui/testing/tester/ui_tester.py, traitsui/testing/tester/ui_wrapper.py, traitsui/tests/editors/test_instance_editor.py
Closes #1297
This PR adds a ~"process_events"~ `auto_process_events` flag on `UITester` (propagated to `UIWrapper`) to skip GUI event processing if the users request so.
- User manual is updated to highlight the specific care required when using UITester with ModalDialogTester.  
- Add a test against InstanceEditor that launches a UI as a modal dialog. ModalDialogTester and UITester are used in that test, which demonstrate the issue in #1297 if the flag is set to true.
- The flag is set while instantiating `UITester`, because it is convenient to be able to set it once.
- For correctness, `UITester.create_ui` will also respect this flag.
*Alternative*
- Instead of setting the flag in the object constructor, we can instead pass it through `perform`, `inspect` and `locate`. However I find …
=> Make event processing optional in UITester

traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/list_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/list_editor.py, traitsui/tests/editors/test_list_editor.py
Fixes #1292 
This PR simply uses the current custom list editor implementation for simple list editor.  The classes are so similar, I believe the implementation did not need to be changed.  This PR also adds tests, (basically just took the Custom tests and made them use a Simple List Editor instead).
One thing to note: when running the tests on wx, the tests all pass but there is an extremely long traceback 
<details>
```
$ python -m unittest test_list_editor.py 
01:22:33 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
01:22:33 PM: Debug: Adding duplicate animation handler for '1' type
01:22:33 PM: Debug: Adding duplicate animation handler for '2' type
01:22:33 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
01:22:33 PM: Debug: Adding duplicate …
```
=> UI Tester - implement simple list editor

docs/source/traitsui_user_manual/testing.rst
This PR adds links in the user manual to the recently added demo tests for BooleanEditor and RangeEditor.
I removed one of the links to the ButtonEditor demo test as it has so much in common with the other example that there is little value in referencing both.
=> Doc: Add links two more demo GUI tests to the user manual

traitsui/examples/demo/Advanced/Auto_update_TabularEditor_demo.py, traitsui/examples/demo/Standard_Editors/ButtonEditor_simple_demo.py, traitsui/examples/demo/Standard_Editors/CSVListEditor_demo.py, traitsui/examples/demo/Standard_Editors/ColorEditor_demo.py, traitsui/qt4/button_editor.py
Closes #928 
Closes #1245 (after causing `TabularEditor.update` to fire, from this [comment](https://github.com/enthought/traitsui/issues/1245#issuecomment-696062894)).
The issue affects Mac OSX and Qt only. This [macOSX specific limitation on Qt documentation](https://doc.qt.io/qt-5/macos-issues.html#using-native-cocoa-panels) seems relevant.
This issue is not specific to the textbox, as I can reproduce the same behaviour with a different widget, using just QPushButton and QLabel.
<details>
<summary> Same strange behaviour using Two QPushButton and QLabel </summary>
```
import sys
from PyQt5 import QtWidgets, QtCore
class MainWindow(QtWidgets.QWidget):
def __init__(self, ):
super().__init__()
self.count = 1
self.label = QtWidgets.QLabel(self)
self.button = QtWidgets.QPushButton('button', …
```
=> Fix Qt button click failing to cause other widgets to update

traitsui/tests/editors/test_datetime_editor.py
This PR does a simple clean up on a test that is using a different date time every time the test is run.
=> Maint: Make a test using datetime more deterministic

traitsui/tests/editors/test_datetime_editor.py
fixes #1096 
This PR is simply a one line change to pass a null `QTime` object as the second argument to the `QDateTime` constructor, so that it is using a non-deprecated signature.
=> Fix QDateTime deprecation warning

traitsui/qt4/constants.py
fixes #1114 
This PR simply replaces `QtGui.QApplication.desktop()` with `QtGui.QApplication.screens()[0]` so that `.availableGeometry` can be called on a QScreen object (where it is not a deprecated method) rather than on a `QDesktopWidget` object.  
My only concern is I do not know how the list of screens obtained by `.screens()` is ordered in the case when multiple screens are being used.  The documentation [here][https://doc.qt.io/qt-5/qguiapplication.html#screens] simply says "Returns a list of all the screens associated with the windowing system the application is connected to."
In the code we actually run 
```
_geom = QtGui.QApplication.screens()[0].availableGeometry()
screen_dx = _geom.width()
screen_dy = _geom.height()
```
and I confirmed that before and after this change the …
=> Fix QDesktopWidget.availableGeometry deprecation warning

traitsui/qt4/table_editor.py
fixes #1097 
This PR simply uses `QFontMetrics().horizontalAdvance()` instead of `QFontMetrics().width()`when possible (`horizontalAdvance` was introduced in Qt 5.11) to avoid a deprecation warning.
=> Fix QFontMetrics.width deprecation warning

traitsui/testing/tester/_ui_tester_registry/wx/_interaction_helpers.py
Fix #1200
This fixes the view not updating when KeySequence (on wx TextCtrl) writes each of the key characters. The view is not updated because when the for loop is busy, wx has not got a chance to process pending events. Note that this only affects visuals when one tries to debug a test visually.
=> Fix key sequence not updating view per keystroke on wx

traitsui/view_element.py
This PR removes a try/except around the `AbstractViewElement` import from traits.api. If we're assuming that we're using Traits >= 6.0 (which we're already doing in other parts of the codebase - see #1323), then `AbstractViewElement` will always be available.
This PR represents the final step of the dependency inversion dance started in enthought/traits#610.
=> Assume that AbstractViewElement is available in Traits

traitsui/__init__.py
The TraitsUI codebase already implicitly assumes that we're using Traits >= 6.0 (for example, when importing the `Datetime` trait type from traits.api). This PR makes that assumption explicit in the setup file.
(Context: I wanted to remove the try/except for the `AbstractViewElement` import (which I'll do in another PR). That removal is only valid if we insist on Traits >= 6.0, but I realised that we're already implicitly making that assumption.)
=> Explicitly require a minimum version for Traits

traitsui/examples/demo/Standard_Editors/ImageEnumEditor_demo.py, traitsui/qt4/enum_editor.py
Closes #1304 
The solution is exactly the same as #1303.
I reproduced the issue on OSX 10.15.5 (with both PyQt5 and PySide2) and then verified that this change fixes the issue.
Again, this has implications for tests that don't run the GUI event loop between clicking the button and checking for trait change.
In TraitsUI tests, we have tests using `UITester` for this logic:
https://github.com/enthought/traitsui/blob/a79d7f387bb8d697aff6134e9cdb2a0e81379719/traitsui/tests/editors/test_enum_editor.py#L378-L379
`perform` already does event processing, so the test is happy there.
We also have tests that have yet to be converted to use UITester, and it does the event processing:
https://github.com/enthought/traitsui/blob/964c0110112adc9dc35cf5c6f7f6eedf7ed28fc7/traitsui/tests/editors/test_image_e …
=> Fix ImageEnumEditor button not causing other widget to updates on OSX and Qt

traitsui/examples/demo/Standard_Editors/SetEditor_demo.py, traitsui/qt4/set_editor.py
Closes #1305
The solution is exactly the same as #1303. Again, no tests can be written for this. 
I reproduced the issue on OSX 10.15.5 (with both PyQt5 and PySide2) and then verified that this change fixes the issue.
Like in #1303, this change has implications for tests that try to call `click` directly without causing the event loop to process pending events before checking for state change. Currently tests in TraitsUI are either using UITester that handles this automatically, or have already been driving the event loop processing manually. Therefore the tests here do not require changes.
=> Fix SetEditor on Qt and OSX not updating view after button clicks

traitsui/testing/api.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/button_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/ui_base.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/button_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/ui_base.py, traitsui/testing/tester/query.py, traitsui/tests/editors/test_button_editor.py, traitsui/tests/test_ui.py
Closes #1294 
This PR adds a new `IsEditable` query class for UI Tester, along with implementations for the standard traitsui `ButtonEditor` and the `ui_base` `ButtonEditor`.  It also adds very simple check to the currently existing tests for these editors using the new query class.
=> UI Tester - add IsEnabled query class and implementations for Button Editors

traitsui/qt4/constants.py, traitsui/qt4/toolkit.py, traitsui/wx/constants.py, traitsui/wx/helper.py, traitsui/wx/toolkit.py, traitsui/wx/ui_live.py, traitsui/wx/ui_modal.py, traitsui/wx/ui_panel.py
fixes #1316 
~~This PR removes the screen size from the `traitsui.qt4.constants.py` and `traitsui.wx.constants.py` files~~ (Edit: they have been added back in and use pyface's `SystemMetrics`.  They were added back as they had been public and it is possible they may be used elsewhere). Note pyface's `SystemMetrics`  is now used to get these values whenever they are needed (only a few places) within traitsui, rather than getting them from `constants.py`.  I.e. the constants which remain in the `constants.py` files are not used in traitsui itself, but could still potentially be being used elsewhere.   
Note that this will reintroduce deprecation warnings which were resolved by #1311 ~~until https://github.com/enthought/pyface/pull/719 is merged on pyface~~ (Edit: it is now merged) and a …
=> Replace screen metrics code with Pyface implementation

traitsui/testing/tester/ui_wrapper.py
This PR fixes a few missing "Returns" block in the `UIWrapper` docstrings (part of the public API) and some drive-by language improvements.
Purely documentation change, i.e. no behavioural change.
=> Doc: Improve docstrings on UIWrapper

docs/source/traitsui_user_manual/testing.rst, traitsui/testing/tester/ui_wrapper.py
This PR improves the documentation to clarify that `UIWrapper._target` is a protected (or internal?) attribute that is neither public or private. While it is expected to be used, it should be used with discretion.
The attribute is expected to be used for extending the API (it is mentioned in the "Advanced Testing" section). It deliberately begs the questions "are you sure you want to use it"  / "could you do this differently" / "should you request the support to be implemented upstream". Whether it is appropriate to be used depends on the context, e.g. it may expose the implementation details that do not belong to the same project, or the implementation details may be maintained in the same place such that it is less of a problem.
The documentation here is also useful for developers …
=> Doc: Improve documentation on the UIWrapper._target being protected

CHANGES.txt
Part of https://github.com/enthought/traitsui/issues/1307
This PR updates the changelog with changes for Release 7.1.0
This PR should target a new branch `maint/7.1` (Edited: Done)
=> Update Changelog for release 7.1.0

ci-src-requirements.txt
[Targeting 7.1 maintenance branch]
This PR updates this CI source requirement such that Pyface maint/7.1 branch is used in tests.
=> Update pyface version being run on CI

appveyor.yml
This PR updates the Appveyor config on master to accept builds on any branch matching `maint/*`, this is such that future maintenance branch created from master does not have to update this setting anymore.
=> Accept any Appveyor builds on maintenance branch

CHANGES.txt
[Targeting maint/7.1]
This PR adds a section in the changelog to remind users about the potential impact on tests due to the fix/workaround to Qt PushButton (and that now they may try to remove their workarounds).
=>  Add 'Notes on Upgrading' to the Changelog for 7.1

etstool.py
The current `docs` command in `etstool.py` cannot be reliably run on Windows as reported by @rahulporuri 
While I could not reproduce, we can avoid the issue by using the sphinx command directly.
The make files are kept, I believe some developers still prefer to use them(?). It does risk the two going out-of-sync though.
Closes #997
=> Allow docs command to be run on Windows

traitsui/testing/api.py
This PR adds a reference to the new `IsEnabled` query in the api module docstring.
=> Add IsEnabled to the testing api docstring

CHANGES.txt
[Targeting maint/7.1]
On second pass of the changelog, there are some minor improvements we can make.
- Add a mention to encourage users to upgrade to Traits 6.1
- Move behaviourial fixes to the top of the "Fixes" section.
- Move fixes to deprecation warning that users can see together.
This PR may be easier to review commits by commits.
=> Improve changelog for release 7.1

traitsui/examples/demo/Standard_Editors/tests/test_ListEditor_demo.py
I believe the PR to introduce this test was not merged before #1274 and there was probably a copy paste error.  
This PR simply uses the testing api for imports and removes an old comment.
=> Update UI Tester demo example for ListEditor demo to import from traitsui.testing.api

docs/source/conf.py
Closes #1375 
Similar to https://github.com/enthought/pyface/pull/762, this PR adds a skip logic in autodoc so that `load_tests` does not appear in the API documentation.
Maybe a more scalable and explicit solution is to have a decorator purely for documentation purpose, and the decorator adds a private attribute that autodoc-skip-member will use to skip the member. So one does something like this:
```
@skip_api_doc
def load_tests(...):
...
```
With the current PR, if one actually wants to document a function called `load_tests`, they are going to have a harder time figuring out why it is not visible on the API documentation...
On the other hand, this might well be an overkill. Just an idea.
=> Skip load_tests in API documentation

traitsui/testing/api.py, traitsui/testing/tester/_ui_tester_registry/_traitsui_ui.py, traitsui/testing/tester/_ui_tester_registry/default_registry.py, traitsui/testing/tester/_ui_tester_registry/qt4/_interaction_helpers.py, traitsui/testing/tester/_ui_tester_registry/qt4/_registry_helper.py, traitsui/testing/tester/_ui_tester_registry/qt4/default_registry.py, traitsui/testing/tester/_ui_tester_registry/wx/_interaction_helpers.py, traitsui/testing/tester/_ui_tester_registry/wx/_registry_helper.py, traitsui/testing/tester/_ui_tester_registry/wx/default_registry.py, traitsui/testing/tests/test_api.py
This PR adds simple import tests for the `traitsui.testing.api`.  I broke the tests up into sections to try to make it easier to ensure the test is up to date with the api moving forward.  
In doing so I also thought it would make sense to reorganize the ordering of the groups of imports in the api module to match the docstring (and have the tests be written in the same order).  In doing so I realized that this actually caused some tests to fail as importing UITester ultimately led to trying to import things from `traitsui.testing.api` whose imports happened after UI Tester.  To avoid this, I simply had those problem cases not import from the api.  (I'm not sure if this was the correct approach, but I thought it made sense).
=> Add a test for traitsui.testing.api

traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/boolean_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/button_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/check_list_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/editor_factory.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/enum_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/instance_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/list_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/range_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/text_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/ui_base.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/boolean_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/button_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/check_list_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/editor_factory.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/enum_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/instance_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/list_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/range_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/text_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/ui_base.py
This PR replaces imports from `traitsui.testing.api` in internal non-test code.  This is to avoid potential circular dependencies.  See comment here: https://github.com/enthought/traitsui/pull/1370#discussion_r506176635
=> Don't import from traitsui.testing.api in internal editor implementations

setup.py
This Pr contains 2 commits (Dont squash merge!) to set the `PRERELEASE` to rc2 and flip `IS_RELEASED`.
=> Release candidate 7.1.0rc2

traitsui/examples/demo/Advanced/Auto_update_TabularEditor_demo.py, traitsui/examples/demo/Advanced/Dynamic_EnumEditor_demo.py, traitsui/examples/demo/Advanced/Dynamic_range_trait_and_editor.py, traitsui/examples/demo/Advanced/Popup_Dialog_demo.py, traitsui/examples/demo/Advanced/Tabular_editor_demo.py, traitsui/examples/demo/Standard_Editors/File_Dialog/File_Open_with_ImageInfo_Extension.py, traitsui/examples/demo/Standard_Editors/File_Dialog/File_Open_with_TextInfo_Extension.py, traitsui/examples/demo/Standard_Editors/SetEditor_demo.py, traitsui/examples/demo/Standard_Editors/TreeEditor_demo.py
fixes #1126 
This PR fixes issues that arise when parsing the demo module docstrings - displayed in the etsdemo application.
=> Address warnings when parsing demo docstrings

traitsui/qt4/helper.py
Closes https://github.com/enthought/traitsui/issues/1364
On OSX, the clickable area of the icon button is too small: you have to click dead center with a few pixel accuracy to actually click the button. This explains why sometimes the dialog can be launched and sometimes it cannot.
This issue affects the simple FileEditor, RangeEditor (the buttons for incrementing and decrementing the value), and the ListEditor (the button for opening a menu for adding or removing an item).
This PR fixes the issue by reimplementing the sizeHint of the `IconButton` (inheriting QPushButton) to return a larger size and remove the `setMaximumSize` line which set the button size to be too small.  The sizeHint implemented here follows a logic similar to that of `QToolButton` (see source …
=> Fix Qt IconButton with a clickable area too small

traitsui/__init__.py
fixes #1355 
Note that pyface 7.1.0 is not yet released, but I opened this PR in anticipation of that.  (It may be too early to do this in which case I will simply close this PR and open a new PR at the appropriate time)  
This PR simply bumps the version number for pyface in `__requires__` in `__init__.py` to 7.1.0.
=> Update __init__.py to depend on Pyface >= 7.1.0 

CHANGES.txt, traitsui/__init__.py
This PR brings the only two changes that need to be brought back to master:
- Changelog
- Update to install requirement to depend on pyface>=7.1.0
(Note: It is also valid to update install requirement on master first instead of the other way round.)
Closes #1355
=> Update changelog and requirements from 7.1 back to master

traitsui/testing/tester/tests/test_ui_wrapper.py
In this specific case, there was nothing that needed to be formatted in the string so we can just use a normal string.
This was reported as a flake8 failure in the CI job - https://travis-ci.org/github/enthought/traitsui/jobs/738921895, PR #1392 .
=> Remove unnecessary use of f-string.

ci-src-requirements.txt, etstool.py
fixes #1382 
This PR updates CI/etstool to install pyface using edm instead of installing it from git source.
=> Dont install pyface from git source

etstool.py
Currently, `python -m etstool --help` works for getting help but `python -m etstool -h` does not. This breaks user expectations when working with a command line application. This PR makes `-h` work as expected.
(For @achabotl )
=> Support -h for getting help

traitsui/qt4/tests/test_ui_base.py, traitsui/qt4/ui_base.py
Fixes https://github.com/enthought/pyface/issues/802
This is an alternative fix to https://github.com/enthought/traitsui/issues/1078, i.e. it overrides https://github.com/enthought/traitsui/pull/1083 partially.
This PR:
- Change the Qt StickyDialog window flag from `Dialog` to `Window`. The StickyDialog is the main widget used when `configure_traits` or `edit_traits` are called with default settings.
With this, the only difference compared to TraitsUI 7.0.1 is that when `resizable` is false, the window flag is `Qt.Window | QtCore.Qt.WindowSystemMenuHint` instead of `Qt.Dialog | QtCore.Qt.WindowSystemMenuHint`. Before this change, the dialog may not have minimize/maximize buttons in some window managers.
In this part of the code base, there is in fact no information as to whether the …
=> Change Dialog flag to Window to allow minimize/maximize buttons to be shown

traitsui/qt4/tests/test_ui_panel.py, traitsui/qt4/ui_panel.py
Fixes #1403 
This only attempts to add scrolling to vertical, horizontal and grid groups, as it doesn't make sense for tabbed, split or vfold groups.
Currently no tests: I could hack one together, but it would be good to know if this can be integrated into the new testing framework easily.
=> Enable the scrollable trait of a Group in the Qt backend

.github/workflows/minimal-deps.yml, appveyor.yml
Part of #1416
This PR removes part of the test matrix on Appveyor, which has been the bottleneck of per-PR CI build.
We do lose one test job from this change. The (allow-to-fail) job with wxPython and OSX is now gone.
The other removed jobs are now covered on GitHub Actions.
The setup on OSX with wxPython has not been successful as I ran into this issue: https://stackoverflow.com/questions/48531006/wxpython-this-program-needs-access-to-the-screen 
On the other hand, TraitsUI test suite for wxPython + OSX has been failing.
=> Reduce CI matrix on Appveyor

LICENSE.txt
This PR removes information about the non-existent `traits/protocols` directory from the main license file.
=> Remove info about non-existent pyprotocols

.github/actions/apt-get-qt-deps/README.md, .github/actions/apt-get-qt-deps/action.yml, .github/workflows/bleeding-edge.yml, .github/workflows/integration-tests.yml, .github/workflows/minimal-deps.yml, .github/workflows/style-checks.yml, .github/workflows/test-with-pip.yml, .github/workflows/traits-6-compat.yml, CHANGES.txt, appveyor.yml, etstool.py, setup.cfg, traitsui/__init__.py, traitsui/qt4/helper.py, traitsui/qt4/tests/test_ui_base.py, traitsui/qt4/tests/test_ui_panel.py, traitsui/qt4/ui_base.py, traitsui/qt4/ui_panel.py, traitsui/testing/tester/tests/test_ui_wrapper.py
This PR backports bug fixes for 7.1 series in preparation for #1419
This also backports the changes to CI setup: it replaces some of Appveyor test matrix with GitHub actions, in an effort to speed up the release process. 
The changelog is updated, that is the only one change that is not previously reviewed.
=> Backport fixes to 7.1

CHANGES.txt
[Targeting maint/7.1]
When I build the documentation, I realize that the section title "Bugfix release" in the changelog is really an odd one out. This PR fixes the title to be more consistent.
=> Fix changelog section title for consistency

setup.py
Targeting `maint/7.1`
This PR bumps the release version and flip the IS_RELEASE flag for the development of the next bug fix release.
(For #1419)
=> Bump release version for the development of 7.1.2

.travis.yml, etstool.py
This is motivated by the difficulties in fixing the cron job on Travis CI (see attempts in #1427 and #1395). By removing the dependency requirement given to EDM for pulling Traits 6.0, we would be able to fix the cron job on Travis more easily.
A job has been added on GitHub Actions for testing against Traits 6.0 (see #1415), so we are still testing against Traits 6.0.  However note that to conserve resources, the job on GitHub Actions is currently scheduled to be run per week, rather than per-PR.  We can change that event trigger setting too.
=> Remove job on Travis for testing against Traits 6.0

etstool.py
The cron job on Travis is currently failing with this:
```
======================================================================
ERROR: traitsui.testing.tests.test_gui (unittest.loader._FailedTest)
ImportError: Failed to import test module: traitsui.testing.tests.test_gui
File "/home/travis/.edm/envs/traitsui-test-3.6-null/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
module = self._get_module_from_name(name)
File "/home/travis/.edm/envs/traitsui-test-3.6-null/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
__import__(name)
File "/home/travis/.edm/envs/traitsui-test-3.6-null/lib/python3.6/site-packages/traitsui/testing/tests/test_gui.py", line …
```
=> Fix cron job not installing additional dependencies

traitsui/examples/demo/Applications/Python_source_browser.py, traitsui/examples/demo/Extras/Image_editor_demo.py, traitsui/examples/demo/Extras/tests/test_Image_editor_demo.py
fixes #1432 
This PR changes the search path the be the correct path to the directory that contains the image folder containing the images of interest.
=> Use correct source_path in example

etstool.py, setup.py
Closes #1435
This PR removes Python 3.5 from etstool.py (it is not used by CI), and most importantly, updated setup.py so that package installer will no longer pick up the next release in a Python <=3.5 environment.
=> Drop Python 3.5 support in TraitsUI

ets-demo/setup.py
Similar to #1436 but for etsdemo.
etsdemo is an application and is a separate distribution, but in any case, we have not tested the application with Python 3.5 or lower.
=> Declare Python 3.5 not supported for ets-demo

docs/source/conf.py
Using this extension means that API docs now link to source code. See example below which now includes the `source` button.
=> Use viewcode sphinx extension

ets-demo/etsdemo/app.py
This PR updates the etsdemo application such that clicking on links in the description will be opened in the default browser instead of in the html editor itself. This behavior was observed in #1445 and was recommended as the right user experience - https://github.com/enthought/traitsui/pull/1445#issuecomment-746182226
=> Open links externally instead of in the html editor in etsdemo application

traitsui/qt4/html_editor.py, traitsui/tests/editors/test_html_editor.py
This is a fix for the issue with open_externally with the `QtWebEngine` version of `QWebView`.
Basic unit test which validates that open_externally behaves as expected assuming that Qt does what it says it should.
Currently raises two warnings in tests:
```
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
```
~However this seems like something that is a problem at the Pyface level.  If this PR is approved I will open an issue for these warnings in TraitsUI and we can track down what this means later.~ It looks like enthought/pyface#853 fixes this.
See #1449 and #1450 
Fixes #1448 and …
=> Support HTMLEditor.open_externally on QtWebEngine

ets-demo/etsdemo/app.py
This adds an alternative group in demo file view for when demo is None.
Unfortunately we can't just hide the "Demo" tab, because dynamic hiding doesn't work.
This should essentially fix #1454
=> Hide demo tab when the demo is None

traitsui/tests/editors/test_html_editor.py
Motivated by #1464, this PR extends the tests for testing how the HTMLEditor opens `<a>` links with/without `target` set, along with the `open_externally` flag.
The tests rely on Qt webkit/webengine being able render CSS so that the link can fill up the entire page and the tests can simply click anywhere to trigger the link.
Only test code is changed. Two of the tests are effectively tests with "expected failures" to illustrate the issue described in #1464.
Note the draft implementation in https://github.com/enthought/traitsui/issues/1464#issuecomment-754662151 requires the existing test be modified as the slot to `linkClicked` (WebKit only) is removed there. The draft implementation passes the new tests (after replacing expected failures with expected successes).
=> Refactor and extend tests for Qt HTMLEditor handling of opening links

ets-demo/etstool.py
This PR makes `-h` an alias to `--help` in the etstool module in ets-demo distribution.
=> Add help aliases to etsdemo etstool module

ets-demo/etstool.py, etstool.py, setup.cfg, traitsui/tests/test_actions.py
This PR includes the `flake8_ets` package in the environment. Note that this PR also excludes the `examples` folder from copyright header violations.
=> Include flake8_ets plugin when running flake8 on codebase.

traitsui/editors/api.py
This PR adds a sentence to the API documentation of `traitsui.editors.api` to refer users to `traitsui.api` instead. `traitsui.editors.api` is NOT being deprecated. Since `traitsui.editors.api` is merely a subset of `traitsui.api`, this simply clarifies the relationship and recommendation.
=> Doc: Clarify which of traitsui.api and traitsui.editors.api is recommended

traitsui/testing/__init__.py, traitsui/testing/api.py
This PR updates the API documentation for `traitsui.testing.api` and `traitsui.testing` to remove clauses that deviate from the convention of backward compatibility guarantee in PEP8.
These clauses were added following the suggestion in https://github.com/enthought/traits/issues/1213 and similar changes in Traits-Futures. The idea that things outside of the `api` module don't get backward compatibility guarantee has really got into my head, but over time, I find it confusing as a developer working with this convention, because it differs from the one followed by the wider Python community. As a result, I would change code that break backward compatibility for PEP8-public components because this alternative convention allows me to do that, but then those changes may have to be reverted …
=> Remove clause that deviates from PEP8 backward compatibility convention in the testing package

traitsui/testing/tester/tests/test_ui_tester.py, traitsui/testing/tester/ui_tester.py
Following up observation from refactoring the documentation: The `auto_process_events` flag is only exposed from the object `__init__` method, making it difficult to cross reference in sphinx (there exists sphinx extensions for that, but we may not want to depend on them).
The flag is an internal state of `UITester` not allowed to be mutated post instantiation. The immutability is important in my opinion because if it was allowed to mutate, one may expect this value to be observed by `UIWrapper` created prior to the mutation. Any attempt to "fix" that is going to add complexity. It is not necessary to mutate the flag, because one can simply create another `UITester` in the same test.
By exposing the attribute as a readonly property, this allows space in the API documentation to describe …
=> Better document auto_process_events

docs/source/traitsui_dev_guide/testing.rst
The cross reference to the section explaining the testing terminology has been renamed, this PR fixes one lingering reference to the old name.
=> Fix a cross reference to a section in documentation after refactoring

docs/source/conf.py
Closes #1484
This is before, these buttons are shown at the very top of the page. The first button actually links to the home page. :
This is after this PR:
=> Fix link label to the documentation home page

ets-demo/etstool.py
Currently Travis CI setup install etsdemo for the wx toolkit (because it is otherwise to break it out in a single config file), but the install step fails at the point of installing `wxPython`. We still expect tests to fail/error for the wx toolkit for the etsdemo application though.
This is a quick fix to get CI to at least run the tests. We need a better solution to replace this hardcoded ubuntu version in the install command.
(Note that this PR is independent of TraitsUI, but the CI between TraitsUI and etsdemo are tied.)
=> Fix link for installing wxPython on CI (for etsdemo)

docs/source/conf.py, traitsui/editor.py, traitsui/qt4/editor.py, traitsui/tests/test_editor.py, traitsui/wx/editor.py
This is a refactor/cleanup that does a number of things:
- makes the tooltip methods a formal part of the base `Editor` interface.  Previously these were supplied by the base toolkit implementations of the Editor classes, so they were there but not documented.
- moves out the logic for finding the tooltip text into its own method (which could be overridden if needed)
- moves out the toolkit-specific code into its own abstract method and making `set_tooltip` a method on the base `Editor` class, removing all duplicated code
- adds tests
There are strategic code-generation reasons why I want this done, but hopefully it is useful enough to stand as a clean-up action.
=> Formal editor interface for tooltips

traitsui/api.py
closes #1494 
This PR simply adds instance choice related classes to the `traitsui.api`
=> Add instance choice classes to traitsui.api

traitsui/qt4/instance_editor.py
Fixes #1475.
Not sure how to test this apart from a manual check.
=> Qt InstanceEditor button should never be the default

integrationtests/styled_date_editor_test.py, traitsui/editors/image_enum_editor.py, traitsui/editors/table_editor.py, traitsui/examples/demo/Advanced/Dynamic_range_trait_and_editor.py, traitsui/examples/demo/Advanced/String_list_ui_editor.py, traitsui/extras/saving.py, traitsui/key_bindings.py, traitsui/list_str_adapter.py, traitsui/qt4/code_editor.py, traitsui/qt4/datetime_editor.py, traitsui/qt4/table_editor.py, traitsui/tabular_adapter.py, traitsui/ui.py, traitsui/wx/code_editor.py, traitsui/wx/file_editor.py, traitsui/wx/history_editor.py, traitsui/wx/scrubber_editor.py, traitsui/wx/table_model.py
contributes to #1052 
This PR replaces all uses of `@on_trait_change` with the equivalent form using observe
=> Convert on_trait_change decorators to observe

traitsui/qt4/tree_editor.py, traitsui/wx/tree_editor.py
Part of #1502 
This PR supersedes #1518.
This PR follows the approach outlined here: https://github.com/enthought/traitsui/pull/1518#issuecomment-776682726
=> Refactor TreeEditor _new_actions and _menu_new_node to avoid hacky eval

traitsui/editors/text_editor.py, traitsui/qt4/text_editor.py, traitsui/tests/editors/test_text_editor.py
fixes #1514 
This PR adds a `clear_button` boolean trait on the `TextEditor` `ToolkitEditorFactory`, and uses it to call `setClearButtonEnable` if we are working with a `QLineEdit` on qt>=5.2.  It also adds a simple test to check it gets enabled as expected, and I separately modified the `TextEditor_demo.py` to confirm the changes worked as expected (changes not included in this PR).
I have only just started looking into the scope of adding something similar for wx / for a QTextEdit (used for the custom style of the `TextEditor`). For now, just adding the functionality for `QLineEdit`s on qt>=5.2 is only a couple line change.
=> Expose `clearButtonEnabled` for Qt TextEditor

traitsui/editors/shell_editor.py, traitsui/qt4/button_editor.py, traitsui/qt4/enum_editor.py, traitsui/qt4/instance_editor.py, traitsui/qt4/list_str_editor.py
contributes to #1052 
This PR updates a few editors to use dynamic `observe` instead of `on_trait_change`. More similar PRs to follow
=> Dynamic otc to observe1

traitsui/qt4/ui_base.py, traitsui/qt4/ui_live.py, traitsui/qt4/ui_modal.py, traitsui/qt4/ui_panel.py, traitsui/ui.py, traitsui/wx/ui_base.py, traitsui/wx/ui_live.py, traitsui/wx/ui_modal.py, traitsui/wx/ui_panel.py
contributes to #1052
This PR updates a few files to use dynamic `observe` instead of `on_trait_change`. More similar PRs to follow
=> Dynamic otc to observe 2

traitsui/wx/code_editor.py
fixes #1535 
Ref https://wxpython.org/Phoenix/docs/html/wx.stc.StyledTextCtrl.html#wx.stc.StyledTextCtrl.StartStyling
=> StartStyling API changed for new Wx version

traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/instance_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/instance_editor.py, traitsui/tests/editors/test_instance_editor.py, traitsui/ui.py
fixes #1501 
This is a couple line change which simply adds a listener to a UI's errors trait.  Whenever the errors change, this change is propagated up to the UI's parent's errors trait as well.
BEWARE: although this seems like the logical thing to do it is a change in behavior and we may risk breaking code that was dependent upon the parent UI not picking up on child UI errors for whatever reason.  
The scope of this changes impact should be investigated before merging
NOTE: I merged #1499 into this PR as I found myself wanting to write basically the same thing to write new tests. If changes are made to that PR we will want to pull those in here as well
=> Propagate UI errors to the UI's parent

traitsui/examples/demo/Advanced/Tree_editor_required_traits_demo.py, traitsui/qt4/tree_editor.py, traitsui/tree_node.py, traitsui/wx/tree_editor.py
closes #1502 
This is part 2 from this comment: https://github.com/enthought/traitsui/pull/1518#issuecomment-776682726 which follows up the changes made in #1524.
Previously there was already a _secret_ part of the `TreeNode` api in which users could pass in a 2-tuple as an element in the list supplied for the `add` trait of a `TreeNode`.  The first element of the tuple would be used as the klass to be added, and the second was a `prompt` boolean, which when true would call `edit_traits` on the new object before fully adding it to the tree to prompt the user to change traits if they want to.  I did not see this actually documented anywhere, but from the code I believe that was the idea (and testing locally that is what happens).
In this PR I simply extend that secret api to now also …
=> Extend / document secret TreeNode api for passing tuples into `add` list trait

traitsui/key_bindings.py
In #1519 there was a typo that went unnoticed. The tests all still passed but in the test suite one could see the error
```
Exception occurred in traits notification handler for event object: TraitChangeEvent(object=<traitsui.key_bindings.KeyBindings object at 0x7f9344a73048>, name='children', old=[<traitsui.key_bindings.KeyBindings object at 0x7f935c6c6ca8>], new=[])
File "/Users/aayres/Desktop/traits/traits/observation/_trait_event_notifier.py", line 122, in __call__
self.dispatcher(handler, event)
File "/Users/aayres/Desktop/traits/traits/observation/observe.py", line 26, in dispatch_same
handler(event)
File "/Users/aayres/Desktop/traitsui/traitsui/key_bindings.py", line 267, in _children_modified
for item in event.added:
AttributeError: …
```
=> fix a typo from on_trait_change to observe migration

traitsui/testing/tester/_abstract_target_registry.py, traitsui/testing/tester/_base_dynamic_registry.py, traitsui/testing/tester/_dynamic_target_registry.py, traitsui/testing/tester/_ui_tester_registry/default_registry.py, traitsui/testing/tester/_ui_tester_registry/qt4/_control_widget_registry.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/button_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/ui_base.py, traitsui/testing/tester/_ui_tester_registry/qt4/default_registry.py, traitsui/testing/tester/_ui_tester_registry/qt4/tests/test_control_widget_registry.py, traitsui/testing/tester/_ui_tester_registry/tests/test_default_registry.py, traitsui/testing/tester/_ui_tester_registry/wx/_control_widget_registry.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/button_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/ui_base.py, traitsui/testing/tester/_ui_tester_registry/wx/default_registry.py, traitsui/testing/tester/_ui_tester_registry/wx/tests/test_control_widget_registry.py, traitsui/testing/tester/target_registry.py, traitsui/testing/tester/tests/test_registry.py, traitsui/testing/tester/tests/test_ui_wrapper.py, traitsui/testing/tester/ui_tester.py, traitsui/testing/tester/ui_wrapper.py, traitsui/tests/editors/test_enum_editor.py
This is a draft PR to show implementations and API that would solve #1418.
Narrow goal:
- Allow alternative registries to be written in order to support testing `IsEnabled` check on any QWidget or wx.Window
Wider goal:
- Allow more flexibility in extending of the testing API
Changes:
- All the `get_*` methods on the current `TargetRegistry` are extracted to an interface, `AbstractTargetRegistry`. Any objects that implement the interface can be a registry given to `UIWrapper`.
- Some of the arguments in the `get_*` methods that used to require the type of `UIWrapper._target` is now changed to just an instance. While this adds requirements on the information required by a registry, `UIWrapper._target` is always an instance so that information is almost always available.
- A …
=> Extract an interface from TargetRegistry to allow wider testing support for IsEnabled

etstool.py, traitsui/qt4/editor.py, traitsui/tests/test_editor.py
fixes #1543
Note I am observing a segfault when I set the slider to 0 in the example given in the issue and then close the information dialog (this occurs both with and without the changes of this PR)
Im not sure why we weren't previously using `information` from the `pyface.api` here (see: https://github.com/enthought/pyface/blob/65813858730a61f25618e98669bcc5347d44935a/pyface/message_dialog.py#L15-L43)
In any case, now in order to call `setTextFormat` we would not be ably to use pyface directly anyway / we can no longer call the static function `QtGui.QMessageBox.information`.
This is what I currently see if I set the slider to 0.0:
As opposed to this from before:
I am unsure why 2 dialogs show up (this is probably a separate bug?)
A test for this would likely require UITester + …
=> manually set the text format to plain text in error

traitsui/tests/test_editor.py
_Hopefully_ fixes #1551 
The intermittent test failure first appeared in pr #1546, and after my realization on #1540 I am suspect of `auto_process_events` on UITester being relevant here as well (although this is still more of a hunch than a well understood solution).  This PR sets auto_process_events=False (the test still runs as expected with ModalDialogTester taking the full event processing responsibility, so even if this was not the cause of 1551 this change is still viable).
In addition, looking back at the test from 1546 and looking more closely at the code in ModalDialogTester, I realize that the `text` arg in `has_widget` corresponds to the text the widget holds which is the same value regardless of the format (it was not corresponding to the text actually displayed by the …
=> Update new test_editor_error_msg

docs/source/traitsui_user_manual/advanced_view.rst, docs/source/traitsui_user_manual/view.rst, traitsui/group.py, traitsui/item.py, traitsui/menu.py
closes #833 
This PR adds to the trait definition comments for `enabled_when` / `visible_when` to comment on some common points of confusion.  It also mentions in the view context section of the docs the HasTraits `trait_context` method to override the default context.
=> Document enabled_when / visible_when better

traitsui/null/rgb_color_trait.py, traitsui/qt4/rgb_color_trait.py, traitsui/tests/test_toolkit_traits.py
fixes #1531
This PR simply replaces `/` with `//` to avoid trying to `&` a float with an int.  Note the wx version already had this.  It also adds a very simple regression test
Note that as mentioned https://github.com/enthought/traitsui/issues/1531#issuecomment-790573071 this function is effectively copied 3 separate times and we will ultimately want to unify them in one place.  However, the wx version has an additional check for `wx.Colour` inputs, so they are not exactly the same.  This very simple PR fixes the bug, the architecture / code organization issue can be addressed separately.
=> Fix RGBColor hex int to tuple color conversion

docs/source/traitsui_user_manual/factories_basic.rst, traitsui/editors/file_editor.py, traitsui/wx/file_editor.py
closes #1530 
Although we may want to have another issue open for adding qt support
This PR simply aims to better document the fact that the `entries` parameter for keeping a history of past entries on the FileEditor (and subsequently the DirectoryEditor) is only supported on the wx backend, but not on qt.  
In addition, this PR makes a fix (similar to the one made in #1067) to fix the `History_demo.py` on wx.  Now if one runs the demo in an environment with wx they can see what the history functionality is actually capable of.
=> Document `entries` parameter not supported qt for FileEditor/DirectoryEditor

traitsui/qt4/tests/test_ui_panel.py, traitsui/qt4/ui_panel.py, traitsui/tests/test_ui_panel.py, traitsui/wx/ui_panel.py
fixes #1538 
Previously we were using the html module from the python standard library in a function, as well as defining a local variable `html` that held on to the html content to be used to create an `HTMLHelpWindow` instance.  This PR adds a very simple test to showcase the bug, and fixes it by giving the `html` variable a new name `html_content`.   Additionally, I changed the import statement to only import what we need from `html`.  Namely, `from html import escape`.  Either of these fixes would work alone (it may be overkill to do them both), but I figured it couldn't hurt.
=> Don't use html for a variable name when using html module from standard library

traitsui/qt4/ui_panel.py
ref: https://github.com/enthought/traitsui/pull/1544#issuecomment-804545226
=> Refactor _add_items method of _GroupPanel object

docs/source/traitsui_user_manual/testing/references/examples.rst, traitsui/examples/demo/Standard_Editors/FileEditor_demo.py, traitsui/examples/demo/Standard_Editors/tests/test_FileEditor_demo.py, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/file_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/default_registry.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/file_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/default_registry.py, traitsui/tests/editors/test_file_editor.py
This PR adds testing support for the simple FileEditor via its text widget.
- `DisplayedText`, `KeyClick`, `KeySequence` can now be used for testing with a simple FileEditor
- A test for the FileEditor demo example is added, and an entry is added to the documentation.
This is motivated by an observation of a similar extension being made in a downstream project. One will extend using the `_file_name` attribute on the editor, acknowledging that such extension relies on implementation details of the editor. If the testing support is implemented in traitsui, then the support can be maintained along with those implementation details.
In the context of testing an application, it is often sufficient to set a file path via the text widget instead of via the file modal dialog.
This goes some way …
=> Support testing with simple FileEditor (without dialog)

.github/workflows/test-etsdemo.yml, ets-demo/etsdemo/info.py, ets-demo/etstool.py
This PR simply sets default to true in the eam metadata so that one can run the application from the command line through edm
=> Add 'default': True to the eam metadata

ets-demo/etsdemo/app.py, examples/tutorials/traitsui_4.0/buttons.py, examples/tutorials/traitsui_4.0/items.py, integrationtests/ui/text_editor_invalid.py, traitsui/dock_window_theme.py, traitsui/examples/demo/Advanced/Dynamic_range_trait_and_editor.py, traitsui/examples/demo/Advanced/Property_List_demo.py, traitsui/examples/demo/Advanced/Settable_cached_property.py, traitsui/examples/demo/Advanced/Statusbar_demo.py, traitsui/examples/demo/Advanced/Tabular_editor_demo.py, traitsui/examples/demo/Applications/converter.py, traitsui/examples/demo/Standard_Editors/CSVListEditor_demo.py, traitsui/examples/demo/Standard_Editors/File_Dialog/File_Open_with_Custom_Extension.py, traitsui/examples/demo/Standard_Editors/TitleEditor_demo.py, traitsui/extras/_demo_legacy.py, traitsui/file_dialog.py, traitsui/group.py, traitsui/key_bindings.py, traitsui/qt4/table_editor.py, traitsui/tabular_adapter.py, traitsui/tests/test_ui.py, traitsui/theme.py, traitsui/tree_node.py, traitsui/ui.py
This PR replaces the use of `depends_on` metadata on Traits Properties with the use of `observe` metadata. Contributes towards #1052
=> Replace use of depends_on in Traits Properties with observe

traitsui/editor.py, traitsui/editors/range_editor.py, traitsui/group.py, traitsui/handler.py, traitsui/include.py, traitsui/qt4/list_str_editor.py
This PR first fixes and then removes arguments from the `super` calls in various traitsui objects.
=> Fix "super" calls in potentially buggy cases

traitsui/wx/button_editor.py, traitsui/wx/check_list_editor.py, traitsui/wx/color_editor.py, traitsui/wx/compound_editor.py, traitsui/wx/date_editor.py, traitsui/wx/dnd_editor.py, traitsui/wx/drop_editor.py, traitsui/wx/editor.py, traitsui/wx/enum_editor.py, traitsui/wx/file_editor.py, traitsui/wx/font_editor.py, traitsui/wx/helper.py, traitsui/wx/history_editor.py, traitsui/wx/image_enum_editor.py, traitsui/wx/instance_editor.py, traitsui/wx/key_binding_editor.py, traitsui/wx/list_editor.py, traitsui/wx/list_str_editor.py, traitsui/wx/range_editor.py, traitsui/wx/rgb_color_editor.py, traitsui/wx/scrubber_editor.py, traitsui/wx/set_editor.py, traitsui/wx/table_editor.py, traitsui/wx/table_model.py, traitsui/wx/tabular_editor.py, traitsui/wx/text_editor.py, traitsui/wx/ui_live.py, traitsui/wx/ui_window.py, traitsui/wx/view_application.py
This PR updates the `super` usage in classes in `traitsui.wx` submodule. The update was done using automated regex-based search and replace. After the changes were made, each changes was individually checked to ensure that we were calling super with the right arguments before.
Ref https://github.com/enthought/traits/pull/1280. Also see related #1587
=> Update "super" usage in "traitsui.wx"

traitsui/editors/array_editor.py, traitsui/editors/button_editor.py, traitsui/editors/enum_editor.py, traitsui/editors/file_editor.py, traitsui/editors/list_editor.py, traitsui/editors/text_editor.py, traitsui/editors/tree_editor.py
closes #1585 
This PR simply replaces comments using # with #: so that the traits get documented by the autogenerated api docs.
=> replace # with #: to document traits in traitsui.editors.*

traitsui/qt4/check_list_editor.py, traitsui/qt4/enum_editor.py, traitsui/wx/check_list_editor.py, traitsui/wx/enum_editor.py
`str.capitalize('abc')` is the same as `'abc'.capitalize()`
closes #768 
these changes were introduced in https://github.com/enthought/traitsui/pull/234
Note that the original issue was planned for traitsui 7.1.0. Ref https://github.com/enthought/traitsui/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Release+7.1%22
=> Use "str.capitalize" directly instead of an alias

traitsui/examples/demo/Advanced/Property_List_demo.py, traitsui/examples/demo/Advanced/Statusbar_demo.py
fixes #1576
This PR updates the use of the deprecated `threading.Thread.setDaemon` to just use `threading.Thread.daemon`.
=> Update use of deprecated "Thread.setDaemon"

traitsui/api.py
fixes #1396
This PR re-exports `triatsui.toolkit.toolkit_object` via `traitsui.api`.
=> Adds "traitsui.toolkit.toolkit_object" to "traitsui.api"

traitsui/__init__.py, traitsui/helper.py, traitsui/ui_traits.py, traitsui/view.py
This PR relies on `traits.api` directly for `PrefixList` instead of relying on a compatibility layer to support traits 6.0. We bump the traits dependency to `>=6.1`. Note that we would have relied on `>=6.1` anyway because of the on triat change -> observe changes.
Note that the compat layer was introduced in https://github.com/enthought/traitsui/pull/1053/ and fixes #1296
Note that the original issue was planned for traitsui 7.1.0. Ref https://github.com/enthought/traitsui/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Release+7.1%22
=> Use "PrefixList" from traits >= 6.1

traitsui/qt4/toolkit.py
This PR removes a conditional that handled support for PyQt version < 4.3.2 - and thereby officially removes support for this version. I'm reasonably sure that no one was using such an old version of PyQt (the latest is 4.12.1 and the only other available version on python 3 for pyqt4 is 4.11.4).
=> Drop support for PyQt < 4.3.2

traitsui/toolkit_traits.py
This PR makes a very trivial/simple change - it imports `TraitFactory` from `traits.api` instead of `traits.trait_factory`. This was fixed in traits in https://github.com/enthought/traits/pull/730/ and has been available in traits since v 6.0.0.
=> Import "TraitFactory" from "traits.api"

traitsui/wx/tabular_editor.py
fixes #1411
This PR replaces the deprecated `wx.ListItemAttr` with the recommended `wx.ItemAttr`. This has been verified by running the traits-futures example which is how we originally discovered the issue.
=> Replace deprecated "wx.ListItemAttr" with "wx.ItemAttr"

traitsui/editors/array_editor.py, traitsui/editors/boolean_editor.py, traitsui/editors/button_editor.py, traitsui/editors/check_list_editor.py, traitsui/editors/code_editor.py, traitsui/editors/compound_editor.py, traitsui/editors/custom_editor.py, traitsui/editors/date_range_editor.py, traitsui/editors/directory_editor.py, traitsui/editors/dnd_editor.py, traitsui/editors/drop_editor.py, traitsui/editors/enum_editor.py, traitsui/editors/file_editor.py, traitsui/editors/image_enum_editor.py, traitsui/editors/instance_editor.py, traitsui/editors/list_editor.py, traitsui/editors/progress_editor.py, traitsui/editors/range_editor.py, traitsui/editors/set_editor.py, traitsui/editors/shell_editor.py, traitsui/editors/styled_date_editor.py, traitsui/editors/table_editor.py, traitsui/editors/text_editor.py, traitsui/editors/title_editor.py, traitsui/editors/tree_editor.py, traitsui/editors/tuple_editor.py, traitsui/editors/value_editor.py
This PR swaps the editor names with the new alias `ToolkitEditorFactory` e.g. `ArrayEditor` is the class name now and `ToolkitEditorFactory` is now the alias. Note that this PR doesn't address all of the uses of `ToolkitEditorFactory` as the class name. There are all of the trivial changes and i'll open a separate PR to address the non-trivial changes.
addresses a part of #1586
=> Rename editor factory classes

traitsui/tests/editors/test_range_editor_spinner.py, traitsui/wx/range_editor.py
At the moment, we only support the latest versions of WxPython (4.x) so this PR removes the code which was explicitly handling these old/outdated versions.
=> Remove code handling old/outdated versions of wx

traitsui/tests/editors/test_enum_editor.py
fixes #545
This PR unskips `EnumEditor` tests that were failing earlier on windows.
=> Unskip "EnumEditor" tests that were failing earlier on windows

traitsui/item.py
fixes #71 . See also related closed issue #343.
This PR removes the unused `Item.full_size` trait. The trait was meant for use in an unimplemented feature/enhancement.
=> Remove unused "Item.full_size" trait

traitsui/editors/video_editor.py, traitsui/examples/demo/Standard_Editors/VideoEditor_demo.py, traitsui/qt4/video_editor.py, traitsui/tests/editors/test_video_editor.py
Follow up to PR #745 that adds the ability to control the [notify interval](https://doc.qt.io/qt-5/qmediaobject.html#notifyInterval-prop) of the media player.
When running the `VideoEditor` demo, you should see position updates occur approx every 0.5s now (previously 1s).
=> Expose notify interval in VideoEditor

traitsui/table_filter.py
Importing `EnumEditor` directly from the `traitsui.editors.enum_editor` module isnt enough because the `traitsui.editors.__init__` module imports all of the editors -like the `traitsui.editors.api` module.
So, the best fix for the moment is to simply move the `EnumEditor` into the specific method where the object is needed.
fixes #575
=> Move EnumEditor import in table_filter into the methods that need it

traitsui/qt4/list_editor.py, traitsui/tests/editors/test_list_editor.py
closes #1154 
This PR currently catches the TraitError to prevent the app from crashing.  If you run the short example given in the issue now and add a new item, you see an error dialog 
like before, but clicking ok just returns you to thee original UI, without crashing.  It also adds a regression test.
There may be other changes we want to make down the road, but this is a good first step which resolves the major problem of the issue.
=> Dont crash when failing to add item to list

traitsui/tests/editors/test_html_editor.py
#1551 
Has been coming up more frequently it seems lately.  This PR will not change that, but seeing the failure made me notice we were not using UI Tester on the failing test, and instead were using the old `create_ui` function which now just goes through UITester itself anyway.  This PR updates two tests to use `UITester.create_ui` instead
=> use UI Tester for all tests in test_html_editor.py

traitsui/editors/shell_editor.py
closes #1612 and closes #1620
This PR simply takes the easy way out of reverting the `on_trait_change` to `observe` changes made to `ShellEditor` in #1523 
I aim to open a separate PR that fixes the use of `observe`.  This PR should be seen as a back up plan to avoid the issues in case there is trouble coming to the real solution and we don't want to hold up the release.
Note the migration from `on_trait_change` is not yet complete and won't be by the upcoming release, so it is not as though this will be the only use of `on_trait_change` in the codebase if this PR does get merged.  
In any case I plan to try to actually fix the issue in a separate PR in which case this can simply be closed.
=> revert on_trait_change to observe changes in shell editor

traitsui/__init__.py, traitsui/qt4/video_editor.py, traitsui/tests/editors/test_video_editor.py
closes #1636
This PR does a number of things.  It moves the `import numpy as np` statement from the top of the module to inside the `__init__` method so it is only imported when needed.  It skips the video editor tests when numpy is not installed.  (both of these follow exactly was it done for the `DataFrameEditor`.  
Lastly, I added `numpy` as a test dependency in `extras_require`.  My understanding was that if I do `pip install -e .[test]` I should have all the deps needed to run _every_ test in the test suite
=> skip video editor test without numpy / move numpy import to when it is needed / list numpy as test dependency

traitsui/wx/ui_base.py
fixes #1642 
We should not have been calling an observed method manually.  Otherwise we would need to pass in a makeshift `Event` object.  Instead we can just do what we want to do directly there by calling a method directly on control
=> Fix Statusbar on Wx

docs/source/demos/index.rst, docs/source/traitsui_user_manual/factories_advanced_extra.rst, traitsui/examples/demo/Standard_Editors/VideoEditor_demo.py
This PR adds a small new "VideoEditor" section in the advanced factories page of the traitsui user docs. The section links to the traitsui demos page and the demo page has been updated to link to the new video editor demo
The video editor section includes a rather large note containing information regarding platform support for the video editor and what codecs need to be installed to get things working. Note that this advice was extracted from https://github.com/enthought/traitsui/pull/745#issuecomment-821088282. Thanks @mdsmarte for putting together this information.
fixes #1629
=> User facing docs for VideoEditor

traitsui/tests/test_ui_panel.py
closes #1648 
This PR simply skips a test if we don't have QtWebkit or QtWebEngine
This was causing the test suite to fail with pyqt5 from pypi and an error to occur (test somehow still passed in this case) with pyside2 from edm
=> skip test if no QtWebkit or QtWebEngine

traitsui/__init__.py
This was accidentally missed before the release.  With recent changes `TraitsUI` now rquires newer `Traits` and `Pyface`.
These are a result of using `Property(observe=...)` and `from pyface.undo.api import ...`
**Checklist**
=> Explicitly require traits 6.2 and pyface 7.2

CHANGES.txt, traitsui/__init__.py
Targeting [maint/7.2]
This PR backports two PRs in preparation for a quick 7.2.1 bugfix release
**Checklist**
=> Backport fix to 7.2

CHANGES.txt, traitsui/__init__.py
With pyface 7.2 there was a consistent test failure.  It appears we actually require pyface 7.3
**Checklist**
=> require pyface 7.3

CHANGES.txt, setup.py
The commit from this PR will be tagged as the 7.2.1 release.
I will open a separate PR to flip IS_RELEASED to false and bump the version after this one is merged.
**Checklist**
=> TraitsUI Release 7.2.1

setup.py
Targeting `maint/7.2`
This PR bumps the release version and flip the `IS_RELEASED` flag for the development of the next bug fix release.
**Checklist**
=> Bump release version for the development of 7.2.2

.github/workflows/test-with-edm.yml, .travis.yml, appveyor.yml, docs/releases/upcoming/1686.test.rst
part of https://github.com/enthought/ets/issues/57
This PR removes testing with pyqt4 from CI
**Checklist**
=> Dont test against PyQt4 on CI

README.rst, ets-demo/etstool.py, etstool.py
This PR removes support for the `PyQt` toolkit in the `etstool.py` helper modules - because we dont test against `PyQt` on CI any longer (ref #1686 ). Note that the `README` has also been updated to not mention `PyQt`.
**Checklist**
=> Remove support for PyQt in etstool helpers

traitsui/editors/api.py
closes #1647 
This PR simply exposes the objects mentioned on the issue in `traitsui.editors.api`
**Checklist**
=> Expose TreeEditor actions and IconSize in `traitsui.editors.api`

docs/releases/upcoming/1690.feature.rst
Given #1690 involved a change to an api module, it feels relevant to users and should get a changelog entry.  I would have tagged this as 'maintenance', but we don't have that as an option so I went with feature.
**Checklist**
=> Add news fragment for PR 1690

traitsui/qt4/helper.py, traitsui/qt4/ui_base.py, traitsui/qt4/ui_panel.py, traitsui/tests/test_splitter_prefs_restored.py
part of #1578 
This PR addresses some of the warnings mentioned when running the testsuite with python 3.8 and pyqt5.
I was having a bit of trouble resolving the `ImageEnumEditor` related warnings:
<details>
```
test_simple_editor_combobox (traitsui.tests.editors.test_image_enum_editor.TestSimpleImageEnumEditor) ... /Users/aayres/Desktop/traitsui/traitsui/qt4/image_enum_editor.py:149: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
self.setModel(model)
/Users/aayres/Desktop/traitsui/traitsui/qt4/enum_editor.py:165: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future …
```
=> Address some deprecation warnings with python 3.8 and pyqt5

docs/releases/upcoming/1674.bugfix.rst, traitsui/qt4/ui_panel.py
Part of #1673 
This PR takes the simpler quick fix approach as mentioned in this comment: https://github.com/enthought/traitsui/issues/1673#issuecomment-843282178
It is certainly worth the investigation into the alternate approach described in that comment.  This was just a very simple fix that could be done in the short term
**Checklist**
=> Call HasPrivateTraits.__init__() in GroupEditor.__init__

traitsui/editors/array_editor.py
This PR was motivated by this comment:
https://github.com/enthought/traitsui/pull/1691#pullrequestreview-688037697
specifically the second bullet.
Note that adding `print(object.dtype.type)` while running `ArrayEditor_demo.py` previously was giving `<class 'numpy.int64'>`, whereas `kind` gives `"i"` as we expect.
**Checklist**
=> Fix ArrayEditor data type check

docs/source/traitsui_user_manual/factories_basic.rst
This PR simply updates a note in the documentation as we now have screenshots using pyqt5.  Some still have the old wx screenshots though which will progressively be updated over time. 
**Checklist**
~- [ ] Add a news fragment if this PR is news-worthy for end users. (see docs/releases/README.rst)~ Too minor to warrant a news fragment
=> Update note in docs as we now have pyqt5 screenshots

docs/releases/upcoming/1684.bugfix.rst, traitsui/editors/range_editor.py, traitsui/qt4/range_editor.py, traitsui/tests/editors/test_range_editor.py, traitsui/wx/range_editor.py
closes #1650 
This PR adds support for `format_func` for the `SimpleSliderEditor` `RangeEditor`.  It does so by calling the `string_value` method defined on the factory, rather than just `self.format % _____`.  See method definition here:
https://github.com/enthought/traitsui/blob/e2521b4cf3ca882591c68ff57e795867964725ec/traitsui/editor_factory.py#L190-L208
I am just realizing while opening this that although the base `EditorFactory` class defines a `format_str` trait, the `RangeEditor` defines its own `format` trait to hold the format string instead.  I suspect this will cause problems, hence the WIP for now.  I would like to rename `format` to `format_str` but that is part of the public api... 
Perhaps I will need to redefine the `string_value` method on `RangeEditor` and have it be …
=> Add RangeEditor support for format_func

docs/releases/upcoming/1710.feature.rst, traitsui/testing/tester/_ui_tester_registry/qt4/_traitsui/directory_editor.py, traitsui/testing/tester/_ui_tester_registry/qt4/default_registry.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/directory_editor.py, traitsui/testing/tester/_ui_tester_registry/wx/default_registry.py, traitsui/tests/editors/test_directory_editor.py
Start of #1337 
This PR adds very basic UITester support for `DirectoryEditor`.  It does effectively exactly the same as what currently exists for `FileEditor`.
**Checklist**
=> UITester DirectoryEditor support

traitsui/tests/editors/test_tabular_editor.py
Part of #1533 
This PR skips the remaining tests for TabularEditor on wx (some were skipped already, see #752)
When running the test suite on master, I see 9 tests run with 3 failures and 1 error:
<details>
```
======================================================================
ERROR: test_adapter_columns_changes (traitsui.tests.editors.test_tabular_editor.TestTabularEditor)
File "/Users/aayres/Desktop/traitsui/traitsui/testing/_exception_handling.py", line 64, in reraise_exceptions
yield
File "/Users/aayres/Desktop/traitsui/traitsui/testing/tester/ui_tester.py", line 123, in create_ui
process_cascade_events()
File "/Users/aayres/Desktop/traitsui/traitsui/testing/_gui.py", line 40, …
```
=> Skip remaining tabular editor tests on wx as they are failing

.github/workflows/integration-tests.yml
We were unable to use `ubuntu-latest` earlier because it shipped with swig 4 by default and enable didnt support swig 4. But the issue got fixed in enable so we should be able to use `ubuntu-latest` now.
Fixes #1660 
Xref https://github.com/enthought/enable/issues/360
**Checklist**
=> Use ubuntu-latest instead of ubuntu-18.04

.github/workflows/test-with-pip.yml
This PR enables us to manually trigger cron job (for now, only the test-with-pip job). This is done using `workflow_dispatch`. Ref 
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
This allows us to debug the changes we are making to the configurations easily. Note that we intend to make other cron jobs manually triggerable as well - which will happen in a later PR.
**Checklist**
=> Enable manual triggering of cron job

docs/releases/upcoming/1719.bugfix.rst, traitsui/examples/demo/Advanced/Dynamic_EnumEditor_demo.py, traitsui/qt4/enum_editor.py
closes #1676 
For thee full saga see this comment:
https://github.com/enthought/traitsui/issues/1676#issuecomment-876585259
This PR fixes the example, by fixing a bug in EnumEditor itself.  In order to fully fix the issue, it also additionally updates the example to use an `Instance` rather than a `Constant` trait, since `Constant` doesn't seem to work with observe (?)
I will write up a MWE and open an issue (which can quickly be closed if this is in fact intentional).
**Checklist**
=> fix Dynamic_EnumEditor_demo.py on qt

.github/workflows/bleeding-edge.yml
This PR makes it possible to manually trigger the bleeding edge github actions - using `workflow_dispatch` like we did earlier.
One more step towards https://github.com/enthought/ets/issues/68
**Checklist**
=> Make it possible to manually trigger bleeding edge tests

docs/releases/upcoming/1721.bugfix.rst, traitsui/qt4/extra/progress_renderer.py
closes #964 by following the advice on https://forum.qt.io/topic/105375/qitemdelegate-for-drawing-progress-bar-working-but-won-t-move-off-origin
**Checklist**
=> Fix table editor with progress column

docs/releases/upcoming/1725.bugfix.rst, traitsui/qt4/instance_editor.py, traitsui/tests/editors/test_instance_editor.py
closes #1641 
For full saga see comment https://github.com/enthought/traitsui/issues/1641#issuecomment-877321165
This solution works but I am not sure when one could unhook these observers (perhaps it isn't needed?)
~I will work on adding a regression test, although this _may_ require currently not existent UI Tester support for combobox of Instance Editor, I am not sure yet~
**Checklist**
=> Fix selectable InstanceEditor combobox updates

.github/workflows/bleeding-edge.yml, .github/workflows/integration-tests.yml, .github/workflows/test-with-pip.yml
One step towards https://github.com/enthought/ets/issues/65
This PR sets up slack notifications for the 3 cron jobs in this repository. Note that I manually triggerred the cron jobs to check that the slack notifications actually show up - and they do.
**Checklist**
=> Setup slack notification for cron jobs

.readthedocs.yaml, traitsui/__init__.py
This PR adds a basic configuration file for Read the Docs. These changes are based on enthought/traits#1478. This is one more step towards enthought/ets#69.
This PR also add a `docs` `extras_require` when installing `traitsui` to make it easy to build the sphinx docs.
**Checklist**
=> Add an RtD config file

docs/releases/upcoming/1728.bugfix.rst, traitsui/qt4/instance_editor.py, traitsui/tests/editors/test_instance_editor.py
closes #1134 
I've been testing this locally using:
```
from traits.api import Button, HasStrictTraits, Instance, List, Str, observe
from traitsui.api import EnumEditor, InstanceEditor, Item, VGroup, View
class Option(HasStrictTraits):
name = Str()
class Model(HasStrictTraits):
selected_option = Instance(Option)
all_options = List(Instance(Option))
reset_to_none = Button()
change_options = Button()
selected_name = Str()
all_names = List(Str)
view = View(
VGroup(
Item('selected_option', label='InstanceEditor',
editor=InstanceEditor(name='all_options', editable=False)),
Item('selected_name', label='EnumEditor',
editor=EnumEditor(name='all_names')),
Item('reset_to_none'),
Item('change_options')
),
)
@observe('reset_to_none')
def do_stuff(self, event):
self.selected_option = None …
```
=> Fix Qt InstanceEditor appearance when None selected

docs/releases/upcoming/1731.bugfix.rst, traitsui/qt4/range_editor.py, traitsui/tests/editors/test_range_editor.py
closes #737
This PR simply forces the value to be `self.low` if a value outside of the range is given.  This is similar to what the `SimpleSliderEditor` / other range editors do. 
I've tested manually with the example in the issue and added a comparable regression test.
~I still need to investigate wx - hence the WIP title for now~ EDIT: looks like wx was already doing the right thing
**Checklist**
=> Prevent RangeTextEditor from allowing values outside range

docs/releases/upcoming/1726.feature.rst, traitsui/qt4/tree_editor.py, traitsui/tests/editors/test_tree_editor.py
closes #673 
This PR took inspiration from the `expand_levels` method here:
https://github.com/enthought/traitsui/blob/fc3b8ac92eea79efba923ec2387f292c281eddf3/traitsui/qt4/tree_editor.py#L263-L273
and the second response here https://stackoverflow.com/questions/28829192/how-to-get-the-number-of-items-of-a-qtreewidget suggesting to make use of https://doc.qt.io/qt-5/qtreewidgetitemiterator.html#details for easy traversal of a `QTreeWidget`.
I found a lot of the TreeEditor internals hard to follow.  TraitsUI does its own thing setting `node_data` which takes the form `(expanded, node, object)`.  I am unclear on why expanded is included here as it could be directly accessed on the nid object via `nid.isExpanded()`.  However, this is very prevalent throughout the code so I left things as is …
=> add an expand_all method to TreeEditor

docs/source/conf.py
Previously, we manually traversed the file system to extract the `version` and `release` information from `traitsui._version` file. Now, we simply expect `traitsui` to be installed in the python environment when we try building the docs and we just import `version` from `traitsui.__init__`. Note that this PR also removes the `release` variable in the configuration file.
Note that these changes should fix the broken RtD docs build. Ref https://readthedocs.org/projects/traitsui/builds/14256791/
**Checklist**
=> Simply import "version" information from "traitsui.__init__"

docs/releases/upcoming/1733.bugfix.rst, traitsui/qt4/instance_editor.py, traitsui/tests/editors/test_instance_editor.py
=> Fix droppable instance editor

docs/source/traitsui_user_manual/examples/key_bindings.py, docs/source/tutorials/code_snippets/interactive.py, docs/source/tutorials/code_snippets/traits_thread.py, traitsui/editors/shell_editor.py, traitsui/examples/demo/Advanced/Table_editor_with_progress_column.py, traitsui/examples/demo/Standard_Editors/ButtonEditor_demo.py, traitsui/examples/demo/Standard_Editors/ButtonEditor_simple_demo.py, traitsui/examples/demo/Standard_Editors/CSVListEditor_demo.py, traitsui/qt4/table_editor.py
This PR simply replaces all uses of the `_fired` magically named methods with their observe equivalent.
**Checklist**
=> Replace all use of magic named _fired methods with observe

traitsui/qt4/ui_panel.py
This issue was observed when working on #1691, and again while working on addressing #1312.
Previously I remember having run the example code in #1312 without this issue... I recently updated to macOS Big Sur, but I am unsure if that is related.  I do not know what changed to cause this, especially since it appears to be an off by one error (which somehow wasn't a problem before ?).  
In any case, running the example code given in #1312 without this fix I see:
and with this change:
**Checklist**
=> Fix separator alignment

.github/workflows/bleeding-edge.yml, README.rst, docs/source/conf.py, etstool.py
This PR replaces the use of `master` in the repo with `main` as the default branch name has been updated.
**Checklist**
=> Default branch has been renamed from "master" to "main"

docs/source/conf.py
At the moment, the documentation links to examples on the `main`/default branch. This isn't right because the examples might change in between releases, potentially confusing users who are referring to the documentation. This PR fixes that problem by making the documentation use version-specific links i.e. for the 7.2.1 release, the `7.2.1` tag will be used instead of the `main` branch.
I tested this locally by checking the links generated in the built docs - the examples links will be broken as expected as the dev version has no corresponding tag on GitHub. I then hardcoded the version in the sphinx configuration to `7.2.1` and the links worked as expected, pointing to the `7.2.1` tree instead of `main`.
**Checklist**
=> Don't link to examples on the main branch in documentation

docs/releases/upcoming/1745.bugfix.rst, traitsui/qt4/tree_editor.py, traitsui/wx/tree_editor.py
=> Fix incorrect items added in Tree Editor

docs/releases/upcoming/1738.bugfix.rst, traitsui/instance_choice.py
Closes #1480. This avoids some issues when instanciating "InstanceChoiceItem", which is incorrect.
**Checklist**
=> Convert `InstanceChoiceItem` into a subclass of `ABCHasStrictTraits`

traitsui/list_str_adapter.py, traitsui/qt4/list_str_editor.py, traitsui/qt4/table_editor.py, traitsui/qt4/tabular_editor.py, traitsui/table_column.py, traitsui/tabular_adapter.py, traitsui/wx/list_str_editor.py, traitsui/wx/tabular_editor.py
This PR replaces several traits declared with type `Any({})`  to have type `Dict` instead.
I'm not sure why these lines were using `Any({})`, but I suspect that they long predate modern Traits and relied on the old `TraitHandler` inference mechanisms.
The main motivation for this PR was enthought/traits#1532: currently there's some special-casing in Traits that treats a `list` or `dict` default value to `Any` specially, making a copy of that default value for each relevant `HasTraits` instance. We're considering deprecating and eventually removing that special-casing. That would cause a behaviour change for the cases  changed in this PR. (Within the whole of ETS, these were the only pieces of current code found that would be affected by such a change.)
Independent of whether that change …
=> Replace uses of Any({}) with Dict()

traitsui/tests/ui_editors/test_data_frame_editor.py, traitsui/ui_editors/data_frame_editor.py
part of #1751 
This PR fixes the `NameError` by importing `warnings` and adds a simple test that accessing or assigning `scroll_to_row_hint` causes a `DeprecationWarning`
**Checklist**
=> fix NameError and add test for warnings

.github/workflows/bleeding-edge.yml, .github/workflows/test-etsdemo.yml, .github/workflows/test-with-edm.yml, .github/workflows/test-with-pip.yml
This PR upgrades EDM to the latest available version - 3.3.0 - on the CI.
**Checklist**
=> Upgrade edm to use the latest version on CI - 3.3.0

docs/releases/upcoming/1791.bugfix.rst, traitsui/qt4/list_editor.py, traitsui/tests/editors/test_list_editor.py, traitsui/wx/list_editor.py
=> Fix NotebookEditor initial selected

docs/releases/upcoming/1804.bugfix.rst, traitsui/qt4/range_editor.py, traitsui/tests/editors/test_range_editor.py
This PR adds a simple fix for providing enter set behavior for the simple spin editor.  As with some other editors, this behavior is enabled by setting `auto_set` to False (the value of `enter_set` doesn't actually matter).
ref: https://doc.qt.io/archives/qt-4.8/qabstractspinbox.html#keyboardTracking-prop
**Checklist**
=> Fix SimpleSpinEditor "enter set" on qt

traitsui/qt4/ui_base.py
On a conda-forge env, I got this error when setting up a window in a test where I have warnings turn into errors:
<details>
```
mne_kit_gui/tests/test_kit2fiff_gui.py:122: in test_kit2fiff_gui
ui, frame = mne.gui.kit2fiff()
../../anaconda3/envs/mne-kit-gui/lib/python3.9/site-packages/mne/gui/__init__.py:241: in kit2fiff
return _initialize_gui(frame)
../../anaconda3/envs/mne-kit-gui/lib/python3.9/site-packages/mne/gui/__init__.py:16: in _initialize_gui
return frame.edit_traits(view=view), frame
../../anaconda3/envs/mne-kit-gui/lib/python3.9/site-packages/traits/has_traits.py:1825: in edit_traits
return view.ui(
../traitsui/traitsui/view.py:450: in ui
ui.ui(parent, kind)
../traitsui/traitsui/ui.py:235: in ui
self.rebuild(self, parent)
../traitsui/traitsui/qt4/toolkit.py:168: in ui_live …
```
=> BUG: Cast to int to avoid deprecation warning

traitsui/qt4/title_editor.py, traitsui/qt4/ui_panel.py, traitsui/wx/title_editor.py, traitsui/wx/ui_panel.py
This removes a deprecation warning coming from a change in Pyface behaviour. Additionally it adds proper disposal of the HeadingText Widget to the TitleEditor.  It would be nice to do the same for the ui_panel code, but there is no available hook and deeper architectural issues with the code.
**Checklist**
=> Use two-phase HeadingText creation from Pyface 7.4.0.

docs/releases/upcoming/1810.bugfix.rst, etstool.py, traitsui/qt4/image_editor.py, traitsui/tests/editors/test_image_editor.py, traitsui/wx/image_control.py, traitsui/wx/image_editor.py
Currently code is doing a check for `ImageResource`.  Includes smoke tests for expected functionality.
**Checklist**
=> Support changing images in ImageEditor for all IImage subclasses

docs/releases/upcoming/1823.feature.rst, traitsui/api.py
Does what it says.
Fixes #1799.
**Checklist**
=> Add `ListStrAdapter` to `traitsui.api`

traitsui/qt4/extra/qt_view.py
This doesn't mean that stylesheets work, just that there is no crash.  Also update the docstring to indicate why it won't work.
See #1788 - this is only a partial fix.
**Checklist**
=> QtView shouldn't crash for modal kinds.

docs/releases/upcoming/1821.bugfix.rst, traitsui/qt4/constants.py
This also adds a dark mode flag in the constants module.
Mac light mode error:
Mac dark mode error:
This is not dynamic, however - if dark mode changes while app is running, may get odd effects.
See #1796 and #1810 
**Checklist**
=> Set default colors for Qt toolkit to work better in dark mode

docs/releases/upcoming/1817.bugfix.rst, traitsui/key_bindings.py, traitsui/tests/test_key_bindings.py
This cleans up the KeyBindings classes to make the semantics a bit clearer and to fix some issues.  In particular, this removes the ad-hoc creation of `List` traits with fixed length in favour of using a `readonly` list editor, which fixes #1805 without any change to the UX.
Additionally it removes the use of old `event` metadata in favour of a modern, standard `observe` pattern.
Also adds tests.
**Checklist**
=> Clean up KeyBindings.

docs/releases/upcoming/1819.feature.rst, traitsui/qt4/font_trait.py, traitsui/qt4/tests/test_font_trait.py, traitsui/wx/font_trait.py, traitsui/wx/tests/test_font_trait.py
This adds support for Pyface Font traits, as well as tests.
This does some fussing around with the way font families are handled - they seem to have little effect on qt4 and OS X, while on wx they are very powerful and may override the user's preferred font.  I've adjusted the way things work slightly such that I hope it makes a little better sense, in particular to make sure that the font family gets included in the string version of the code (since that is used for pickling, it seemed important!) - the tests show the behaviour.
This code is likely to be deprecated/replaced in the next release, so the tests are probably the most important piece as they document current behaviours.
**Checklist**
=> Improvements for Font traits

docs/releases/upcoming/1812.feature.rst, traitsui/qt4/color_trait.py, traitsui/qt4/tests/test_color_trait.py, traitsui/wx/color_trait.py, traitsui/wx/tests/test_color_trait.py
In addition this PR standardizes the set of recognized color names to those that Pyface `Color` understands (basically all web colors, which aligns with Enable/Chaco).  Previously these were just whatever the backend understood.
This includes tests for the `PyQtColor` and `WxColor` traits (which correspond to the traits.api `Color` trait) and which were previously absent.
**Checklist**
=> Support Pyface `Color` in TraitsUI toolkit Color traits.

traitsui/qt4/ui_panel.py, traitsui/wx/ui_panel.py
closes #1768 
WIP label because the still needs a test.  support was introduced in #1544, but that needs a test as well.  Not sure if I will have the time to write a test on this, but wanted to open a PR with the simple fix now so it isn't forgetten. (previous comment about difficulty I had writing tests for Labels {enabled/visible}_when https://github.com/enthought/traitsui/pull/1544#issuecomment-823551479)
Note that for "normal" enabled/visible when we have `cond_value` come up in an `if` statement: https://github.com/enthought/traitsui/blob/87dceb219b8b7b547907f031aaca70e1a66b7945/traitsui/ui.py#L793
In the code here we really do want to always pass a bool to `setVisible` or `setEnabled`.
**Checklist**
=> Call Bool before evaluating {enabled/visible}_when condition for labels

docs/releases/upcoming/1832.feature.rst, traitsui/examples/demo/Advanced/Adapted_tree_editor_demo.py, traitsui/examples/demo/Advanced/Auto_editable_readonly_table_cells.py, traitsui/examples/demo/Advanced/Invalid_state_handling.py, traitsui/examples/demo/Advanced/Settable_cached_property.py, traitsui/examples/demo/Advanced/Table_editor_with_live_search_and_cell_editor.py, traitsui/ui.py
Mostly this is just replacing with appropriate `observe` metadata, but in one example the text description needed significant updating.
Fixes #1730
**Checklist**
=> Remove usage of `property_depends_on`

traitsui/editor.py, traitsui/qt4/editor.py, traitsui/tests/test_editor.py, traitsui/wx/editor.py
This allows us to use the same error-handling code cross-platform, modulo a little tweaking for editors which wrap `QLayout` instead of `QWidget`.
This should be transparent to tests - the underlying widgets are the same, we just create them differently.
**Checklist**
=> Use Pyface's message dialogs in errors instead of rolling our own

traitsui/qt4/directory_editor.py, traitsui/qt4/file_editor.py, traitsui/wx/directory_editor.py, traitsui/wx/file_editor.py
This has the potential to allow more common code between the two editors, but not in this PR.
No new tests, unfortunately, as we don't have a way to drive the file dialogs once they are open.
**Checklist**
=> Use Pyface file dialogs instead of creating custom ones

traitsui/qt4/color_trait.py
When testing on Python 3.8 with certain versions of PySide6 we were getting a segfault when a tuple with a string value was passed as a color.  This should raise a `TraitError`, not segfault.
**Checklist**
=> Small fix for segfault when non-int values given to `QColor`

traitsui/qt4/tree_editor.py, traitsui/wx/tree_editor.py
This should fix #1839.
The issue was a for loop that was iterating over all the nodes in a selection, but then using the `node` variable from the loop as if it were the selection, leading to a mismatch between the selected `object` and the `node`.  The `View` for the editor came from the `node` and so might not be correct for the `object`, leading to a crash and segfault.
The fix is to break once the selection has been identified.
Can't easily test other than manually, and the Wx fix is blocked by #1845.  The sample code from #1839 is fairly straightforward to run and to get a replication.
**Checklist**
=> Fix `TreeEditor` extended selection bug

traitsui/qt4/file_editor.py, traitsui/tests/editors/test_file_editor.py, traitsui/wx/file_editor.py
Closes #1859 
This PR fixes a mis-named attribute accession in the `FileEditor`'s Qt and Wx implementation. Since the bug makes the editor unusable, I think this will warrant a hotfix release.
=> FIX: correct attribute name

traitsui/editor.py, traitsui/tests/test_regression.py
The last traitsui release introduced a regression where doing `from traitsui.view import View` would end up importing a toolkit backend. This is tested and fixed.  I am not sure if this is an appropriate test case but here it is.  This is related to https://github.com/enthought/mayavi/pull/1139
=> Delay importing toolkit when importing View.

traitsui/testing/tester/_ui_tester_registry/qt4/tests/test_interaction_helpers.py
This PR weakens the `test_key_click` test to check that when the Enter key is pressed inside a QTextEdit, the `textChanged` event is fired at least once. Previously, the test checked that the event was fired _exactly_ once, but that check fails on Windows / PySide 6, for reasons that I haven't been able to track down. This may be a PySide6 or Qt bug, but I haven't found any relevant bug report.
I suspect that for our purposes it should be good enough that `textChanged` is fired at all; we shouldn't need to care too much about how many times it's fired.
Closes #1895.
=> Add workaround for test_key_click failure on Windows/PySide6

.github/workflows/test-with-edm.yml
This PR allows the main test workflow to be run manually if desired. This is convenient when debugging CI failures - the workflow can be run directly on a test branch, without needing to first create a PR for that branch.
=> Allow main test workflow to be run manually

traitsui/__init__.py
This PR updates the behaviour of `pip install .[pyside6]` to avoid known-bad PySide6 versions on Python 3.6 and Python 3.7. It should have no effect on Python >= 3.8.
With a bit of luck, this should get our install-from-PyPI cron job back to working.
Note: I also removed the explicit "shiboken6" and "shiboken2" requirements: we don't depend directly on shiboken at all, and for a PyPI install it should always be installed automatically as a dependency of the appropriate version of PySide.
=> Avoid broken PySide6 versions on Python 3.6 and 3.7

.github/workflows/bleeding-edge.yml, .github/workflows/integration-tests.yml, .github/workflows/test-with-pip.yml
This PR updates the scheduled workflows to report failures to the main ETS channel rather than the more noisy bots channel, in the hope that they're more likely to be noticed there. Successes continue to be reported to the bots channel.
=> Report cron job failures to main Slack channel, not bots channel

traitsui/__init__.py
The `pillow` package is used by the `VideoEditor_demo.py`, but is not mentioned in the `examples` list under `__extras_require__`.
With luck, this PR should get the integration tests workflow passing again.
=> Add missing dependency for examples

traitsui/tests/editors/test_range_editor.py
This PR adds a skip for a test that hangs on wxPython. On my machine, the wxPython test run now executes to completion on my machine. (It has many failures and an occasional segfault, but that seems like a slightly better state than a hang - we at least get to find out how many tests failed.)
Closes #1901.
=> Fix test suite hang on wx

docs/releases/upcoming/1907.bugfix.rst, traitsui/qt4/image_editor.py, traitsui/tests/editors/test_image_editor.py
=> If `Image` is `None`, use default `paintEvent` handler only in Qt `ImageEditor`

docs/releases/upcoming/1904.doc.rst, docs/source/conf.py, etstool.py, traitsui/__init__.py
This PR does the following: 
- Use the `sphinx_copybutton` extension when building the Sphinx documentation
- Make `sphinx-copybutton` as a `docs` extra for the `traitsui` package
- Install `sphinx-copybutton` from PyPI when building docs using the `etstool.py` utility.
Ref https://sphinx-copybutton.readthedocs.io/en/latest/
**Checklist**
=> Use the "sphinx-copybutton" extension in documentation

.github/actions/apt-get-qt-deps/action.yml, docs/releases/upcoming/1908.bugfix.rst, integrationtests/test_all_examples.py, traitsui/examples/demo/Standard_Editors/VideoEditor_demo.py, traitsui/qt4/video_editor.py, traitsui/tests/editors/test_video_editor.py
Get basic `VideoEditor` functionality up and working for Qt6.  There have been considerable changes to the way that QtMultimedia works.
Can't (yet) handle editing the video frames along the way, but it is technically feasible: the problem is that the mechanism is completely different in Qt6 and still needs some investigation.
Fixes #1905.
**Checklist**
=> Fixes for Qt6 VideoEditor

traitsui/qt4/list_str_editor.py
Fixes #1888.  This only manifested as incomplete clean-up in test suites on an internal Enthought project - no errors were generated even without the fix.
**Checklist**
=> Properly dispose of any header view for the ListStrEditor.

docs/releases/upcoming/1910.bugfix.rst, traitsui/qt4/image_enum_editor.py, traitsui/tests/editors/test_image_enum_editor.py
This fixes #844 and fixes #1890.
**Checklist**
=> Fix updates for ImageEnumEditor

traitsui/qt4/range_editor.py
Closes #1923.  Makes the qt range text editor accept a none value for either the high or low value. 
**Checklist**
=> Fix range text editor bug

traitsui/testing/tester/_ui_tester_registry/qt4/_interaction_helpers.py, traitsui/testing/tester/_ui_tester_registry/wx/_interaction_helpers.py, traitsui/testing/tester/_ui_tester_registry/wx/_traitsui/button_editor.py
Drive-by PR to cleanup some typos I noticed while reading through the UITester code
=> FIX: typos in UITester docstrings mouce -> mouse

docs/releases/upcoming/1927.bugfix.rst, traitsui/qt4/extra/progress_renderer.py
Should fix #1936.
**Checklist**
=> Fix progress column rendering on linux and windows

CHANGES.txt, docs/releases/upcoming/1927.bugfix.rst, traitsui/qt4/extra/progress_renderer.py, traitsui/qt4/range_editor.py
Backport PR #1931 to the `maint/7.4` branch.
**Checklist**
=> Backport fixes in prep for version 7.4.1 and update changelog

.github/workflows/bleeding-edge.yml, .github/workflows/integration-tests.yml, .github/workflows/publish-on-pypi.yml, .github/workflows/test-with-pip.yml
This protects against spurious workflow failures from repos that don't have access to Enthought resources (Slack, PyPI credentials, etc.).  This is mainly a noise-reduction fix.
**Checklist**
=> Restrict some workflows to Enthought repo only

docs/releases/upcoming/1960.bugfix.rst, traitsui/qt4/tree_editor.py
This replaces `QAbstractTreeView.viewOptions()` with `initViewItemOption()`, and this seems to be a drop-in replacement.
I can't see how to test this fix in CI.
Fixes #1959
**Checklist**
=> Fix rendering of dragged tree nodes on Qt6

docs/releases/upcoming/1973.bugfix.rst, traitsui/qt4/helper.py, traitsui/qt4/tests/test_helper.py, traitsui/qt4/tree_editor.py
This change makes checks that the underlying Qt `QTreeViewItem` exists before attempting to access any data stored on it.  This hopefully resolves some issues observed in PySide6 which I suspect were caused by a change in API from returning `AttrbuteError` to `RuntimeError` when accessing that data.
**Checklist**
=> Protect against deleted nodes in Qt `TreeEditor`

docs/releases/upcoming/1967.bugfix.rst, traitsui/qt4/date_editor.py
This change:
- shows the calendar page with the current value when started
- if multi-select is true, it shows the page with the earliest date
- when the date changes externally in single-select mode it also updates
This fixes #1942
**Checklist**
=> Display the selected date in the DateEditor in custom style.

docs/releases/upcoming/1964.bugfix.rst, traitsui/editors/datetime_editor.py, traitsui/examples/demo/Standard_Editors/DatetimeEditor_demo.py, traitsui/qt4/datetime_editor.py, traitsui/tests/editors/test_datetime_editor.py, traitsui/tests/test_datetime.py
Add `allow_none` to `Datetime` bounds in `DatetimeEditor` and to other uses of `Datetime` in tests and examples.
This fixes a deprecation warning with recent traits.
Fixes #1963.
**Checklist**
=> Add explicit `allow_none` in Datetime traits.

docs/releases/upcoming/1966.bugfix.rst, traitsui/qt4/table_editor.py
This removes the `empty_menu`, `header_menu` and related traits.  As a result there is a small chance of backwards incompatibility, however:
- there are no uses of these traits found in a quick search of the Enthought codebase
- any code using these traits is likely buggy, as discovered in #1947
The fixes #1947
**Checklist**
=> Generate extra `TableEditor` menus dynamically

LICENSE.txt, docs/source/traitsui_user_manual/index.rst, ets-demo/LICENSE.txt
Missed a few copyright updates because I was filtering for Python files only.
=> Update copyright notice in 2023 for non-python files.

traitsui/tests/test_key_bindings.py, traitsui/tests/test_view_application.py
I was getting some errors in the tests about relative imports.
=> Replace some relative imports in tests

traitsui/wx/directory_editor.py, traitsui/wx/file_editor.py
File (and directory editors) are broken in current head (and the last couple of releases). See traceback below.
```
File "/Users/david/dev/traitsui/traitsui/wx/file_editor.py", line 147, in show_file_dialog
dlg = self._create_file_dialog()
File "/Users/david/dev/traitsui/traitsui/wx/file_editor.py", line 209, in _create_file_dialog
default_path=self._file_name.text(),
AttributeError: 'TextCtrl' object has no attribute 'text'
```
This looks like it can be traced to #1829, which seems to have copy-pasted the `FileDialog` creation code verbatim from the QT version into the wx version. Replacing the `.text()` call with the wx equivalent `.GetValue()` seems to fix things. Thought I'd submit a PR directly seeing as I had a simple fix, but happy to create an …
=> Fix regression in wx version of FileEditor

traitsui/qt4/instance_editor.py
Fixed the error mentioned in issue #1988.
=> Fix error: 'InstanceFactoryChoice' object has no attribute 'object'

traitsui/tests/test_undo.py, traitsui/undo.py
Fixes #1515.  Also removes a no-longer used `history` trait.
This completes the transition of TraitsUI undo/redo to share the same basis as the Pyface/Apptools undo/redo.
There is still an issue in #1060 that is unresolved which is about refactoring TraitsUI to be more command-stack based, rather than building the command stack reactively.
**Checklist**
=> Remove `merge_undo` from undo code.

traitsui/qt/file_editor.py, traitsui/wx/file_editor.py
The `FileDialog.action` can have values `open`, `open files`, or `save as`, see https://github.com/enthought/pyface/blob/a9bf0264cb2afe9d05ce8856de650fd6efbc2684/pyface/ui/wx/file_dialog.py#L37 and https://github.com/enthought/pyface/blob/a9bf0264cb2afe9d05ce8856de650fd6efbc2684/pyface/ui/qt/file_dialog.py#L36.
The `dialog_style` on the other hand can have values `open` and `save`, see https://github.com/enthought/traitsui/blob/c08f891c19e5464e308cb9c6c14e77599e11b132/traitsui/editors/file_editor.py#L77-L78
As such, the logic for converting from `dialog_style` to `action` was the wrong way around. As a result,
the file dialog would always open in "open" mode.
=> Fix logic for selecting action in file dialog

traitsui/tree_node.py
The `'fast_ui'` dispatch mechanism is identical to the `'ui'` dispatch mechanism. It's not used by the `fast_ui` name anywhere in ETS outside the the TraitsUI `TreeNode` implementation.
This PR replaces use of `fast_ui` with `ui`; this should allow us to deprecated and remove the `fast_ui` dispatch method in Traits at some point in the future.
=> Replace 'fast_ui' dispatch with 'ui' dispatch

traitsui/examples/demo/Advanced/Scrubber_editor_demo.py
As mentioned in issue #2010, a NotImplementedError: the qt traitsui.qt backend doesn't implement scrubber_editor:_ScrubberEditor will be raised when running this example without wx. Viewing the code (https://github.com/enthought/traitsui/blob/main/traitsui/wx/scrubber_editor.py ) suggests that ScrubberEditor is only implemented for wx version of the code  However, this is not explicitly mentioned in the demo. This PR add lines to mention this explicitly. closes #2010 
**Checklist**
=> MAINT: add note for wx only use for scrubber finder

traitsui/tests/editors/test_date_range_editor.py
This adds `allow_none=True` to the traits on the model used for the test case.
Fixes #2018
=> Fix date range editor tests: allow `None` for test traits.

examples/tutorials/traitsui_4.0/editors/animated_gif.py
The traitsui/examples/tutorials/traitsui_4.0/editors/animated_gif.py will generate a RuntimeError: Importing from wx backend after selecting qt backend!. The cause of this error comes from assert_toolkit_import(["wx"]) in traitsui/traitsui/toolkit.py. Althought removing this line can suppress this problem, this demo is supposed to be wx only, thus I push this PR to add the message. closes #2016 
**Checklist**
=> MAINT:add comment to explain the example as wx only

traitsui/qt/image_enum_editor.py
**Checklist**
This seems to be needed in Fedora Rawhide with PyQt6 6.5.1.
=> Use QtGui.QStyle.SubControl.SC_ComboBoxArrow

traitsui/qt/video_editor.py
On windows machines, the file open object that Qt creates is kept after the VideoEditor UI is destroyed.
So (for example) deleting the file after viewing it is not possible, giving `PermissionError: [WinError 32] The process cannot access the file because it is being used by another process:`.
This PR adds a line to the UI destroy part of the VideoEditor to [ensure `setSource`](https://doc.qt.io/qtforpython-6/PySide6/QtMultimedia/QMediaPlayer.html#PySide6.QtMultimedia.PySide6.QtMultimedia.QMediaPlayer.setSource) is set to empty string to close any previous connections.
Adapted from the VideoEditor demo in TraitsUI
<details>
<summary>Below fails without change, and succeeds after changes</summary>
Replace the path and video filename with your test video file.
```python
#
#
"""
Demonstrates …
```
=> FIX: [Only Windows] VideoEditor release file open on UI close

traitsui/__init__.py
Replaces `impportlib` with `importlib` in the warning message for `traitsui.__version__`.
**Checklist**
=> Fix a typo in a warning message

traitsui/tests/editors/test_instance_editor.py
See Issue #2038 - this is a work-around to get tests back into working state, but does not resolve the issue.
Includes incidental black and isort clean-up.
=> Skip tests on PySide6 6.6.1
